import {useContext} from 'react';
import {CaptionDefaults} from '../caption-defaults';
import type {CaptionSettings} from '../../config/captions/types';
import {useEffect,useLayoutEffect,useRef,useState,useId,type CSSProperties} from 'react';
import {createPortal} from 'react-dom';
import './ColorPicker.scss';
const palette=['#ffffff','#000000','#62667e','#9599aa','#bdc0cb','#dadce3','#eeeeF1','#ff544f','#ff9843','#ffe455','#50ad62','#358ded','#6954ff','#ba49e5','#f95baf','#ffabaa','#ffd0ad','#fff3ab','#b9dfbf','#afd0fa','#c5bcff','#e7bcf7','#ffd0e6'];
function channels(value:string){const v=value.replace('#','');const hex=v.length===3?v.split('').map(c=>c+c).join(''):v;return [0,2,4].map(i=>parseInt(hex.slice(i,i+2),16)||0);}
function hsv(value:string){const [r,g,b]=channels(value).map(v=>v/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;return {h:d?((max===r?(g-b)/d+(g<b?6:0):max===g?(b-r)/d+2:(r-g)/d+4)*60):0,s:max?d/max:0,v:max};}
function hex(h:number,s:number,v:number){const c=v*s,x=c*(1-Math.abs(h/60%2-1)),m=v-c,rgb=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return '#'+rgb.map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('');}
export function ColorPicker({value,onChange,settingKey,onReset}:{value:string;onChange:(event:{target:{value:string}})=>void;settingKey?:keyof CaptionSettings;onReset?:()=>void}){
 const defaults=useContext(CaptionDefaults),original=settingKey?defaults[settingKey]:undefined;
 const reset=onReset??(typeof original==='string'?()=>onChange({target:{value:original}}):undefined);
 const gradientId=useId().replace(/:/g,'');const [format,setFormat]=useState<'hex'|'rgb'>('hex');const [formatOpen,setFormatOpen]=useState(false);
 const [open,setOpen]=useState(false),[color,setColor]=useState(()=>hsv(value)),[draft,setDraft]=useState(value.slice(0,7)),[alpha,setAlpha]=useState(value.length===9?Math.round(parseInt(value.slice(7),16)/255*100):100),[pos,setPos]=useState({left:8,top:8});
 const root=useRef<HTMLButtonElement>(null),panel=useRef<HTMLDivElement>(null);
 const [brand,setBrand]=useState<string[]>(()=>{try{const saved=JSON.parse(localStorage.getItem('edita-brand-colors')||'[]');return Array.isArray(saved)?saved.filter((c:unknown)=>typeof c==='string'&&/^#[0-9a-f]{6,8}$/i.test(c)).slice(0,12):[];}catch{return [];}});
 useEffect(()=>{setColor(hsv(value));setDraft(value.slice(0,7));setAlpha(value.length===9?Math.round(parseInt(value.slice(7),16)/255*100):100);},[value]);
 useLayoutEffect(()=>{root.current?.style.setProperty('background',value,'important');},[value,open]);
 const emit=(base:string,a=alpha)=>{setDraft(base);onChange({target:{value:a===100?base:base+Math.round(a/100*255).toString(16).padStart(2,'0')}});};
 useLayoutEffect(()=>{if(!open)return;const place=()=>{const r=root.current?.getBoundingClientRect(),p=panel.current;if(!r||!p)return;setPos({left:Math.max(8,Math.min(innerWidth-p.offsetWidth-8,r.left)),top:Math.max(8,Math.min(innerHeight-p.offsetHeight-8,r.bottom+6))});};place();window.addEventListener('resize',place);window.addEventListener('scroll',place,true);return()=>{window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true);};},[open,brand.length]);
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node)&&!panel.current?.contains(e.target as Node))setOpen(false);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.stopPropagation();if(formatOpen){setFormatOpen(false);panel.current?.querySelector<HTMLButtonElement>('.edita-color-format>button')?.focus();}else{setOpen(false);root.current?.focus();}}};document.addEventListener('pointerdown',outside,true);document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('pointerdown',outside,true);document.removeEventListener('keydown',key,true);};},[open,formatOpen]);
 const saturation=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect(),s=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),v=1-Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));setColor(c=>({...c,s,v}));emit(hex(color.h,s,v));};
 const eye=async()=>{const api=window as unknown as {EyeDropper?:new()=>{open:()=>Promise<{sRGBHex:string}>}};if(!api.EyeDropper)return;try{const result=await new api.EyeDropper().open();emit(result.sRGBHex);}catch{/* User cancelled the eyedropper. */}};
 return <><button ref={root} type="button" className="edita-native-color" style={{'--picked-color':value} as CSSProperties} aria-label={'Odaberi boju '+value} aria-expanded={open} onClick={()=>{setOpen(v=>!v);setFormatOpen(false);}}/>{open&&createPortal(<div ref={panel} className="edita-color-popover" role="dialog" aria-label="Izbor boje" style={pos} onPointerDown={e=>e.stopPropagation()}>
  {reset&&<button type="button" className="edita-color-reset" title="Vrati izvornu boju" onClick={reset}>↶ Vrati izvornu boju</button>}
  <div className="edita-color-sv" tabIndex={0} role="slider" aria-label="Zasićenost i svjetlina; lijevo/desno mijenja zasićenost, gore/dolje svjetlinu" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(color.s*100)} aria-valuetext={Math.round(color.s*100)+'% zasićenosti, '+Math.round(color.v*100)+'% svjetline'} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const s=Math.max(0,Math.min(1,color.s+(e.key==='ArrowRight'?.01:e.key==='ArrowLeft'?-.01:0))),v=Math.max(0,Math.min(1,color.v+(e.key==='ArrowUp'?.01:e.key==='ArrowDown'?-.01:0)));setColor(c=>({...c,s,v}));emit(hex(color.h,s,v));}} style={{backgroundColor:hex(color.h,1,1)}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);saturation(e);}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))saturation(e);}}><svg className="edita-sv-paint" width="100%" height="100%" aria-hidden="true"><defs><linearGradient id={gradientId+'white'}><stop offset="0" stopColor="#fff"/><stop offset="1" stopColor="#fff" stopOpacity="0"/></linearGradient><linearGradient id={gradientId+'black'} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#000" stopOpacity="0"/><stop offset="1" stopColor="#000"/></linearGradient></defs><rect width="100%" height="100%" fill={hex(color.h,1,1)}/><rect width="100%" height="100%" fill={'url(#'+gradientId+'white)'}/><rect width="100%" height="100%" fill={'url(#'+gradientId+'black)'}/></svg><span style={{left:color.s*100+'%',top:(1-color.v)*100+'%'}}/></div>
  <input className="edita-hue" aria-label="Nijansa" type="range" min="0" max="359" value={color.h} onChange={e=>{const h=Number(e.target.value);setColor(c=>({...c,h}));emit(hex(h,color.s,color.v));}}/>
  <div className="edita-color-values"><div className="edita-color-code"><div className="edita-color-format"><button type="button" aria-label="Format boje" aria-expanded={formatOpen} aria-haspopup="listbox" onClick={()=>setFormatOpen(current=>!current)}>{format==='hex'?'Hex':'RGB'}<svg className="edita-color-format-chevron" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></button>{formatOpen&&<div className="edita-color-format-menu" role="listbox" aria-label="Format boje" onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();setFormatOpen(false);}}}>{(['hex','rgb'] as const).map(item=><button type="button" role="option" aria-selected={format===item} key={item} onClick={()=>{setFormat(item);setFormatOpen(false);}}>{item==='hex'?'Hex':'RGB'}</button>)}</div>}</div>{format==='hex'?<input aria-label="Hex boja" value={draft} onChange={e=>{setDraft(e.target.value);if(/^#[0-9a-f]{6}$/i.test(e.target.value))emit(e.target.value);}} onBlur={()=>setDraft(value.slice(0,7))}/>:<div className="edita-rgb-inputs">{channels(value).map((channel,i)=><input key={i} type="number" min="0" max="255" aria-label={['Crvena','Zelena','Plava'][i]} value={channel} onChange={e=>{const rgb=channels(value);rgb[i]=Math.max(0,Math.min(255,Number(e.target.value)));emit('#'+rgb.map(n=>Math.round(n).toString(16).padStart(2,'0')).join(''));}}/>)}</div>}</div><label><input aria-label="Opacity boje" type="number" min="0" max="100" value={alpha} onChange={e=>{const a=Math.max(0,Math.min(100,Number(e.target.value)));setAlpha(a);emit(hex(color.h,color.s,color.v),a);}}/>%</label>{'EyeDropper' in window&&<button type="button" onClick={()=>void eye()} title="Uzmi boju s ekrana" aria-label="Uzmi boju s ekrana"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m14 5 5 5M5 16l10-10 3 3L8 19H5zM15 6l2-2a2 2 0 0 1 3 3l-2 2M4 20h4"/></svg></button>}<span className="edita-color-current" style={{background:value}} aria-label="Trenutna boja"/></div>
  <small>MOJE BOJE</small><div className="edita-color-palette">{brand.map(c=><button type="button" key={c} style={{background:c}} aria-label={'Moja boja '+c} onClick={()=>emit(c.slice(0,7),c.length===9?Math.round(parseInt(c.slice(7),16)/255*100):100)}/>)}<button type="button" aria-label="Sačuvaj trenutnu boju" onClick={()=>{const next=[...new Set([...brand,value])].slice(-12);setBrand(next);try{localStorage.setItem('edita-brand-colors',JSON.stringify(next));}catch{/* Storage unavailable. */}}}>+</button></div>
  <div className="edita-color-palette edita-color-presets"><button type="button" className="edita-no-color" aria-label="Bez boje" onClick={()=>emit(hex(color.h,color.s,color.v),0)}/>{palette.map(c=><button type="button" key={c} style={{background:c}} aria-label={'Boja '+c} onClick={()=>emit(c,100)}/>)}</div>
 </div>,document.fullscreenElement||document.body)}</>;
}
