import {AdminSelect} from './BillingSelect/AdminSelect';
import {useCallback,useEffect,useState} from 'react';
import {apiJson} from '../lib/api';
type Controls={upload_limit:number|null;download_limit:number|null;discount_percent:number;affiliate:boolean;remaining:number;verified_email:string;history:{detail:string;created_at:string;actor__username:string}[]};
export function AdminUserControls({userId,onClose}:{userId:number;onClose:()=>void}){
 const [data,setData]=useState<Controls|null>(null),[tokens,setTokens]=useState(0),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[operation,setOperation]=useState(()=>crypto.randomUUID());
 useEffect(()=>{void apiJson<Controls>(`/api/admin/users/${userId}/controls`).then(setData).catch(e=>setError(e.message));},[userId]);
 return <section className="affiliate-card"><button onClick={onClose}>Zatvori postavke korisnika</button><h2>Tokeni, limiti i affiliate popust</h2>{error&&<p role="alert">{error}</p>}{data&&<><p>Preostalo: {data.remaining} tokena · Email: {data.verified_email||'Nije potvrđen'}</p><form className="affiliate-config" onSubmit={async e=>{e.preventDefault();setBusy(true);try{setData(await apiJson(`/api/admin/users/${userId}/controls`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,tokens,reason,operation})}));setTokens(0);setReason('');setOperation(crypto.randomUUID());setError('');}catch(e){setError(e instanceof Error?e.message:'Spremanje nije uspjelo.');}finally{setBusy(false);}}}><label>Dodaj tokene<input type="number" min={0} max={100000} value={tokens} onChange={e=>setTokens(Number(e.target.value))}/></label>{(['upload_limit','download_limit'] as const).map(key=><label key={key}>{key==='upload_limit'?'Upload':'Preuzimanje'} limit (GB)<input type="number" min={0} step="0.01" placeholder="Bez posebnog limita" value={data[key]===null?'':data[key]/1e9} onChange={e=>setData({...data,[key]:e.target.value===''?null:Math.round(Number(e.target.value)*1e9)})}/></label>)}<AdminSelect label="Affiliate popust" disabled={!data.affiliate} value={data.discount_percent} onChange={e=>setData({...data,discount_percent:Number(e.target.value)})}>{[0,5,10].map(n=><option key={n} value={n}>{n}%</option>)}</AdminSelect><label>Razlog promjene<input required minLength={3} maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>Spremi</button></form><p>Limiti važe za tekući period tokena. Prazno koristi zadani limit paketa; 0 blokira nove prenose. Dodavanje tokena čuva postojeće važeće stanje.</p><details><summary>Interna historija promjena</summary>{data.history.map((r,i)=><p key={i}>{r.created_at} · {r.actor__username} · {r.detail}</p>)}</details></>}</section>;
}
export function AdminEmails(){
 const [data,setData]=useState<{configured:boolean;messages:{id:number;user__username:string;recipient:string;subject:string;status:string}[]}|null>(null),[error,setError]=useState('');
 const load=useCallback(()=>apiJson<NonNullable<typeof data>>('/api/admin/emails').then(setData).catch(e=>setError(e.message)),[]);
 useEffect(()=>{void load();},[load]);
 return <section><div className="billing-toolbar admin-section-header"><h2>Emailovi i potvrde</h2><button onClick={()=>void load()}>Osvježi</button></div>{error&&<p role="alert">{error}</p>}{data&&!data.configured&&<p role="status">SMTP nije konfigurisan. Poruke ostaju na čekanju; nisu poslane korisnicima.</p>}<div className="billing-table-wrap"><table className="billing-table"><thead><tr><th>Korisnik</th><th>Email</th><th>Poruka</th><th>Status</th><th>Akcija</th></tr></thead><tbody>{data?.messages.map(r=><tr key={r.id}><td>{r.user__username}</td><td>{r.recipient}</td><td>{r.subject}</td><td>{r.status}</td><td>{['failed','pending'].includes(r.status)&&<button onClick={async()=>{try{await apiJson('/api/admin/emails',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:r.id})});await load();}catch(e){setError(e instanceof Error?e.message:'Slanje nije uspjelo.');}}}>Pokušaj poslati</button>}</td></tr>)}</tbody></table></div></section>;
}

export function AdminPayments(){
 const [data,setData]=useState<{testMode:boolean;liveEnabled:boolean;checkoutEnabled:boolean;invoices:{invoice_id:string;account__user__username:string;amount_paid:number;currency:string;granted:boolean;period_end:string}[];events:{event_id:string;kind:string;processed_at:string}[]}|null>(null),[error,setError]=useState('');
 useEffect(()=>{void apiJson<NonNullable<typeof data>>('/api/admin/payments').then(setData).catch(e=>setError(e.message));},[]);
 return <section><h2>Plaćanja i potvrde</h2><p>Stripe TEST · stvarna naplata je isključena. Uplata je potvrđena tek kad server primi i provjeri Stripe događaj, ne kada se korisnik vrati sa stranice plaćanja.</p>{error&&<p role="alert">{error}</p>}<div className="billing-table-wrap"><table className="billing-table"><thead><tr><th>Korisnik</th><th>Stripe račun</th><th>Iznos</th><th>Tokeni dodijeljeni</th><th>Važi do</th></tr></thead><tbody>{data?.invoices.map(r=><tr key={r.invoice_id}><td>{r.account__user__username}</td><td>{r.invoice_id}</td><td>{(r.amount_paid/100).toFixed(2)} {r.currency}</td><td>{r.granted?'Da':'Ne — historijska uplata'}</td><td>{r.period_end}</td></tr>)}</tbody></table></div>{data&&!data.invoices.length&&<p>Još nema serverski potvrđenih testnih uplata.</p>}<details><summary>Posljednje Stripe potvrde</summary>{data?.events.map(e=><p key={e.event_id}>{e.processed_at} · {e.kind}</p>)}</details></section>;
}
