import {useEffect,useRef,useState} from 'react';
import {apiJson} from '../lib/api';
type Row={id:string;day:string;campaign:string;metric:string;delta:number;reason:string;status:'pending'|'approved'|'rejected';actor:string;at:string};
const labels:Record<string,string>={visits:'Dolasci',registrations:'Registracije',purchases:'Kupovine',pending:'Na čekanju',approved:'Odobreno',rejected:'Odbijeno'};
export function AffiliateReview({userId,onChanged}:{userId:string;onChanged:()=>void}){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[day,setDay]=useState(()=>{const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}),[metric,setMetric]=useState('visits'),[delta,setDelta]=useState('-1'),[campaign,setCampaign]=useState(''),[selected,setSelected]=useState<{row:Row;status:'approved'|'rejected'}|null>(null),[decisionReason,setDecisionReason]=useState('');
 const operation=useRef<{payload:string;id:string}|null>(null),endpoint='/api/admin/affiliates/'+userId+'/corrections';
 useEffect(()=>{let live=true;void apiJson<{items:Row[]}>(endpoint).then(data=>{if(live)setRows(data.items);}).catch(()=>{if(live)setError('Korekcije nisu učitane.');});return()=>{live=false;};},[endpoint]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const fields={day,metric,delta:Number(delta),campaign,reason},payload=JSON.stringify(fields);if(operation.current?.payload!==payload)operation.current={id:crypto.randomUUID(),payload};try{const data=await apiJson<{items:Row[]}>(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,id:operation.current.id})});setRows(data.items);setReason('');operation.current=null;onChanged();}catch(e){setError(e instanceof Error?e.message:'Korekcija nije sačuvana.');}finally{setBusy(false);}}
 async function decide(){if(!selected)return;setBusy(true);setError('');try{const result=await apiJson<{item:Row}>(endpoint+'/'+selected.row.id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:selected.status,expectedStatus:selected.row.status,reason:decisionReason})});setRows(current=>current.map(row=>row.id===result.item.id?result.item:row));setSelected(null);setDecisionReason('');onChanged();}catch(e){setError(e instanceof Error?e.message:'Odluka nije sačuvana.');}finally{setBusy(false);}}
 return <section className="affiliate-card"><h2>Administratorsko odobravanje i korekcije</h2><p>Interno — affiliate ne vidi razloge ni historiju. Odobrena korekcija mijenja zbir, dnevni grafikon i kampanju. Izvorni događaji ostaju sačuvani. Broj preglednika se ne mijenja ručno.</p>{error&&<p role="alert">{error}</p>}<form onSubmit={create}><label>Datum<input type="date" required value={day} onChange={e=>setDay(e.target.value)}/></label><label>Podatak<select value={metric} onChange={e=>setMetric(e.target.value)}>{['visits','registrations','purchases'].map(key=><option key={key} value={key}>{labels[key]}</option>)}</select></label><label>Promjena (+/−)<input type="number" required min="-100000" max="100000" step="1" value={delta} onChange={e=>setDelta(e.target.value)}/></label><label>Kampanja — prazno za neoznačene<input value={campaign} maxLength={48} pattern="[a-zA-Z0-9_-]*" onChange={e=>setCampaign(e.target.value)}/></label><label>Interni razlog<input required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||Number(delta)===0}>Predloži korekciju</button></form>{selected&&<div role="group" aria-label="Potvrda odluke"><h3>{selected.status==='approved'?'Odobri korekciju':'Odbij / poništi korekciju'}: {selected.row.delta>0?'+':''}{selected.row.delta} · {labels[selected.row.metric]}</h3><label>Razlog odluke<input value={decisionReason} maxLength={500} onChange={e=>setDecisionReason(e.target.value)}/></label><button disabled={busy||decisionReason.trim().length<3} onClick={()=>void decide()}>Potvrdi odluku</button><button disabled={busy} onClick={()=>setSelected(null)}>Odustani</button></div>}<div className="billing-table-wrap"><table className="billing-table"><thead><tr><th>Datum / kampanja</th><th>Promjena</th><th>Razlog</th><th>Status</th><th>Akcija</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.day}<br/>{row.campaign||'Bez oznake'}</td><td>{labels[row.metric]}: {row.delta>0?'+':''}{row.delta}</td><td>{row.reason}<br/>{row.actor}</td><td>{labels[row.status]}</td><td>{row.status!=='approved'&&<button disabled={busy} onClick={()=>{setSelected({row,status:'approved'});setDecisionReason('');}}>Odobri</button>}{row.status!=='rejected'&&<button disabled={busy} onClick={()=>{setSelected({row,status:'rejected'});setDecisionReason('');}}>{row.status==='approved'?'Poništi':'Odbij'}</button>}</td></tr>)}</tbody></table></div>{!rows.length&&<p>Nema predloženih korekcija.</p>}<small>Prikazano posljednjih 200 korekcija.</small></section>;
}
