import {OrdinaryPaletteChoices} from './OrdinaryPaletteChoices';
import {StudioStyleControls} from './StudioStyleControls';
import {isStudioStyle} from '../config/captions/studio-collection';
import {SignatureStyleControls} from './SignatureStyleControls';
import {AiStyleControls} from './AiStyleControls';
import {isPresetCaptionStyle} from '../config/captions/style-library';
import {InkImpactControls} from './InkImpactControls';
import {PrismFoldControls} from './PrismFoldControls';
import {NeonRiotControls} from './NeonRiotControls';
import {ColorPicker} from './ColorPicker/ColorPicker';
import {CaptionStyleControls} from './CaptionStyleControls';
import {CaptionRange} from './CaptionRange';
import {CaptionDefaults} from './caption-defaults';
import {templates,settingsForTemplate} from '../config/captions/presets';
import {captionCapabilities,captionTypography} from '../lib/caption-capabilities';
import {useState,useEffect} from 'react';
import {titleSettingsForStyle} from '../lib/caption-selection';
import {CaptionBasicsPanel} from './CaptionBasicsPanel';
import {SettingsPopover} from './SettingsPopover';
import {previewCaptionSound} from '../lib/use-caption-sounds';
import {StudioIcon} from './StudioIcon/StudioIcon';
import type {SetStateAction,ReactNode} from 'react';
import type {CaptionSettings,StyleKey,CaptionTemplate} from '../config/captions/presets';
import {LanguageDropdown} from './LanguageDropdown/LanguageDropdown';
export function CaptionSettingsPanel({onVariant,editedSettings:baseSettings,setEditedSettings:setBaseSettings,openSection,activeStyle,scopeLabel,onReset,actions,wordTools,individualTools,secondaryMode=false,hasTitles=false,editingTitle=false}:{onVariant?:(template:CaptionTemplate)=>void;editingTitle?:boolean;hasTitles?:boolean;openSection?:{view:'menu'|'text'|'animation'|'style';id:number};editedSettings:CaptionSettings;setEditedSettings:(action:SetStateAction<CaptionSettings>)=>void;activeStyle:StyleKey;text:string;scopeLabel?:ReactNode;wordTools?:ReactNode;individualTools?:ReactNode;secondaryMode?:boolean;onReset?:()=>void;actions?:ReactNode}) {
 const [role,setRole]=useState<'ordinary'|'important'|'titles'>('ordinary');
 const variant=(base:CaptionSettings)=>role==='titles'?titleSettingsForStyle(activeStyle,base):role==='important'?{...base,fontFamily:base.secondaryFontFamily||base.fontFamily,fontScale:base.secondaryFontScale??160,fontSizePx:base.secondaryStyle?.fontSizePx,textColor:base.highlightColor,...base.secondaryStyle}:base;
 const capabilities={...captionCapabilities(activeStyle),important:captionCapabilities(activeStyle).important||!!baseSettings.secondaryFontFamily};
 useEffect(()=>{setRole('ordinary');},[activeStyle]);
 const editedSettings=captionTypography(activeStyle,variant(baseSettings));
 const setEditedSettings=(update:SetStateAction<CaptionSettings>)=>setBaseSettings(base=>{
  const before=captionTypography(activeStyle,variant(base)),next=typeof update==='function'?update(before):update;
  if(role==='ordinary'){if(next.fontWeight!==before.fontWeight)return {...next,secondaryStyle:{...next.secondaryStyle,fontWeight:base.secondaryStyle?.fontWeight??(activeStyle==='scriptVerbatim'?400:activeStyle==='captionsScript'?700:before.fontWeight)},titleAppearance:{...next.titleAppearance,fontWeight:base.titleAppearance?.fontWeight??titleSettingsForStyle(activeStyle,base).fontWeight??before.fontWeight}};return next;}
  const patch=Object.fromEntries(Object.entries(next).filter(([key,value])=>!['secondaryStyle','titleAppearance'].includes(key)&&value!==before[key as keyof CaptionSettings]));
  if('displayWordCount' in patch)return {...base,displayWordCount:next.displayWordCount};
  if(role==='titles')return {...base,titleAppearance:{...base.titleAppearance,...patch}};
  return {...base,...('fontFamily' in patch?{secondaryFontFamily:next.fontFamily}:{}),...('fontScale' in patch?{secondaryFontScale:next.fontScale}:{}),...('textColor' in patch?{highlightColor:next.textColor}:{}),secondaryStyle:{...base.secondaryStyle,...patch}};
 });
 const nativeEffects=(              <div className="caption-effect-controls">
 <SignatureStyleControls style={activeStyle} settings={editedSettings} onChange={setEditedSettings}/>
 <InkImpactControls style={activeStyle} settings={editedSettings} onChange={setEditedSettings}/>
 <PrismFoldControls style={activeStyle} settings={editedSettings} onChange={setEditedSettings}/>
 <NeonRiotControls style={activeStyle} settings={editedSettings} onChange={setEditedSettings}/>
 {activeStyle==='captionsScript'&&<LanguageDropdown label="Potez linije" value={editedSettings.scriptLineMode??'full'} options={[{value:'full',label:'Puna linija s povratnim potezom'},{value:'right',label:'Kraća linija · zavoj desno'}]} onChange={value=>setEditedSettings(s=>({...s,scriptLineMode:value as 'full'|'right'}))}/>}
              {activeStyle==='terminalType'&&<LanguageDropdown label="Tipkanje" value={editedSettings.typingUnit??'letters'} options={[{value:'letters',label:'Slovo po slovo'},{value:'words',label:'Riječ po riječ'}]} onChange={value=>setEditedSettings(c=>({...c,typingUnit:value as 'letters'|'words'}))}/>}
              {activeStyle==='premiumOrangeV4'&&<><LanguageDropdown label="Ulazak teksta" value={editedSettings.premiumEntrance??'mixed'} options={[{value:'mixed',label:'Kombinovani · prema referenci'},{value:'upright',label:'Ravni · bijelo i narandžasto'},{value:'italic',label:'Kosi · klizanje odozdo'}]} onChange={value=>setEditedSettings(s=>({...s,premiumEntrance:value as CaptionSettings['premiumEntrance']}))}/><LanguageDropdown label="Riječi u frazi" value={String(editedSettings.premiumPhraseWords??6)} options={[2,3,4,5,6].map(n=>({value:String(n),label:String(n)}))} onChange={value=>setEditedSettings(s=>({...s,premiumPhraseWords:Number(value)}))}/><label><input type="checkbox" checked={editedSettings.glassCamera!==false} onChange={e=>setEditedSettings(s=>({...s,glassCamera:e.target.checked}))}/> Pokret kamere</label><label className="subtitle-size-control"><span>Jačina kamere <b>{editedSettings.glassIntensity??100}%</b></span><CaptionRange settingKey="glassIntensity" resetValue={100} type="range" min="0" max="150" value={editedSettings.glassIntensity??100} onChange={e=>setEditedSettings(s=>({...s,glassIntensity:Number(e.target.value)}))}/></label></>}
              {activeStyle==='metallicCompactV2'&&<>
              <LanguageDropdown label="Metal" value={editedSettings.metallicMaterial??'auto'} options={[{value:'auto',label:'Kombinovani'},{value:'silver',label:'Srebrni'},{value:'red',label:'Tamnocrveni'},{value:'orange',label:'Narandžasti'}]} onChange={value=>setEditedSettings(s=>({...s,metallicMaterial:value as CaptionSettings['metallicMaterial']}))}/>
              <LanguageDropdown label="Zona teksta" value={editedSettings.metallicZone??'mixed'} options={[{value:'mixed',label:'Gornja i donja'},{value:'top',label:'Gornja'},{value:'bottom',label:'Donja'}]} onChange={value=>setEditedSettings(s=>({...s,metallicZone:value as CaptionSettings['metallicZone']}))}/>
              <LanguageDropdown label="Riječi u frazi" value={String(editedSettings.metallicPhraseWords??3)} options={[2,3,4,5,6].map(n=>({value:String(n),label:String(n)}))} onChange={value=>setEditedSettings(s=>({...s,metallicPhraseWords:Number(value)}))}/>
              <label>Tamnocrveni metal<input type="color" value={editedSettings.metallicRed??'#850926'} onChange={e=>setEditedSettings(s=>({...s,metallicRed:e.target.value}))}/></label>
              <label>Srebrni metal<input type="color" value={editedSettings.metallicSilver??'#9db7d1'} onChange={e=>setEditedSettings(s=>({...s,metallicSilver:e.target.value}))}/></label>
              <label className="subtitle-size-control"><span>Jačina odsjaja <b>{editedSettings.metallicShine??100}%</b></span><CaptionRange settingKey="metallicShine" resetValue={100} type="range" min="0" max="150" value={editedSettings.metallicShine??100} onChange={e=>setEditedSettings(s=>({...s,metallicShine:Number(e.target.value)}))}/></label>
              <label><input type="checkbox" checked={editedSettings.glassCamera!==false} onChange={e=>setEditedSettings(s=>({...s,glassCamera:e.target.checked}))}/> Zumiranje videa</label>
              <label className="subtitle-size-control"><span>Jačina zuma <b>{editedSettings.glassIntensity??100}%</b></span><CaptionRange settingKey="glassIntensity" resetValue={100} type="range" min="0" max="150" value={editedSettings.glassIntensity??100} onChange={e=>setEditedSettings(s=>({...s,glassIntensity:Number(e.target.value)}))}/></label>
              <label><input type="checkbox" checked={editedSettings.metallicHoldEnd??false} onChange={e=>setEditedSettings(s=>({...s,metallicHoldEnd:e.target.checked}))}/> Zadrži završni tekst bez izlaza</label>
              </>}
                            {([
                ['waveWords','waveStrength','Jačina valova',0,180,100,1],
                ['captionsScript','scriptWidth','Širina nacrtane linije',60,180,110,1],['captionsScript','scriptDrawDuration','Trajanje crtanja (s)',.1,2,.65,.05],
                ['sketchNote','sketchPen','Debljina markera',30,200,100,1],['sketchNote','sketchEllipseWidth','Širina elipsi',100,160,125,1],['sketchNote','sketchMarkerOpacity','Vidljivost marker-trake',0,100,85,1],
                ['lensFrame','lensMotion','Živost kamere',0,150,60,1],['lensFrame','lensShotInterval','Razmak bliceva (s)',1,12,4.5,.5],
                ['popCollage','popSize','Veličina ukrasa',60,180,125,1],['popCollage','popInset','Ukrasi prema sredini',0,35,12,1],
              ] as const).filter(([style])=>style===activeStyle).map(([,key,label,min,max,fallback,step])=><SettingsPopover key={key} label={label} value={String(editedSettings[key]??fallback)}><label className="caption-popover-range"><span>{label}</span><CaptionRange settingKey={key} resetValue={fallback} aria-label={label} min={min} max={max} step={step} value={editedSettings[key]??fallback} onChange={event=>setEditedSettings(current=>({...current,[key]:Number(event.target.value)}))}/></label></SettingsPopover>)}
{activeStyle==='dynamicGlass'&&<div className="caption-effect-controls">
<label><input type="checkbox" checked={editedSettings.glassCamera!==false} onChange={e=>setEditedSettings(s=>({...s,glassCamera:e.target.checked}))}/> Zoom kadra</label>
<label>Jačina pokreta <CaptionRange settingKey="glassIntensity" resetValue={100} type="range" min="0" max="150" value={editedSettings.glassIntensity??100} onChange={e=>setEditedSettings(s=>({...s,glassIntensity:Number(e.target.value)}))}/></label>
<label>Topla boja stakla <input type="color" value={editedSettings.glassAccentColor||'#ff880c'} onChange={e=>setEditedSettings(s=>({...s,glassAccentColor:e.target.value}))}/></label>
</div>}{!secondaryMode&&['sketchNote','lensFrame','vistaRise','popCollage','primeFrame','stackedHeadlines','sweepTitle','verticalTitle','editorialHeader','boldHeader'].includes(activeStyle)&&<div className="caption-effect-controls"><LanguageDropdown label="Ponašanje efekta" value={editedSettings.effectPlayback||'hold'} options={[{value:'hold',label:'Efekat miruje'},{value:'repeat',label:'Efekat se ponavlja'}]} onChange={value=>setEditedSettings(s=>({...s,effectPlayback:value as 'hold'|'repeat'}))}/><LanguageDropdown label="Idle efekat" value={editedSettings.effectIdle||(activeStyle==='primeFrame'?'float':'none')} options={[{value:'float',label:'Blagi nagib i zoom'},{value:'shimmer',label:'Presijavanje'},{value:'zoom',label:'Blagi zoom'},{value:'tilt',label:'Blagi nagib'},{value:'gradient',label:'Promjena boje / gradient'},{value:'none',label:'Bez pokreta'}]} onChange={value=>setEditedSettings(s=>({...s,effectIdle:value as CaptionSettings['effectIdle']}))}/>{editedSettings.effectIdle==='gradient'&&<label>Druga boja efekta<input type="color" value={editedSettings.effectIdleColor||'#ad79ff'} onChange={e=>setEditedSettings(s=>({...s,effectIdleColor:e.target.value}))}/></label>}</div>}</div>
);
 const styleEffects=<CaptionStyleControls settings={editedSettings} patch={patch=>setEditedSettings(current=>({...current,...patch}))} secondary={secondaryMode||role!=='ordinary'} individual={individualTools} native={<>{nativeEffects}<div className="caption-style-native-extras">              {activeStyle==='goldMesh'&&<SettingsPopover label="Zlatna tekstura">
                <label className="subtitle-size-control"><span>Vanjski okvir <b>{editedSettings.outerOutlineWidth??1.19}px</b></span><CaptionRange settingKey="outerOutlineWidth" resetValue={1.19} type="range" min="0" max="8" step=".1" value={editedSettings.outerOutlineWidth??1.19} onChange={e=>setEditedSettings(c=>({...c,outerOutlineWidth:Number(e.target.value)}))}/></label>
                <label className="subtitle-size-control"><span>Vidljivost teksture <b>{editedSettings.textureOpacity??100}%</b></span><CaptionRange settingKey="textureOpacity" resetValue={100} type="range" min="0" max="100" value={editedSettings.textureOpacity??100} onChange={e=>setEditedSettings(c=>({...c,textureOpacity:Number(e.target.value)}))}/></label>
                <div className="subtitle-color-control"><span>Boja teksture okvira</span><ColorPicker value={editedSettings.highlightColor} onChange={e=>setEditedSettings(c=>({...c,highlightColor:e.target.value}))}/></div>
              </SettingsPopover>}
              {activeStyle==='testSerif'&&<SettingsPopover label="PNG pozadina">
                <label className="subtitle-size-control"><span>Dim oko slova <b>{editedSettings.glyphSmokeScale??115}%</b></span><CaptionRange settingKey="glyphSmokeScale" resetValue={115} type="range" min="100" max="220" step="5" value={editedSettings.glyphSmokeScale??115} onChange={event=>setEditedSettings(current=>({...current,glyphSmokeScale:Number(event.target.value)}))}/></label>
                <label><input type="checkbox" checked={editedSettings.textureBackground!==false} onChange={event=>setEditedSettings(current=>({...current,textureBackground:event.target.checked}))}/> Stalna dimna pozadina</label>
                <label className="subtitle-size-control"><span>Vidljivost pozadine <b>{editedSettings.textureOpacity??70}%</b></span><CaptionRange settingKey="textureOpacity" resetValue={70} type="range" min="0" max="100" value={editedSettings.textureOpacity??70} onChange={event=>setEditedSettings(current=>({...current,textureOpacity:Number(event.target.value)}))}/></label>
                {([['frostWidth','Širina',300],['frostHeight','Visina',400]] as const).map(([key,label,max])=><label className="subtitle-size-control" key={key}><span>{label} <b>{editedSettings[key]??100}%</b></span><CaptionRange settingKey={key} resetValue={100} type="range" min="50" max={max} value={editedSettings[key]??100} onChange={event=>setEditedSettings(current=>({...current,[key]:Number(event.target.value)}))}/></label>)}
                <label className="subtitle-size-control"><span>Trajanje širenja <b>{editedSettings.smokeDuration??2.1} s</b></span><CaptionRange settingKey="smokeDuration" resetValue={2.1} type="range" min=".3" max="3" step=".1" value={editedSettings.smokeDuration??2.1} onChange={event=>setEditedSettings(current=>({...current,smokeDuration:Number(event.target.value)}))}/></label>
              </SettingsPopover>}
              {activeStyle==='stackedHeadlines'&&<LanguageDropdown label="Naslovi u pozadini" value={String(editedSettings.backgroundTitles??4)} options={[1,2,3,4].map(n=>({value:String(n),label:String(n)}))} onChange={value=>setEditedSettings(current=>({...current,backgroundTitles:Number(value)}))}/>}
              {(['prism','prismPop','prismWords'].includes(activeStyle)||editedSettings.fillTexture==='prism')&&<label className="subtitle-size-control"><span>Jačina Prism efekta <b>{editedSettings.prismStrength??100}%</b></span><CaptionRange settingKey="prismStrength" resetValue={100} type="range" min="0" max="100" value={editedSettings.prismStrength??100} onChange={e=>setEditedSettings(current=>({...current,prismStrength:Number(e.target.value)}))}/></label>}



</div></>}/>;
 const additionalEffects=<div className="caption-style-native-extras">              <SettingsPopover label="Ledena pozadina">
                {([['frostWidth','Širenje u širinu',300],['frostHeight','Širenje u visinu',400]] as const).map(([key,label,max])=><label className="subtitle-size-control" key={key}><span>{label} <b>{editedSettings[key]??100}%</b></span><CaptionRange settingKey={key} resetValue={100} type="range" min="50" max={max} step="5" value={editedSettings[key]??100} onChange={event=>setEditedSettings(current=>({...current,[key]:Number(event.target.value)}))}/></label>)}
                <label><input type="checkbox" checked={editedSettings.borderMist??activeStyle==='smokeSerif'} onChange={event=>setEditedSettings(current=>({...current,borderMist:event.target.checked}))}/> Uključi za ovaj stil</label>
                <label className="subtitle-size-control"><span>Širenje ledene pozadine <b>{editedSettings.smokeSpread??65}%</b></span><CaptionRange settingKey="smokeSpread" resetValue={65} type="range" min="0" max="100" value={editedSettings.smokeSpread??65} onChange={e=>setEditedSettings(current=>({...current,smokeSpread:Number(e.target.value)}))}/></label>
                <label className="subtitle-size-control"><span>Trajanje zaleđivanja <b>{editedSettings.smokeDuration??1.2} s</b></span><CaptionRange settingKey="smokeDuration" resetValue={1.2} type="range" min=".3" max="3" step=".1" value={editedSettings.smokeDuration??1.2} onChange={e=>setEditedSettings(current=>({...current,smokeDuration:Number(e.target.value)}))}/></label>
              </SettingsPopover>
<SettingsPopover label="Zvuk titla" icon={<StudioIcon name="sound"/>}><LanguageDropdown label="Zvuk pri ulasku titla" value={editedSettings.captionSound??'none'} options={[{value:'none',label:'Bez zvuka'},{value:'whoosh',label:'Whoosh'},{value:'pop',label:'Pop'},{value:'tick',label:'Tihi klik'}]} onChange={value=>{setEditedSettings(current=>({...current,captionSound:value as CaptionSettings['captionSound']}));if(value!=='none')previewCaptionSound(value as 'whoosh'|'pop'|'tick',(editedSettings.captionSoundVolume??25)/100);}}/><CaptionRange settingKey="captionSoundVolume" resetValue={25} aria-label="Glasnoća efekta" min={0} max={100} value={editedSettings.captionSoundVolume??25} onChange={e=>setEditedSettings(current=>({...current,captionSoundVolume:Number(e.target.value)}))}/></SettingsPopover></div>;
 if(isPresetCaptionStyle(activeStyle))return <CaptionDefaults.Provider value={settingsForTemplate(templates.find(t=>t.key===activeStyle)!)}><div className="subtitle-customize-panel"><div className="subtitle-customize-head ai-settings-heading"><strong>{templates.find(t=>t.key===activeStyle)?.name}</strong><small>{scopeLabel}</small></div>{isStudioStyle(activeStyle)?<StudioStyleControls style={activeStyle} settings={baseSettings} onChange={setBaseSettings} onSelect={onVariant}/>:<AiStyleControls style={activeStyle} settings={baseSettings} onChange={setBaseSettings} onSelect={onVariant}/>}<div className="caption-style-actions">{onReset&&<button type="button" className="caption-reset-format" onClick={onReset}>Vrati originalni stil</button>}{actions}</div></div></CaptionDefaults.Provider>;
 return (
            <CaptionDefaults.Provider value={captionTypography(activeStyle,variant(settingsForTemplate(templates.find(t=>t.key===activeStyle)!)))}><div className="subtitle-customize-panel">
              {!secondaryMode&&<div className="subtitle-customize-head">
                <strong>Prilagodi stilove</strong><small>{scopeLabel}</small>
              </div>}
              {!secondaryMode&&!editingTitle&&<OrdinaryPaletteChoices style={activeStyle} settings={baseSettings} onSelect={onVariant} onChange={setBaseSettings}/>}
              {wordTools&&<div className="caption-overall-words">{wordTools}</div>}
              {!secondaryMode&&<CaptionBasicsPanel styleEffects={<><details className="caption-role-dropdown" key={activeStyle+String(hasTitles)+String(capabilities.important)+String(editingTitle)} open={editingTitle||(!capabilities.important&&!hasTitles)}><summary>{editingTitle?'Stilovi naslova':'Obični stilovi'}</summary>{styleEffects}</details>{!secondaryMode&&!editingTitle&&capabilities.important&&<details className="caption-role-dropdown"><summary>Stilovi bitnih riječi</summary><CaptionStyleControls secondary settings={captionTypography(activeStyle,{...baseSettings,fontFamily:baseSettings.secondaryFontFamily||baseSettings.fontFamily,fontScale:baseSettings.secondaryFontScale??160,textColor:baseSettings.highlightColor,...baseSettings.secondaryStyle})} patch={patch=>setBaseSettings(base=>({...base,...(patch.fontFamily?{secondaryFontFamily:patch.fontFamily}:{}),...(patch.textColor?{highlightColor:patch.textColor}:{}),...(patch.fontScale?{secondaryFontScale:patch.fontScale}:{}),secondaryStyle:{...base.secondaryStyle,...patch}}))} native={null}/></details>}{!secondaryMode&&!editingTitle&&hasTitles&&<details className="caption-role-dropdown"><summary>Stilovi naslova</summary><CaptionStyleControls secondary settings={captionTypography(activeStyle,titleSettingsForStyle(activeStyle,baseSettings))} patch={patch=>setBaseSettings(base=>({...base,titleAppearance:{...base.titleAppearance,...patch}}))} native={null}/></details>}{additionalEffects}</>} allowLayout={capabilities.layout} allowOutlines={capabilities.outlines} settings={editedSettings} onChange={setEditedSettings} role={role} onRole={setRole} openSection={openSection} allowImportant={capabilities.important} allowTitles={capabilities.titles||hasTitles}/>}
              <div className="caption-style-actions">{onReset&&<button type="button" className="caption-reset-format" title="Vrati postavke odabranog stila; sačuvaj tekst, naslove, grupe i vremena" onClick={onReset}>Vrati izgled na zadano</button>}{actions}</div>
              {secondaryMode&&styleEffects}

            </div></CaptionDefaults.Provider>);}
