import {useState,useRef} from 'react';
import type {Segment,CaptionSettings,StyleKey} from '../config/captions/presets';
import {captionTitle,replaceCaptionTitle,groupCaptions,addCaptionsToGroup,detachCaption,keywordPreset} from '../lib/caption-selection';
import {StudioIcon} from './StudioIcon/StudioIcon';
type DragWord={kind:'word'|'title'|'plain';index:number;id?:string};
export function CaptionSelectionTools({segments,selected,style,settings,onChange,onSelect,word,onWord,duration=Infinity}:{duration?:number;segments:Segment[];selected:number;style:StyleKey;settings:CaptionSettings;onChange:(v:Segment[])=>void;onSelect:(i:number)=>void;word?:number;onWord:(i:number|undefined)=>void}){
 const menu=useRef<HTMLDetailsElement>(null),dragged=useRef<DragWord|null>(null),handled=useRef(false);
 const [message,setMessage]=useState(''),[chosen,setChosen]=useState<DragWord|null>(null);const current=segments[selected];
 if(!current)return null;
 const words=current.text.trim().split(/\s+/),own=current.detachedStyle||current.laneStyle;
 const titles=segments.filter(s=>s.role==='title'&&(s.sourceCaptionId===current.id||(!s.sourceCaptionId&&s.start>=current.start&&s.start<current.end)));
 const groups=[...new Map(segments.filter(s=>s.group&&(s.lane||0)===(current.lane||0)).map(s=>[s.group!.id,s.group!])).values()];
 const remove=(item:DragWord)=>{if(item.kind==='plain')return;onChange(item.kind==='title'?segments.filter(s=>s.id!==item.id):segments.map(s=>{if(s.id!==current.id)return s;const next={...s.wordStyles};delete next[item.index];return {...s,wordStyles:next};}));setChosen(null);onWord(undefined);};
 const mark=(kind:'word'|'title',index:number)=>{if(index<0||index>=words.length)return;
  if(kind==='title'){onChange(replaceCaptionTitle(segments,current,captionTitle(current,index,own?.style||style,own?.settings||settings,1)));}
  else {const variant=keywordPreset(own?.style||style,own?.settings||settings);onChange(segments.map(s=>s.id!==current.id?s:{...s,suppressSuggestions:true,wordStyles:{...s.wordStyles,[index]:{text:words[index],...variant}}}));}setChosen(null);onWord(undefined);
 };
 const begin=(e:React.DragEvent,item:DragWord)=>{dragged.current=item;handled.current=false;e.dataTransfer.setData('text/plain',words[item.index]||'');e.dataTransfer.effectAllowed='move';};
 const end=(e:React.DragEvent)=>{const item=dragged.current;if(item&&!handled.current&&item.kind!=='plain'){const box=e.currentTarget.closest('.caption-word-bucket')?.getBoundingClientRect();if(box&&(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom))remove(item);}dragged.current=null;};
 const iconButton=(label:string,icon:React.ReactNode,action:()=>void)=><button type="button" title={label} aria-label={label} onClick={action}>{icon}</button>;
 return <div className="caption-row-actions"><details ref={menu} className="caption-selection-tools caption-options-menu"><summary onClick={()=>{document.querySelectorAll<HTMLDetailsElement>('details.caption-options-menu[open]').forEach(other=>{if(other!==menu.current)other.open=false;});onSelect(selected);onWord(undefined);setChosen(null);}} title="Opcije titla" aria-label="Opcije titla"><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><circle cx="5" cy="12" r="1.7"/><circle cx="12" cy="12" r="1.7"/><circle cx="19" cy="12" r="1.7"/></svg></summary><div className="caption-options-popup">
 <header className="caption-popup-icons">
 {current.group?iconButton('Izbaci iz grupe',<svg width="16" height="16" viewBox="0 0 24 24"><path d="M5 12h14" stroke="currentColor" strokeWidth="1.7"/></svg>,()=>onChange(segments.map(s=>s.id===current.id?{...s,group:undefined,detachedStyle:s.detachedStyle||s.laneStyle}:s))):<details className="caption-group-add-menu"><summary title="Dodaj u grupu" aria-label="Dodaj u grupu"><StudioIcon name="plus"/></summary><div className="caption-group-add-options">{groups.length?<><span>Dodaj u grupu</span>{groups.map(g=><button type="button" key={g.id} onClick={()=>onChange(addCaptionsToGroup(segments,[current.id],g.id))}>{g.name}</button>)}</>:<span>Nema grupa</span>}<button type="button" className="caption-create-group" onClick={()=>onChange(groupCaptions(segments,[current.id],'',style,settings))}>+ Dodaj grupu</button></div></details>}

 {iconButton('Kopiraj tekst',<StudioIcon name="copy"/>,()=>{void navigator.clipboard.writeText(current.text).then(()=>setMessage('Tekst kopiran')).catch(()=>setMessage('Kopiranje nije dostupno'));})}
 {iconButton('Dupliciraj titl',<StudioIcon name="newCaptions"/>,()=>{onChange([...segments,{...structuredClone(current),id:crypto.randomUUID()}]);onSelect(segments.length);})}
 {iconButton('Obriši titl',<StudioIcon name="trash"/>,()=>{onChange(segments.filter(s=>s.id!==current.id));onSelect(Math.max(0,selected-1));})}

 {iconButton('Zatvori opcije titla',<StudioIcon name="close"/>,()=>{if(menu.current)menu.current.open=false;})}
 </header>
 {current.role==='title'&&current.sourceCaptionId&&<button type="button" className="caption-clear-suggestions" onClick={()=>{const source=segments.findIndex(s=>s.id===current.sourceCaptionId);onChange(segments.filter(s=>s.id!==current.id));onSelect(Math.max(0,source));onWord(undefined);}}>Vrati naslov u izvorni titl</button>}
 <div className="caption-word-choices" aria-label="Prevuci riječ u bitne riječi ili naslove" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragged.current){handled.current=true;remove(dragged.current);}}}>{words.map((text,i)=><button type="button" draggable key={i} aria-pressed={word===i&&chosen?.kind==='plain'} onClick={()=>{setChosen({kind:'plain',index:i});onWord(i);}} onDragStart={e=>begin(e,{kind:'plain',index:i})} onDragEnd={end}>{text}</button>)}</div>
 <button type="button" className="caption-clear-suggestions" onClick={()=>onChange(segments.map(s=>s.id===current.id?{...s,suppressSuggestions:true}:s))}>Izbriši predložene naslove i riječi</button>
 <div className="caption-word-buckets">{(['title','word'] as const).map(kind=><section className="caption-word-bucket-section" key={kind}><header><span>{kind==='word'?'Bitne riječi':'Naslovi'}</span><button type="button" title={chosen?.kind===kind?'Ukloni odabranu riječ':'Dodaj odabranu riječ'} aria-label={chosen?.kind===kind?'Ukloni odabranu riječ':`Dodaj riječ u ${kind==='word'?'bitne riječi':'naslove'}`} disabled={!chosen} onClick={()=>{if(chosen?.kind===kind)remove(chosen);else if(chosen)mark(kind,chosen.index);}}>{chosen?.kind===kind?'−':'+'}</button></header><div className="caption-word-bucket" onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move';}} onDrop={e=>{e.preventDefault();if(dragged.current){handled.current=true;mark(kind,dragged.current.index);}}}>
 {(kind==='word'?Object.entries(current.wordStyles||{}).map(([i,v])=>({text:v.text,index:Number(i),id:undefined})):titles.map(s=>({text:s.text,index:s.sourceWord??words.indexOf(s.text),id:s.id}))).map((item,i)=><button type="button" key={item.id||i} draggable title="Povuci izvan okvira za uklanjanje" aria-pressed={chosen?.kind===kind&&chosen.index===item.index} onClick={()=>{setChosen({kind,index:item.index,id:item.id});if(kind==='word')onWord(item.index);else onWord(undefined);}} onDragStart={e=>begin(e,{kind,index:item.index,id:item.id})} onDragEnd={end}>{item.text}</button>)}
 </div></section>)}</div>
 <section className="caption-extra-options"><span className="caption-extra-label">Pozicija i stil</span><div className="caption-extra-actions"><button type="button" onClick={()=>onChange(segments.map(s=>s.id===current.id?detachCaption(s,style,settings):s))}>Odvoji stil ovog titla</button>{[-.1,.1].map(delta=><button type="button" key={delta} onClick={()=>{const shift=Math.max(-current.start,Math.min(delta,duration-current.end));onChange(segments.map(s=>s.id===current.id?{...s,start:s.start+shift,end:s.end+shift,words:s.words?.map(w=>({...w,start:w.start+shift,end:w.end+shift}))}:s));}}>{delta<0?'← 0.1 s':'0.1 s →'}</button>)}</div></section>{message&&<small role="status">{message}</small>}
 </div></details></div>;
}
