import {gateCleanAudio} from '../lib/audio-noise-gate';
import {useEffect,useRef,useState} from 'react';
import {apiFetch} from '../lib/api';
import {prepareTranscriptionAudio} from '../lib/prepare-transcription-audio';
import {AudioPlayer} from './AudioPlayer';
export function CleanAudioPanel({file,disabled,onApply,openRequest=0}:{file:File|null;disabled?:boolean;openRequest?:number;onApply:(file:File,offset:number)=>Promise<void>}){
 const [threshold,setThreshold]=useState(-60);
 const details=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{if(openRequest&&details.current){details.current.open=true;details.current.scrollIntoView({block:'nearest'});}},[openRequest]);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<{file:File;url:string;offset:number}|null>(null);
 const abort=useRef<AbortController|null>(null);
 const [original,setOriginal]=useState('');
 useEffect(()=>{abort.current?.abort();setBusy(false);setResult(null);setMessage('');if(!file)return;const url=URL.createObjectURL(file);setOriginal(url);return()=>{abort.current?.abort();URL.revokeObjectURL(url);};},[file]);
 useEffect(()=>()=>{if(result)URL.revokeObjectURL(result.url);},[result]);
 async function clean(){if(!file||busy)return;const controller=new AbortController();abort.current=controller;setBusy(true);setMessage('Priprema zvuka…');
 try{const prepared=await prepareTranscriptionAudio(file,controller.signal,percent=>setMessage(percent===undefined?'Priprema zvuka…':`Priprema zvuka ${Math.round(percent)}%…`));controller.signal.throwIfAborted();if(prepared.blob.size>25*1024*1024)throw new Error('Za čišćenje odaberi zvučni zapis do 25 MB. Limit učitavanja videa je odvojen.');
 const body=new FormData();body.append('audio',prepared.blob,prepared.name);setMessage('Uklanjanje pozadinskog šuma…');const response=await apiFetch('/api/audio/clean',{method:'POST',body,signal:controller.signal});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||'Čišćenje nije uspjelo.');}const blob=await gateCleanAudio(await response.blob(),threshold);controller.signal.throwIfAborted();const audio=new File([blob],blob.type==='audio/wav'?'ocisceni-govor.wav':'ocisceni-govor.mp3',{type:blob.type||'audio/mpeg'});setResult({file:audio,url:URL.createObjectURL(audio),offset:prepared.offset});setMessage('Preslušaj rezultat prije primjene.');
 }catch(error){if(!controller.signal.aborted)setMessage(error instanceof Error?error.message:'Čišćenje nije uspjelo.');}finally{if(abort.current===controller){setBusy(false);abort.current=null;}}}
 return <details ref={details} className="clean-audio-panel" aria-busy={busy}><summary>✨ Clean Audio</summary><p>Ukloni pozadinsku buku i šum te izdvoji govor. Preslušaj rezultat prije primjene.</p><label className="subtitle-size-control"><span>Prag tihog šuma <b>{threshold<=-60?'Isključen':`${threshold} dB`}</b></span><input type="range" min="-60" max="-15" step="1" value={threshold} disabled={busy} onChange={event=>{setThreshold(Number(event.target.value));setResult(null);}}/></label><small>Viši prag jače stišava tihe dijelove nakon čišćenja. Može stišati i tih govor.</small><button className="clean-audio-apply" type="button" disabled={!file||disabled||busy} onClick={()=>void clean()}>{busy?'Obrada…':'Ukloni pozadinsku buku'}</button>{busy&&<div className="clean-audio-progress" role="status"><span className="workspace-loading-spinner" aria-hidden="true"/><span>{message||'Obrada zvuka…'}</span><progress aria-label="Obrada zvuka"/></div>}{busy&&<button type="button" onClick={()=>{abort.current?.abort();setMessage('Obrada je otkazana.');}}>Otkaži</button>}{message&&<p role="status">{message}</p>}{result&&<><small>Original</small><AudioPlayer src={original}/><small>Očišćeni govor</small><AudioPlayer src={result.url}/><button type="button" disabled={disabled||busy} onClick={async()=>{setBusy(true);try{await onApply(result.file,result.offset);setMessage('Očišćeni govor je primijenjen.');}catch(error){setMessage(error instanceof Error?error.message:'Primjena nije uspjela.');}finally{setBusy(false);}}}>Primijeni očišćeni govor</button></>}</details>;
}
