import './LivePresence.scss';
import {useEffect,useState} from 'react';
import {apiJson} from '../lib/api';
type Count={name:string;count:number};
type Snapshot={at:string;total:number;active:number;editorActive:number;editorOpen:number;pages:Count[];sources:Count[];campaigns:Count[];affiliateCounts?:Count[];sections:{page:string;section:string;count:number}[];rows?:{user:string;page:string;section:string;source:string;active:boolean;seenAt:string;affiliate:string;campaign:string;isTest:boolean}[]};
const labels:Record<string,string>={home:'Početna',captions:'Titlovi',video:'Video editor',plans:'Paketi',checkout:'Kupovina',account:'Prijava',other:'Ostalo',styles:'Stilovi',settings:'Postavke',voice:'Glas',media:'Mediji',audio:'Zvuk',text:'Tekst',effects:'Efekti',export:'Izvoz',elements:'Elementi',filters:'Filteri',transitions:'Prijelazi',direct:'Direktno / nepoznato',google:'Google',bing:'Bing',instagram:'Instagram',facebook:'Facebook',tiktok:'TikTok',youtube:'YouTube',linkedin:'LinkedIn'};
const label=(key:string)=>labels[key]||key||'Bez oznake';
export function LivePresence({affiliate=false,affiliateUser}:{affiliate?:boolean;affiliateUser?:string}){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[includeTest,setIncludeTest]=useState(false);
 useEffect(()=>{let live=true,busy=false;
 const load=async()=>{if(busy||document.visibilityState!=='visible')return;busy=true;try{const params=new URLSearchParams({includeTest:includeTest?'1':'0',...(affiliateUser?{affiliateUser}:{})});const next=await apiJson<Snapshot>((affiliate?'/api/affiliate/presence':'/api/admin/analytics/presence')+'?'+params);if(live){setData(next);setError('');}}catch(e){if(live)setError(e instanceof Error?e.message:'Pregled nije dostupan.');}finally{busy=false;}};
 setData(null);void load();const timer=setInterval(()=>void load(),15000);const visible=()=>void load();document.addEventListener('visibilitychange',visible);
 return()=>{live=false;clearInterval(timer);document.removeEventListener('visibilitychange',visible);};
 },[affiliate,affiliateUser,includeTest,refresh]);
 const bars=(title:string,rows:Count[])=>{const max=Math.max(1,...rows.map(x=>x.count));return <section className="presence-breakdown"><h3>{title}</h3>{rows.length?rows.map(row=><div key={row.name} style={{display:'grid',gridTemplateColumns:'minmax(110px,1fr) 2fr 40px',gap:12,alignItems:'center',marginBlock:8,fontSize:12}}><span>{label(row.name)}</span><span style={{display:'block',height:7,background:'#8792a320',borderRadius:8}}><span style={{display:'block',height:'100%',width:`${row.count/max*100}%`,background:'#2ed3d3',borderRadius:8}}/></span><strong>{row.count}</strong></div>):<p>Trenutno nema podataka.</p>}</section>;};
 return <section className="affiliate-card live-presence"><h2>{affiliate||affiliateUser?'Trenutno preko affiliate linka':'Trenutno na Editi'}</h2><p>Preglednici s dozvoljenom analitikom i vidljivim tabom. Osvježavanje svakih 15 sekundi; sesija nestaje nakon 90 sekundi bez javljanja. Više tabova iste sesije broji se jednom. Ovo nije tačan broj ljudi.</p><div className="billing-toolbar"><button onClick={()=>setRefresh(v=>v+1)}>Osvježi sada</button>{!affiliate&&<label><input type="checkbox" checked={includeTest} onChange={e=>setIncludeTest(e.target.checked)}/>Uključi lokalni testni račun</label>}</div>{error&&<p role="alert">Podaci možda nisu svježi: {error}</p>}{!data&&!error&&<p>Učitavanje…</p>}{data&&<><p>Zadnja potvrda: {new Date(data.at).toLocaleTimeString('bs-BA')}</p><div className="billing-stats"><div><small>Vidljive sesije</small><strong>{data.total}</strong></div><div><small>Aktivnost u zadnjoj minuti*</small><strong>{data.active}</strong></div><div><small>Otvoren editor</small><strong>{data.editorOpen}</strong></div><div><small>Nedavno aktivni u editoru*</small><strong>{data.editorActive}</strong></div></div><p>*Klik, tipkanje ili skrolanje u zadnjoj prijavi preglednika, ne dokaz izmjene videa ili čitanja. Administratorske sesije su isključene. Bez aktivnosti može značiti da korisnik čita ili gleda video.</p><div className="presence-grid">{bars('Stranice',data.pages)}{bars('Izvor dolaska · prijava preglednika',data.sources)}{bars('Affiliate kampanje',data.campaigns)}{!affiliate&&data.affiliateCounts&&bars('Affiliatori',data.affiliateCounts)}</div><details><summary>Dijelovi aplikacije</summary><div className="billing-table-wrap"><table className="billing-table"><thead><tr><th>Stranica</th><th>Dio</th><th>Sesije</th></tr></thead><tbody>{data.sections.map(row=><tr key={row.page+row.section}><td>{label(row.page)}</td><td>{label(row.section)}</td><td>{row.count}</td></tr>)}</tbody></table></div></details>{data.rows&&<details><summary>Aktivne sesije · najviše 100 · samo administratori</summary><div className="billing-table-wrap"><table className="billing-table"><thead><tr><th>Korisnik</th><th>Gdje</th><th>Aktivnost</th><th>Izvor</th><th>Affiliate / kampanja</th><th>Zadnje javljanje</th></tr></thead><tbody>{data.rows.map((row,i)=><tr key={i}><td>{row.user}{row.isTest?' · Test':''}</td><td>{label(row.page)} · {label(row.section)}</td><td>{row.active?'Nedavna interakcija':'Bez nedavne interakcije'}</td><td>{label(row.source)}</td><td>{row.affiliate||'—'} · {row.campaign||'—'}</td><td>{new Date(row.seenAt).toLocaleTimeString('bs-BA')}</td></tr>)}</tbody></table></div></details>}<p>Izvor je gruba kategorija prvog dolaska u sesiji; preglednik ga može sakriti. Affiliate pripadnost dolazi sa servera prema postojećim pravilima preporuke. Ne prikupljamo pritisnute tipke, sadržaj videa, titlove ni pune adrese stranica.</p></>}</section>;
}
