import {useRef,useState} from 'react';
import {CaptionSample} from './CaptionSample/CaptionSample';
import {StyleDropdown} from './LanguageDropdown/LanguageDropdown';
import {ActionIcon} from './CreativeControls';
import {templates,settingsForTemplate,type Segment,type CaptionTemplate} from '../config/captions/presets';
import type {VideoCaptions} from '../lib/video-captions';

const simpleStyles:CaptionTemplate[]=['clean','minimal','box','captionCard','cinema','elegant','typewriter','focus','karaoke','social'].flatMap(key=>{
 const template=templates.find(t=>t.key===key);return template?[{...template,preset:{...template.preset,outerOutlineWidth:0,wordMode:'all' as const,reveal:'none' as const,animation:'none' as const,behindPerson:false}}]:[];
});
export function LocalCaptionPanel({document:doc,onChange,onSeek,onImport}:{document:VideoCaptions;onChange:(doc:VideoCaptions)=>void;onSeek:(time:number)=>void;onImport:()=>void}){
 const [tab,setTab]=useState<'captions'|'styles'>('captions'),[hover,setHover]=useState('');
 const cursor=useRef<Record<string,number>>({});
 const settings=doc.captionSettings;
 const patch=(value:Partial<typeof settings>)=>onChange({...doc,captionSettings:{...settings,...value},segments:doc.segments.map(s=>({...s,laneStyle:s.laneStyle?{...s.laneStyle,settings:{...s.laneStyle.settings,...value}}:undefined,detachedStyle:s.detachedStyle?{...s.detachedStyle,settings:{...s.detachedStyle.settings,...value}}:undefined,position:s.position?{...s.position,...(value.x!==undefined?{x:value.x}:{}),...(value.y!==undefined?{y:value.y}:{}),...(value.fontScale!==undefined?{fontScale:value.fontScale}:{})}:undefined}))});
 const update=(id:string,value:Partial<Segment>)=>onChange({...doc,segments:doc.segments.map(s=>s.id===id?{...s,...value,words:undefined}:s)});
 const insert=(index:number)=>{const start=index<0?0:doc.segments[index].end;const next=doc.segments[index+1];const end=next&&next.start>start?Math.min(start+3,next.start):start+3;const delta=next?Math.max(0,end-next.start):0;const later=doc.segments.slice(index+1).map(s=>({...s,start:s.start+delta,end:s.end+delta,words:s.words?.map(w=>({...w,start:w.start+delta,end:w.end+delta}))}));onChange({...doc,segments:[...doc.segments.slice(0,index+1),{id:crypto.randomUUID(),start,end,text:'Novi titl'},...later]});};
 const split=(s:Segment)=>{const cut=cursor.current[s.id]??Math.floor(s.text.length/2);if(cut<=0||cut>=s.text.length||s.end-s.start<.2)return;const time=s.start+(s.end-s.start)*cut/s.text.length;onChange({...doc,segments:doc.segments.flatMap(v=>v.id!==s.id?[v]:[{...v,text:v.text.slice(0,cut).trim(),end:time,words:undefined},{...v,id:crypto.randomUUID(),text:v.text.slice(cut).trim(),start:time,words:undefined}])});};
 const duplicate=(s:Segment,index:number)=>{const duration=s.end-s.start;onChange({...doc,segments:[...doc.segments.slice(0,index+1),{...s,id:crypto.randomUUID(),start:s.end,end:s.end+duration,words:undefined},...doc.segments.slice(index+1).map(v=>({...v,start:v.start+duration,end:v.end+duration,words:v.words?.map(w=>({...w,start:w.start+duration,end:w.end+duration}))}))]});};
 const selectStyle=(template:CaptionTemplate)=>onChange({...doc,activeStyle:template.key,captionSettings:{...settingsForTemplate(template,settings),outerOutlineWidth:0,wordMode:'all',reveal:'none',animation:'none',behindPerson:false,fontScale:settings.fontScale},segments:doc.segments.map(s=>({...s,separateStyle:undefined,inheritedStyle:undefined,laneStyle:undefined,detachedStyle:undefined,wordStyles:undefined}))});
 return <div className="local-caption-panel">
  <div className="local-caption-tabs" role="tablist" aria-label="Titlovi i stilovi"><button role="tab" aria-selected={tab==='captions'} onClick={()=>setTab('captions')}>Titlovi <small>{doc.segments.length}</small></button><button role="tab" aria-selected={tab==='styles'} onClick={()=>setTab('styles')}>Stilovi</button></div>
  {tab==='styles'?<div role="tabpanel" aria-label="Stilovi"><div className="local-caption-styles">{simpleStyles.map(t=><button key={t.key} className="local-caption-style" aria-pressed={doc.activeStyle===t.key} onMouseEnter={()=>setHover(t.key)} onMouseLeave={()=>setHover('')} onFocus={()=>setHover(t.key)} onBlur={()=>setHover('')} onClick={()=>selectStyle(t)}><div className="local-style-sample"><CaptionSample template={t} playing={hover===t.key}/></div><span>{t.name}<b>{doc.activeStyle===t.key?'✓':''}</b></span></button>)}</div>
   <div className="local-caption-colors"><label>Prva boja<input type="color" value={settings.textColor} onChange={e=>patch({textColor:e.target.value})}/></label><label>Druga boja<input type="color" value={settings.highlightColor} onChange={e=>patch({highlightColor:e.target.value})}/></label></div><label className="local-caption-background"><input type="checkbox" checked={settings.backgroundOpacity>0} onChange={e=>patch({backgroundOpacity:e.target.checked?60:0})}/>Pozadina teksta</label>{settings.backgroundOpacity>0&&<><label>Boja pozadine<input type="color" value={settings.backgroundColor} onChange={e=>patch({backgroundColor:e.target.value})}/></label><label>Prozirnost pozadine · {100-settings.backgroundOpacity}%<input type="range" min="0" max="100" value={100-settings.backgroundOpacity} onChange={e=>patch({backgroundOpacity:100-Number(e.target.value)})}/></label></>}<label>Položaj po visini<input type="range" min="0" max="100" value={settings.y} onChange={e=>patch({y:Number(e.target.value)})}/></label><div className="caption-position-buttons">{[25,50,75].map(y=><button key={y} onClick={()=>patch({y})}>{y===25?'¼':y===50?'½':'¾'}</button>)}</div><p className="local-caption-hint">Tekst možeš povući direktno u playeru; vodiči označavaju ¼, ½ i ¾ visine.</p>
   <StyleDropdown label="Animacija" value={settings.wordMode==='single'?'word':settings.reveal||'none'} onChange={e=>patch({wordMode:e.target.value==='word'?'single':'all',reveal:e.target.value==='word'?'none':e.target.value as 'none'|'letters'|'fade',fadeFrom:0,revealDuration:.25})}><option value="none">Bez animacije</option><option value="word">Riječ po riječ</option><option value="letters">Slovo po slovo</option><option value="fade">Fade in</option></StyleDropdown><label>Veličina · {settings.fontScale}%<input type="range" min="40" max="180" value={settings.fontScale} onChange={e=>patch({fontScale:Number(e.target.value)})}/></label>
  </div>:<div role="tabpanel" aria-label="Titlovi"><div className="local-caption-toolbar"><button title="Dodaj titl na početak" onClick={()=>insert(-1)}><ActionIcon name="plus"/>Dodaj titl</button><button onClick={onImport}>Iz skripte</button></div><p className="local-caption-hint">„Iz skripte” zamjenjuje titlove intervalima skripte.</p>
   {doc.segments.map((s,index)=><div className="local-caption-item" key={s.id}><div className="local-caption-timing"><button className="local-caption-index" title="Idi na titl" onClick={()=>onSeek(s.start)}>{String(index+1).padStart(2,'0')}</button><label>Od<input aria-label={`Početak titla ${index+1}`} type="number" min="0" max={s.end-.1} step=".1" value={s.start} onChange={e=>update(s.id,{start:Math.max(0,Math.min(s.end-.1,Number(e.target.value)))})}/></label><label>Do<input aria-label={`Kraj titla ${index+1}`} type="number" min={s.start+.1} step=".1" value={s.end} onChange={e=>update(s.id,{end:Math.max(s.start+.1,Number(e.target.value))})}/></label></div>
    <textarea aria-label={`Tekst titla ${index+1}`} rows={2} value={s.text} onSelect={e=>{cursor.current[s.id]=e.currentTarget.selectionStart;}} onChange={e=>update(s.id,{text:e.target.value})}/>
    <div className="local-caption-actions"><button title="Odvoji na kursoru" aria-label="Odvoji na kursoru" disabled={s.text.length<2||s.end-s.start<.2} onClick={()=>split(s)}><ActionIcon name="split"/></button><button title="Dupliciraj" aria-label="Dupliciraj" onClick={()=>duplicate(s,index)}><ActionIcon name="copy"/></button><button title="Spoji sa sljedećim" aria-label="Spoji sa sljedećim" disabled={!doc.segments[index+1]} onClick={()=>{const next=doc.segments[index+1];if(next)onChange({...doc,segments:doc.segments.flatMap(v=>v.id===next.id?[]:v.id===s.id?[{...s,text:`${s.text} ${next.text}`,end:Math.max(s.end,next.end),words:undefined}]:[v])});}}><ActionIcon name="merge"/></button><button title="Dodaj titl ispod" aria-label="Dodaj titl ispod" onClick={()=>insert(index)}><ActionIcon name="plus"/></button><button title="Obriši titl" aria-label="Obriši titl" onClick={()=>onChange({...doc,segments:doc.segments.filter(v=>v.id!==s.id)})}><ActionIcon name="trash"/></button></div>
   </div>)}{!doc.segments.length&&<p>Dodaj titl ili preuzmi intervale iz skripte.</p>}
  </div>}
 </div>;
}
