import {useState} from 'react';
import {Link} from 'react-router-dom';
import {apiFetch,apiJson} from '../lib/api';
import {jsonBody,type Script} from '../lib/production';
import {useAssets} from './ProductionWorkspace';
import {rememberRemoteFile} from './LocalVideoStorage';
import {DEFAULT_CAPTION_SETTINGS} from '../config/captions/presets';
import type {VideoCaptions} from '../lib/video-captions';
import type {StillMotion} from '../lib/still-scenes';
type LocalClip=StillMotion&{id:string;start:number;inPoint:number;outPoint:number;type:"video"|"audio";volume:number;muted:boolean;scale?:number};
export function scriptCaptions(script:Script):VideoCaptions{return {segments:script.segments.map(s=>({...s,words:s.text.trim().split(/\s+/).filter(Boolean).map((text,i,words)=>({text,start:s.start+(s.end-s.start)*i/words.length,end:s.start+(s.end-s.start)*(i+1)/words.length}))})),activeStyle:'clean',captionSettings:{...DEFAULT_CAPTION_SETTINGS,fontFamily:'"Manrope Variable", Arial, sans-serif',textColor:'#ffffff',highlightColor:'#ffffff',y:82,outlineWidth:1.5,outerOutlineWidth:0,backgroundOpacity:50,wordMode:'all',reveal:'fade',fadeFrom:0,revealDuration:.25}};}
export function LocalEditorTools({panel,script,selected,isImage,document,onCaptions,onPatch,onRemove,onAdd,onSeek,disabled}:{panel:string;script:Script;selected?:LocalClip;isImage:boolean;document:VideoCaptions;onCaptions:(doc:VideoCaptions)=>void;onPatch:(patch:Partial<LocalClip>)=>void;onRemove:()=>void;onAdd:(files:File[],start?:number)=>Promise<boolean>;onSeek:(time:number)=>void;disabled:boolean}){
 const {assets,error}=useAssets(script.project,script.updated_at);const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[voices,setVoices]=useState<{id:string;name:string}[]>([]),[voice,setVoice]=useState(''),[text,setText]=useState(script.content),[start,setStart]=useState(0),[segment,setSegment]=useState('');
 const library=assets.filter(a=>a.metadata.scriptId===script.id&&(panel==='audio'?a.contentType.startsWith('audio/'):a.contentType.startsWith('image/')||a.contentType.startsWith('video/')));
 const settings=document.captionSettings;const captionsPatch=(patch:Partial<VideoCaptions['captionSettings']>)=>onCaptions({...document,captionSettings:{...settings,...patch}});
 return <fieldset className="local-editor-tools" disabled={disabled||busy}>
 {(panel==='media'||panel==='audio')&&<><label className="local-import-control">+ {panel==='audio'?'Uvezi audio':'Uvezi slike ili video'}<input type="file" multiple accept={panel==='audio'?'audio/*':'image/png,image/jpeg,image/webp,video/*'} onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setBusy(true);await onAdd(files,panel==='audio'?start:undefined);setBusy(false);}}/></label><div className="local-media-library">{library.map(a=><button key={a.id} onClick={async()=>{setBusy(true);try{const r=await apiFetch(a.url);if(!r.ok)throw new Error('Datoteka nije dostupna.');const file=new File([await r.blob()],a.name,{type:a.contentType});rememberRemoteFile(file,a.id);await onAdd([file],panel==='audio'?start:undefined);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>{a.contentType.startsWith('image/')?<img src={a.url} alt=""/>:<span>{panel==='audio'?'♫':'▶'}</span>}<strong>{a.name}</strong><small>+ Dodaj na timeline</small></button>)}</div>{!library.length&&<p>Ovdje će biti datoteke ove skripte. Možeš ih uvesti s računara.</p>}</>}
 {panel==='scripts'&&<><h3>{script.title}</h3><button onClick={()=>onCaptions(scriptCaptions(script))}>Preuzmi intervale u titlove</button><p>Ovo zamjenjuje titlove na timelineu intervalima iz skripte.</p>{script.segments.map(s=><button className="local-script-interval" key={s.id} onClick={()=>onSeek(s.start)}><small>{s.start}s – {s.end}s</small><span>{s.text}</span></button>)}<Link to={`/skripte?project=${script.project}&script=${script.id}`}>Uredi skriptu →</Link></>}
 {panel==='audio'&&<><h3>Naracija</h3><label>Tekst iz intervala<select value={segment} onChange={e=>{setSegment(e.target.value);const s=script.segments.find(s=>s.id===e.target.value);setText(s?.text||script.content);setStart(s?.start||0);}}><option value="">Cijela skripta</option>{script.segments.map(s=><option key={s.id} value={s.id}>{s.start}s – {s.end}s</option>)}</select></label><label>Tekst<textarea rows={5} value={text} maxLength={10000} onChange={e=>setText(e.target.value)}/></label><label>Početak na timelineu (s)<input type="number" min="0" step=".1" value={start} onChange={e=>setStart(Math.max(0,Number(e.target.value)))}/></label><label>Glas<select value={voice} onChange={e=>setVoice(e.target.value)}><option value="">Odaberi glas</option>{voices.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><button onClick={async()=>{setBusy(true);try{const r=await apiJson<{voices:{id:string;name:string}[]}>('/api/voices');setVoices(r.voices);setVoice(r.voices[0]?.id||'');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Učitaj ElevenLabs glasove</button><button disabled={!voice||!text.trim()} onClick={async()=>{setBusy(true);try{const r=await apiFetch('/api/narration',jsonBody({voiceId:voice,text}));if(!r.ok){const error=await r.json();throw new Error(error.error||'Naracija nije generisana.');}await onAdd([new File([await r.blob()],`naracija-${Date.now()}.mp3`,{type:'audio/mpeg'})],start);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Generiši naraciju</button><p>Generisanje troši ElevenLabs kredite. Interval skripte prilagodi stvarnom trajanju glasa.</p>{selected?.type==='audio'&&<><label>Početak odabranog zvuka<input type="number" min="0" step=".1" value={selected.start} onChange={e=>onPatch({start:Math.max(0,Number(e.target.value))})}/></label><label>Glasnoća · {selected.volume}%<input type="range" min="0" max="150" value={selected.volume} onChange={e=>onPatch({volume:Number(e.target.value)})}/></label><button onClick={()=>onPatch({muted:!selected.muted})}>{selected.muted?'Uključi zvuk':'Isključi zvuk'}</button><button onClick={onRemove}>Ukloni zvuk</button></>}</>}
 {panel==='captions'&&<><label>Stil<select value={document.activeStyle==='minimal'?'clean':'standard'} onChange={e=>onCaptions({...document,activeStyle:e.target.value==='clean'?'minimal':'clean',captionSettings:{...settings,outlineWidth:e.target.value==='clean'?0:1.5,backgroundOpacity:e.target.value==='clean'?0:50}})}><option value="standard">Standard</option><option value="clean">Clean</option></select></label><label>Animacija<select value={settings.wordMode==='single'?'word':settings.reveal||'none'} onChange={e=>captionsPatch({wordMode:e.target.value==='word'?'single':'all',reveal:e.target.value==='word'?'none':e.target.value as 'none'|'letters'|'fade',fadeFrom:0,revealDuration:.25})}><option value="none">Bez animacije</option><option value="word">Riječ po riječ</option><option value="letters">Slovo po slovo</option><option value="fade">Fade in</option></select></label><label>Veličina · {settings.fontScale}%<input type="range" min="40" max="180" value={settings.fontScale} onChange={e=>captionsPatch({fontScale:Number(e.target.value)})}/></label><button onClick={()=>onCaptions({...document,segments:[...document.segments,{id:crypto.randomUUID(),start:document.segments.at(-1)?.end||0,end:(document.segments.at(-1)?.end||0)+3,text:'Novi titl'}]})}>+ Dodaj titl</button>{document.segments.map(s=><div className="local-caption-row" key={s.id}><div><label>Od<input type="number" min="0" step=".1" value={s.start} onChange={e=>onCaptions({...document,segments:document.segments.map(v=>v.id===s.id?{...v,start:Math.min(v.end-.1,Math.max(0,Number(e.target.value))),words:undefined}:v)})}/></label><label>Do<input type="number" step=".1" value={s.end} onChange={e=>onCaptions({...document,segments:document.segments.map(v=>v.id===s.id?{...v,end:Math.max(v.start+.1,Number(e.target.value)),words:undefined}:v)})}/></label></div><textarea aria-label="Tekst titla" rows={2} value={s.text} onChange={e=>onCaptions({...document,segments:document.segments.map(v=>v.id===s.id?{...v,text:e.target.value,words:undefined}:v)})}/><button onClick={()=>onCaptions({...document,segments:document.segments.filter(v=>v.id!==s.id)})}>Ukloni titl</button></div>)}</>}
 {(panel==='settings'||panel==='transitions')&&(selected?.type==='video'?<><h3>Odabrani kadar</h3><label>Početak (s)<input type="number" min="0" step=".1" value={selected.start} onChange={e=>onPatch({start:Math.max(0,Number(e.target.value))})}/></label>{isImage&&<><label>Trajanje slike (s)<input type="number" min=".5" max="600" step=".1" value={selected.outPoint-selected.inPoint} onChange={e=>onPatch({outPoint:selected.inPoint+Math.max(.5,Math.min(600,Number(e.target.value)))})}/></label><label>Pokret<select value={selected.motion||'none'} onChange={e=>onPatch({motion:e.target.value as StillMotion['motion']})}><option value="none">Mirna slika</option><option value="zoom-in">Zoom in</option><option value="zoom-out">Zoom out</option><option value="pan">Pomak</option><option value="shake">Blagi shake</option></select></label><label>Prijelaz<select value={selected.imageTransition||'cut'} onChange={e=>onPatch({imageTransition:e.target.value as StillMotion['imageTransition']})}><option value="cut">Rez</option><option value="crossfade">Pretapanje</option><option value="fade">Fade iz crne</option><option value="slide">Klizanje</option></select></label><label>Trajanje prijelaza (s)<input type="number" min=".1" max="3" step=".1" value={selected.imageTransitionDuration||.5} onChange={e=>onPatch({imageTransitionDuration:Math.max(.1,Math.min(3,Number(e.target.value)))})}/></label></>}<label>Veličina · {Math.round((selected.scale||1)*100)}%<input type="range" min=".2" max="3" step=".05" value={selected.scale||1} onChange={e=>onPatch({scale:Number(e.target.value)})}/></label><button onClick={onRemove}>Ukloni kadar</button></>:<p>Odaberi kadar na timelineu.</p>)}
 {(busy||message||error)&&<p role="status">{busy?'Radim…':message||error}</p>}</fieldset>;
}
