import {LocalCaptionPanel} from './LocalCaptionPanel';
import {StyleDropdown} from './LanguageDropdown/LanguageDropdown';
import {useEffect,useState} from 'react';
import {apiFetch,apiJson} from '../lib/api';
import {type Script} from '../lib/production';
import {useAssets} from './ProductionWorkspace';
import {rememberRemoteFile} from './LocalVideoStorage';
import {DEFAULT_CAPTION_SETTINGS} from '../config/captions/presets';
import type {VideoCaptions} from '../lib/video-captions';
import type {StillMotion} from '../lib/still-scenes';
type LocalClip=StillMotion&{id:string;start:number;inPoint:number;outPoint:number;type:'video'|'audio';audioRole?:'narration'|'sound';volume:number;muted:boolean;scale?:number};
type Voice={id:string;name:string;previewUrl?:string;available?:boolean;reason?:string;gender?:string;language?:string};
export function scriptCaptions(script:Script):VideoCaptions{return {segments:script.segments.map(s=>({...s,words:s.text.trim().split(/\s+/).filter(Boolean).map((text,i,words)=>({text,start:s.start+(s.end-s.start)*i/words.length,end:s.start+(s.end-s.start)*(i+1)/words.length}))})),activeStyle:'clean',captionSettings:{...DEFAULT_CAPTION_SETTINGS,fontFamily:'"Manrope Variable", Arial, sans-serif',textColor:'#ffffff',highlightColor:'#ffffff',y:82,outlineWidth:1.5,outerOutlineWidth:0,backgroundOpacity:50,wordMode:'all',reveal:'fade',fadeFrom:0,revealDuration:.25}};}
export function LocalEditorTools({panel,script,selected,isImage,document,onCaptions,onPatch,onRemove,onAdd,onSeek,disabled,timelineDuration,timelineMinimum,onTimelineDuration,defaults,onDefaults}:{timelineDuration:number;timelineMinimum:number;onTimelineDuration:(value:number)=>void;defaults:StillMotion;onDefaults:(value:StillMotion)=>void;panel:string;script:Script;selected?:LocalClip;isImage:boolean;document:VideoCaptions;onCaptions:(doc:VideoCaptions)=>void;onPatch:(patch:Partial<LocalClip>)=>void;onRemove:()=>void;onAdd:(files:File[],start?:number,role?:'narration'|'sound')=>Promise<boolean>;onSeek:(time:number)=>void;disabled:boolean}){
 const {assets,error}=useAssets(script.project,script.updated_at);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[voices,setVoices]=useState<Voice[]>([]),[voice,setVoice]=useState(''),[text,setText]=useState(script.content),[start,setStart]=useState(0),[segment,setSegment]=useState(''),[durationDraft,setDurationDraft]=useState(String(timelineDuration));
 useEffect(()=>setDurationDraft(String(Math.round(timelineDuration*10)/10)),[timelineDuration]);
 const isSound=panel==='sounds',audio=panel==='audio'||isSound,role=isSound?'sound':'narration';
 const library=assets.filter(a=>a.metadata.scriptId===script.id&&(audio?a.contentType.startsWith('audio/')&&(isSound?a.metadata.audioRole==='sound':a.metadata.audioRole!=='sound'):a.metadata.gallery!==false&&(a.contentType.startsWith('image/')||a.contentType.startsWith('video/'))));
 const chosenVoice=voices.find(v=>v.id===voice),motion=selected?.type==='video'&&isImage?selected:defaults;
 const patchMotion=(value:StillMotion)=>{if(selected?.type==='video'&&isImage)onPatch(value);else onDefaults({...defaults,...value});};
 async function loadVoices(){setBusy(true);setMessage('');try{const owned=await apiJson<{voices:Voice[]}>('/api/voices');let regional:Voice[]=[];try{regional=(await apiJson<{voices:Voice[]}>('/api/voices/regional')).voices;}catch{setMessage('Regionalni primjeri nisu učitani; dostupni su glasovi računa.');}const combined=[...regional,...owned.voices.filter(v=>!regional.some(r=>r.id===v.id))];setVoices(combined);setVoice(combined.find(v=>v.available!==false)?.id||'');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function commitDuration(){const value=Number(durationDraft);if(!durationDraft.trim()||!Number.isFinite(value)||value<=0||value>21600){setMessage('Unesi trajanje veće od 0, do 21.600 sekundi.');return;}onTimelineDuration(value);setMessage('Trajanje timelinea postavljeno.');}
 return <fieldset className="local-editor-tools" disabled={disabled||busy}>
 {panel==='start'&&<><h3>Dužina timelinea</h3><label>Trajanje u sekundama<input type="number" step=".1" min=".1" max="21600" value={durationDraft} onChange={e=>setDurationDraft(e.target.value)} onBlur={commitDuration} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();commitDuration();}}}/></label><small>Trenutni sadržaj traje {timelineMinimum.toFixed(1)} s. Kraće trajanje skraćuje pregled i izvoz; elementi ostaju sačuvani.</small><p>Nove slike ili zvukovi automatski produžavaju timeline kada pređu zadano trajanje.</p></>}
 {(panel==='media'||audio)&&<><label className="local-import-control">+ {audio?(isSound?'Uvezi dodatni zvuk':'Uvezi naraciju'):'Uvezi slike ili video'}<input type="file" multiple accept={audio?'audio/*':'image/png,image/jpeg,image/webp,video/*'} onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setBusy(true);try{await onAdd(files,audio?start:undefined,audio?role:undefined);}finally{setBusy(false);}}}/></label><div className="local-media-library">{library.map(a=><button key={a.id} onClick={async()=>{setBusy(true);try{const r=await apiFetch(a.url);if(!r.ok)throw new Error('Datoteka nije dostupna.');const file=new File([await r.blob()],a.name,{type:a.contentType});rememberRemoteFile(file,a.id);await onAdd([file],audio?start:undefined,audio?role:undefined);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>{a.contentType.startsWith('image/')?<img src={a.url} alt=""/>:<span>{audio?'♫':'▶'}</span>}<strong>{a.name}</strong><small>+ Dodaj na timeline</small></button>)}</div>{!library.length&&<p>Uvezi datoteke s računara ili dodaj fotografije u galeriju skripte.</p>}</>}
 {audio&&<label>Početak na timelineu (s)<input type="number" min="0" step=".1" value={start} onChange={e=>setStart(Math.max(0,Number(e.target.value)))}/></label>}
 {panel==='audio'&&<><section className="local-narration-text"><h3>Naracija</h3><StyleDropdown label="Tekst iz intervala" value={segment} onChange={e=>{setSegment(e.target.value);const s=script.segments.find(s=>s.id===e.target.value);setText(s?.text||script.content);setStart(s?.start||0);}}><option value="">Cijela skripta</option>{script.segments.map(s=><option key={s.id} value={s.id}>{s.start}s – {s.end}s</option>)}</StyleDropdown><label>Tekst<textarea rows={5} value={text} maxLength={10000} onChange={e=>setText(e.target.value)}/></label></section>
 <section className="local-voice-selection"><h3>Glas i primjeri</h3><button onClick={()=>void loadVoices()}>Učitaj ElevenLabs glasove</button><StyleDropdown label="Glas" value={voice} onChange={e=>setVoice(e.target.value)}><option value="">Odaberi glas</option>{voices.map(v=><option key={v.id} value={v.id}>{v.name}{v.available===false?' · primjer':''}</option>)}</StyleDropdown>{chosenVoice?.previewUrl&&<audio controls preload="none" src={chosenVoice.previewUrl} aria-label={`Primjer: ${chosenVoice.name}`}/>}<div className="regional-voice-examples">{voices.filter(v=>v.available!==undefined).map(v=><article key={v.id}><strong>{v.name}</strong>{v.previewUrl&&<audio controls preload="none" src={v.previewUrl}/>}<small>{v.available?'Dostupan preko API-ja':v.reason}</small><button disabled={!v.available} onClick={()=>setVoice(v.id)}>Odaberi</button></article>)}</div>{chosenVoice?.available===false&&<p>{chosenVoice.reason}</p>}</section>
 <section className="local-narration-generate"><h3>Generisanje</h3><button disabled={!voice||!text.trim()||chosenVoice?.available===false} onClick={async()=>{setBusy(true);try{const r=await apiFetch('/api/narration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({voiceId:voice,text})});if(!r.ok){const result=await r.json();throw new Error(result.error||'Naracija nije generisana.');}const added=await onAdd([new File([await r.blob()],`naracija-${Date.now()}.mp3`,{type:'audio/mpeg'})],start,'narration');if(added)setMessage('Naracija je dodana na svoju stazu. Prilagodi intervale stvarnom trajanju govora.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Generiši naraciju</button></section></>}
 {audio&&selected?.type==='audio'&&<><label>Početak odabranog zvuka<input type="number" min="0" step=".1" value={selected.start} onChange={e=>onPatch({start:Math.max(0,Number(e.target.value))})}/></label><label>Glasnoća · {selected.volume}%<input type="range" min="0" max="150" value={selected.volume} onChange={e=>onPatch({volume:Number(e.target.value)})}/></label><button onClick={()=>onPatch({muted:!selected.muted})}>{selected.muted?'Uključi zvuk':'Isključi zvuk'}</button><button onClick={onRemove}>Ukloni zvuk</button></>}
 {panel==='captions'&&<LocalCaptionPanel document={document} onChange={onCaptions} onSeek={onSeek} onImport={()=>onCaptions(scriptCaptions(script))}/>}
 {panel==='transitions'&&<><p>{selected?.type==='video'&&isImage?'Podešavanja odabrane slike.':'Početne postavke za nove slike; odaberi sliku da promijeniš postojeći kadar.'}</p><section className="local-motion-section"><h3>Učitavanje kadra</h3><StyleDropdown label="Animacija ulaska" value={motion.imageTransition||'cut'} onChange={e=>patchMotion({imageTransition:e.target.value as StillMotion['imageTransition']})}><option value="cut">Bez animacije</option><option value="crossfade">Pretapanje</option><option value="fade">Fade iz crne</option><option value="slide-left">Slide slijeva</option><option value="slide-right">Slide zdesna</option><option value="slide-up">Slide odozdo</option><option value="slide-down">Slide odozgo</option></StyleDropdown><label>Trajanje ulaska (s)<input type="number" min=".1" max="3" step=".1" value={motion.imageTransitionDuration||.5} onChange={e=>patchMotion({imageTransitionDuration:Math.max(.1,Math.min(3,Number(e.target.value)))})}/></label></section><section className="local-motion-section"><h3>Ponašanje tokom kadra</h3><StyleDropdown label="Pokret" value={motion.motion||'none'} onChange={e=>patchMotion({motion:e.target.value as StillMotion['motion']})}><option value="none">Mirna slika</option><option value="zoom-in">Blagi zoom in</option><option value="zoom-out">Blagi zoom out</option><option value="pan">Pomak</option><option value="shake">Blagi shake</option></StyleDropdown></section>{selected?.type==='video'&&<><label>Trajanje slike (s)<input type="number" min=".5" max="600" step=".1" value={selected.outPoint-selected.inPoint} onChange={e=>onPatch({outPoint:selected.inPoint+Math.max(.5,Math.min(600,Number(e.target.value)))})}/></label><label>Veličina<input type="range" min=".2" max="3" step=".05" value={selected.scale||1} onChange={e=>onPatch({scale:Number(e.target.value)})}/></label></>}</>}
 {(busy||message||error)&&<p role="status">{busy?'Radim…':message||error}</p>}</fieldset>;
}
