import {useEffect,useImperativeHandle,useRef,useState,type Ref} from 'react';
import {apiFetch,apiJson} from '../lib/api';
import {jsonBody,uploadAsset,type Script,type Asset} from '../lib/production';
import type {ProjectSaveHandle,ProjectSnapshot} from './ProjectToolbar/ProjectToolbar';
import {EditorHeaderPortal} from './EditorHeaderPortal/EditorHeaderPortal';
import {useProduction} from './ProductionWorkspace';
import {useUnsaved} from '../lib/use-unsaved';
const remoteFiles=new WeakMap<File,string>();
export function rememberRemoteFile(file:File,id:string){remoteFiles.set(file,id);}
export type LocalEditorDocument={editor:'edita';data:Record<string,unknown>;files:{key:string;id:string}[]};
export function LocalVideoStorage({script,snapshot,restore,saveHandle,changeKey,disabled}:{script:Script;snapshot:()=>Promise<ProjectSnapshot>;restore:(data:Record<string,unknown>,files:Map<string,File>)=>Promise<void>;saveHandle:Ref<ProjectSaveHandle>;changeKey?:string;disabled:boolean}){
 const {putScript}=useProduction();const [message,setMessage]=useState(''),[opening,setOpening]=useState(true),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false);const latest=useRef({script,snapshot,restore,putScript,changeKey});latest.current={script,snapshot,restore,putScript,changeKey};const activeSave=useRef<Promise<boolean>|null>(null),lastSaved=useRef(''),savedKey=useRef('');
 useUnsaved(!opening&&!blocked&&!!changeKey&&changeKey!==savedKey.current);
 async function save(){if(opening||disabled||blocked)return false;if(activeSave.current){if(!await activeSave.current)return false;if(savedKey.current===latest.current.changeKey)return true;}const keyAtStart=latest.current.changeKey;const task=(async()=>{setBusy(true);setMessage('Spremanje…');try{const s=await latest.current.snapshot();const files=[];for(const item of s.files){let id=remoteFiles.get(item.file);if(!id){const clips=Array.isArray(s.data.clips)?s.data.clips as {assetId:string;audioRole?:'narration'|'sound'}[]:[];const audioRole=clips.find(c=>c.assetId===item.key)?.audioRole;const asset=await uploadAsset(script.project,item.file,{scriptId:script.id,audioRole,purpose:item.file.type.startsWith('audio/')?(audioRole==='narration'?'narration':'audio'):'image'});id=asset.id;remoteFiles.set(item.file,id);}files.push({key:item.key,id});}const result=await apiJson<Script>(`/api/scripts/${script.id}`,jsonBody({storyboard:{editor:'edita',data:s.data,files}},'PATCH'));lastSaved.current=JSON.stringify(s.data);savedKey.current=keyAtStart||'';latest.current.putScript(result);setMessage('Spremljeno lokalno');return true;}catch(e){setMessage((e as Error).message);return false;}finally{setBusy(false);activeSave.current=null;}})();activeSave.current=task;return task;}
 useImperativeHandle(saveHandle,()=>({save}));
 useEffect(()=>{let active=true;void(async()=>{try{const doc=script.storyboard as unknown as Partial<LocalEditorDocument>;if(doc.editor==='edita'&&doc.data&&doc.files){const list=await apiJson<{assets:Asset[]}>(`/api/projects/${script.project}/assets`);const files=new Map<string,File>();for(const ref of doc.files){const a=list.assets.find(a=>a.id===ref.id);if(!a)throw new Error('Nedostaje datoteka projekta.');const r=await apiFetch(a.url);if(!r.ok)throw new Error('Datoteka se ne može učitati.');const file=new File([await r.blob()],a.name,{type:a.contentType});rememberRemoteFile(file,a.id);files.set(ref.key,file);}if(active){await latest.current.restore(doc.data,files);lastSaved.current=JSON.stringify(doc.data);}}if(active)setMessage('Spremljeno lokalno');}catch(e){if(active){setMessage((e as Error).message);setBlocked(true);}}finally{if(active)setOpening(false);}})();return()=>{active=false;};},[script.id]);
 useEffect(()=>{if(opening||disabled||busy||blocked||!changeKey||changeKey===savedKey.current)return;const timer=setTimeout(()=>void save(),1800);return()=>clearTimeout(timer);},[changeKey,opening,disabled,busy,blocked]);
 return <><EditorHeaderPortal slot="project"><div className="local-video-save"><strong>{script.title}</strong><small role="status">{opening?'Učitavanje…':message}</small><button disabled={busy||opening||disabled||blocked} onClick={()=>void save()}>Spremi</button></div></EditorHeaderPortal>{opening&&<div className="local-video-opening" role="status">Učitavanje montaže…</div>}</>;
}
