import './PlatformPreview.scss';
function Glyph({name}:{name:string}){const paths:Record<string,React.ReactNode>={send:<path d="m2 3 20 1-9 18-3-11-8-8Zm8 8L22 4"/>,heart:<path d="M12 21S2 15 2 8a5 5 0 0 1 10-3 5 5 0 0 1 10 3c0 7-10 13-10 13Z"/>,comment:<><path d="M21 10a9 9 0 1 0-9 9h2l5 3v-6a9 9 0 0 0 2-6Z"/><path d="M7 10h.01M12 10h.01M17 10h.01" stroke="#444" strokeWidth="2.5" strokeLinecap="round"/></>,save:<path d="M5 3h14v19l-7-5-7 5Z"/>,share:<path d="m14 2 9 9-9 9v-6c-6 0-9 3-12 7 0-9 4-14 12-14Z"/>,search:<><circle cx="10" cy="10" r="7" fill="none" stroke="currentColor" strokeWidth="2"/><path d="m15 15 7 7" stroke="currentColor" strokeWidth="2"/></>,home:<path d="m2 11 10-9 10 9v11h-7v-8H9v8H2Z"/>,person:<><circle cx="12" cy="7" r="4" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M3 22v-3c0-8 18-8 18 0v3Z" fill="none" stroke="currentColor" strokeWidth="2"/></>,plus:<path d="M12 4v16M4 12h16" fill="none" stroke="currentColor" strokeWidth="3"/>,camera:<><rect x="2" y="5" width="20" height="16" rx="4" fill="none" stroke="currentColor" strokeWidth="2"/><circle cx="12" cy="13" r="4" fill="none" stroke="currentColor" strokeWidth="2"/></>,like:<path d="M8 10 13 2c4 0 1 8 1 8h7l-2 12H8ZM2 10h4v12H2Z"/>,dots:<><circle cx="4" cy="12" r="2"/><circle cx="12" cy="12" r="2"/><circle cx="20" cy="12" r="2"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true" fill="currentColor">{paths[name]||paths.dots}</svg>;}
export function PlatformPreview({platform}:{platform:string}){
 const tik=platform==='tiktok',insta=platform==='instagram',facebook=platform==='facebook',story=platform==='story';
 return <div className={`social-preview social-${platform}`} aria-hidden="true">
 {story?<><div className="story-progress"/><div className="story-heading"><i/> <b>instagram</b><span>15h</span><span className="story-more">···</span><span>×</span></div></>:<>
 <div className="social-status"><b>9:41</b><span><svg viewBox="0 0 46 16"><path d="M1 13v-2m4 2V8m4 5V5m4 8V2" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M19 5q6-6 12 0m-10 3q4-4 8 0m-6 3q2-2 4 0" fill="none" stroke="currentColor" strokeWidth="2"/><rect x="35" y="3" width="9" height="10" rx="2" fill="none" stroke="currentColor"/><path d="M37 5h5v6h-5z"/></svg></span></div>
 <div className="social-heading">{tik?<><span className="social-live">LIVE</span><span>Following</span><b>For you</b><Glyph name="search"/></>:insta?<><Glyph name="search"/><Glyph name="camera"/></>:facebook?<><b>Reels</b><Glyph name="camera"/></>:<><span/><div className="shorts-top"><span>▱</span><Glyph name="search"/><span>⋮</span></div></>}</div>
 <div className="social-actions">{tik&&<span className="social-avatar"><i>+</i></span>}{(insta?['heart','comment','send','dots']:facebook?['like','comment','share','dots']:tik?['heart','comment','save','share']:['like','dislike','comment','share','remix']).map((n,i)=><span key={n} className={`social-action-${n}`}><span className={n==='dislike'?'dislike-icon':''}><Glyph name={n==='dislike'?'like':n==='remix'?'plus':n}/></span><small>{(insta||facebook?['2.8M','2.8M','2.8M','']:tik?['145.1K','942','6180','28.1K']:['248','Dislike','25','Share','Remix'])[i]}</small></span>)}<span className="social-record">{insta&&<Glyph name="camera"/>}</span></div>
 <div className="social-description">{insta?<><div className="social-profile"><span><Glyph name="person"/></span><b>@Your name</b></div><span>Here are some descriptions about videos</span><small>● Music name</small></>:<><b>{tik?'TikTok ✓':facebook?'@Your name':'@youtube'}{!tik&&<em>{facebook?'Follow':'Subscribe'}</em>}</b>{tik?<><span>This a TikTok video with a long description of the video content. #tiktok #viral... more</span><small>See translation</small></>:facebook?<><span>Your video description</span><small>♫ Original audio</small></>:<><span>▸ Playlist 1</span><span>Youtube shorts interface<br/><b>#youtube #shorts #viral</b></span></>}</>}</div>
 </>}
 </div>;
}
