import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {apiJson} from '../lib/api';
import {jsonBody,type Production,type Script,type Asset,type Chapter} from '../lib/production';
import {SelectField} from './CreativeControls';
import {LocalDialog} from './LocalDialog';
import {useAuth} from '../context/auth-context';
export function Icon({name='folder',className=''}:{name?:'folder'|'file'|'chevron'|'plus'|'image'|'film'|'spark';className?:string}){const paths={folder:'M3 7h6l2-3h4l2 3h4v13H3Z',file:'M6 3h8l4 4v14H6Z M14 3v5h4 M9 12h6 M9 16h6',chevron:'m6 9 6 6 6-6',plus:'M12 5v14 M5 12h14',image:'M3 3h18v18H3Z M3 17l6-6 4 4 3-3 5 5 M15 7h.01',film:'M3 4h18v16H3Z M7 4v16 M17 4v16 M3 8h4 M3 16h4 M17 8h4 M17 16h4',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z'};return <svg className={className} width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round" strokeLinecap="round" aria-hidden="true"><path d={paths[name]}/></svg>;}
type Workspace={projects:Production[];scripts:Script[];chapters:Chapter[];loading:boolean;error:string;reload:()=>Promise<void>;putProject:(p:Production)=>void;putScript:(s:Script)=>void;createScript:(project?:string,chapter?:string)=>void;createChapter:(project:string)=>void};
const Context=createContext<Workspace|null>(null);
export function ProductionProvider({children}:{children:ReactNode}){
 const {session}=useAuth();const [projects,setProjects]=useState<Production[]>([]),[scripts,setScripts]=useState<Script[]>([]),[chapters,setChapters]=useState<Chapter[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [adding,setAdding]=useState(false),[project,setProject]=useState(''),[chapter,setChapter]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false);
 const [chapterProject,setChapterProject]=useState(''),[chapterName,setChapterName]=useState('');const [,setParams]=useSearchParams();
 const reload=async()=>{setError('');try{const [p,s,c]=await Promise.all([apiJson<Production[]>('/api/projects?kind=production'),apiJson<Script[]>('/api/scripts'),apiJson<Chapter[]>('/api/chapters')]);setProjects(p);setScripts(s);setChapters(c);}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setLoading(false);}};
 useEffect(()=>{if(!session.user||session.user.mustChangePassword)return;void reload();},[session.user?.id,session.user?.mustChangePassword]);
 const putProject=(p:Production)=>setProjects(list=>[p,...list.filter(i=>i.id!==p.id)]);const putScript=(s:Script)=>setScripts(list=>[s,...list.filter(i=>i.id!==s.id)]);
 const createChapter=(id:string)=>{setChapterProject(id);setChapterName(`Chapter ${chapters.filter(c=>c.project===id).length+1}`);setError('');};
 return <Context.Provider value={{projects,scripts,chapters,loading,error,reload,putProject,putScript,createChapter,createScript:(id,ch)=>{const chosen=id||projects[0]?.id||'';setProject(chosen);setChapter(ch||'');setName(`Skripta ${scripts.filter(s=>s.project===chosen).length+1}`);setAdding(true);setError('');}}}>{children}
 {adding&&<LocalDialog title="Nova skripta" busy={busy} onClose={()=>setAdding(false)}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=await apiJson<Script>('/api/scripts',jsonBody({project,chapter:chapter||null,title:name.trim(),content:''}));putScript(result);setParams({project,script:result.id});setAdding(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><p>Odaberi projekat, chapter i naziv skripte.</p>{projects.length?<><SelectField label="Projekat" value={project} onChange={id=>{setProject(id);setChapter('');}} options={projects.map(p=>[p.id,p.name])}/><div className="chapter-select-row"><SelectField label="Odaberi chapter" value={chapter} onChange={setChapter} options={[["","Bez chaptera"],...chapters.filter(c=>c.project===project).map(c=>[c.id,c.title])]}/><button type="button" title="Dodaj chapter" onClick={()=>createChapter(project)}><Icon name="plus"/></button></div><label>Naziv skripte<input placeholder="Epizoda 1" autoFocus value={name} onChange={e=>setName(e.target.value)} maxLength={160} required/></label></>:<p>Prvo <Link to="/projekti" onClick={()=>setAdding(false)}>kreiraj projekat</Link>.</p>}{error&&<p role="alert">{error}</p>}<div className="production-row"><button type="button" disabled={busy} onClick={()=>setAdding(false)}>Odustani</button><button className="klipanje-primary" disabled={busy||!project||!name.trim()}>Dodaj skriptu</button></div></form></LocalDialog>}
 {chapterProject&&<LocalDialog title="Novi chapter" busy={busy} onClose={()=>setChapterProject('')}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const c=await apiJson<Chapter>('/api/chapters',jsonBody({project:chapterProject,title:chapterName.trim()}));setChapters(list=>[...list,c]);if(adding&&project===chapterProject)setChapter(c.id);setChapterProject('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><p>{projects.find(p=>p.id===chapterProject)?.name}</p><label>Naziv chaptera<input autoFocus required maxLength={160} value={chapterName} onChange={e=>setChapterName(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<div className="production-row"><button type="button" disabled={busy} onClick={()=>setChapterProject('')}>Odustani</button><button className="klipanje-primary" disabled={busy||!chapterName.trim()}>Dodaj chapter</button></div></form></LocalDialog>}
 </Context.Provider>;
}
export function useProduction(){const value=useContext(Context);if(!value)throw new Error('ProductionProvider required');return value;}
export function useSelection(){const w=useProduction();const [params,setParams]=useSearchParams();const project=w.projects.find(p=>p.id===params.get('project'))||w.projects[0];const script=w.scripts.find(s=>s.id===params.get('script')&&s.project===project?.id)||w.scripts.find(s=>s.project===project?.id);return {...w,project,script,params,select:(project:string,script?:string,segment?:string)=>setParams({project,...script?{script}:{},...segment?{segment}:{}})};}
export function ProjectTree({photos=false,beforeSelect}:{photos?:boolean;beforeSelect?:()=>boolean|Promise<boolean>}){
 const w=useSelection();const [closed,setClosed]=useState<string[]>([]);const ready=async()=>!beforeSelect||await beforeSelect();
 const renderScript=(s:Script)=><div key={s.id} className="production-tree-script"><button className={w.script?.id===s.id?'selected':''} onClick={async()=>{if(await ready())w.select(s.project,s.id);}}><Icon name="file"/><span>{s.title}</span><Icon name="chevron"/></button>{photos&&w.script?.id===s.id&&<div className="production-tree-folders">{[{id:'',text:'Sve fotografije'},...s.segments.map((seg,i)=>({id:seg.id,text:`${String(i+1).padStart(2,'0')} · ${seg.start}s – ${seg.end}s`}))].map(item=><button key={item.id} className={(w.params.get('segment')||'')===item.id?'selected':''} onClick={async()=>{if(await ready())w.select(s.project,s.id,item.id);}}><Icon name="folder"/><span>{item.text}</span></button>)}</div>}</div>;
 return <aside className={`production-tree${photos?' photo-project-tree':''}`}><header><strong>Moji projekti</strong><Link to="/projekti" title="Uredi projekte"><Icon name="folder"/></Link></header><button className="klipanje-primary" onClick={async()=>{if(await ready())w.createScript(w.project?.id);}}><Icon name="plus"/>Dodaj skriptu</button>{w.project&&<button className="klipanje-primary tree-add-chapter" onClick={async()=>{if(await ready())w.createChapter(w.project!.id);}}><Icon name="plus"/>Dodaj chapter</button>}
 {w.loading?<p>Učitavanje…</p>:!w.projects.length?<div className="production-empty"><p>Prvo napravi projekat.</p><Link to="/projekti">+ Novi projekat</Link></div>:w.projects.map(p=><section key={p.id}><div className="production-tree-project"><button aria-expanded={!closed.includes(p.id)} onClick={()=>setClosed(list=>list.includes(p.id)?list.filter(id=>id!==p.id):[...list,p.id])}><Icon name="chevron" className={closed.includes(p.id)?'closed':''}/><Icon/><span>{p.name}</span></button><button title={`Dodaj skriptu u ${p.name}`} onClick={async()=>{if(await ready())w.createScript(p.id);}}><Icon name="plus"/></button></div>{!closed.includes(p.id)&&<div className="production-tree-scripts">{w.scripts.filter(s=>s.project===p.id&&!s.chapter).map(renderScript)}{w.chapters.filter(c=>c.project===p.id).map(c=><details key={c.id} className="tree-chapter" open><summary><Icon name="chevron"/><Icon name="folder"/><span>{c.title}</span></summary><button className="chapter-add-script" title={`Dodaj skriptu u ${c.title}`} onClick={async()=>{if(await ready())w.createScript(p.id,c.id);}}><Icon name="plus"/>Skripta</button>{w.scripts.filter(s=>s.chapter===c.id).map(renderScript)}</details>)}{!w.scripts.some(s=>s.project===p.id)&&<small>Još nema skripti.</small>}</div>}</section>)}{w.error&&<p role="alert">{w.error}</p>}</aside>;
}
export function useAssets(projectId?:string,refreshKey?:string){const [assets,setAssets]=useState<Asset[]>([]),[error,setError]=useState('');useEffect(()=>{setAssets([]);setError('');if(!projectId)return;let active=true;void apiJson<{assets:Asset[]}>(`/api/projects/${projectId}/assets`).then(r=>{if(active)setAssets(r.assets);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[projectId,refreshKey]);return {assets,setAssets,error};}
