import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {apiJson} from '../lib/api';
import {jsonBody,type Production,type Script,type Asset} from '../lib/production';
import {useAuth} from '../context/auth-context';
export function Icon({name='folder',className=''}:{name?:'folder'|'file'|'chevron'|'plus'|'image'|'film'|'spark';className?:string}){const paths={folder:'M3 7h6l2-3h4l2 3h4v13H3Z',file:'M6 3h8l4 4v14H6Z M14 3v5h4 M9 12h6 M9 16h6',chevron:'m6 9 6 6 6-6',plus:'M12 5v14 M5 12h14',image:'M3 3h18v18H3Z M3 17l6-6 4 4 3-3 5 5 M15 7h.01',film:'M3 4h18v16H3Z M7 4v16 M17 4v16 M3 8h4 M3 16h4 M17 8h4 M17 16h4',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z'};return <svg className={className} width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round" strokeLinecap="round" aria-hidden="true"><path d={paths[name]}/></svg>;}
type Workspace={projects:Production[];scripts:Script[];loading:boolean;error:string;reload:()=>Promise<void>;putProject:(p:Production)=>void;putScript:(s:Script)=>void;createScript:(project?:string)=>void};
const Context=createContext<Workspace|null>(null);
export function ProductionProvider({children}:{children:ReactNode}){
 const {session}=useAuth();const [projects,setProjects]=useState<Production[]>([]),[scripts,setScripts]=useState<Script[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [adding,setAdding]=useState(false),[project,setProject]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false);const [,setParams]=useSearchParams();
 const reload=async()=>{setError('');try{const [p,s]=await Promise.all([apiJson<Production[]>('/api/projects?kind=production'),apiJson<Script[]>('/api/scripts')]);setProjects(p);setScripts(s);}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setLoading(false);}};
 useEffect(()=>{if(session.user?.mustChangePassword)return;void reload();},[session.user?.id,session.user?.mustChangePassword]);
 const putProject=(p:Production)=>setProjects(list=>[p,...list.filter(i=>i.id!==p.id)]);const putScript=(s:Script)=>setScripts(list=>[s,...list.filter(i=>i.id!==s.id)]);
 return <Context.Provider value={{projects,scripts,loading,error,reload,putProject,putScript,createScript:(id)=>{setProject(id||projects[0]?.id||'');setName('');setAdding(true);setError('');}}}>{children}{adding&&<div className="production-modal"><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=await apiJson<Script>('/api/scripts',jsonBody({project,title:name.trim(),content:''}));putScript(result);setParams({project,script:result.id});setAdding(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h2>Dodaj skriptu</h2>{projects.length?<><label>Projekat<select value={project} onChange={e=>setProject(e.target.value)}>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Naziv skripte<input autoFocus value={name} onChange={e=>setName(e.target.value)} maxLength={160} required/></label></>:<p>Prvo <Link to="/projekti" onClick={()=>setAdding(false)}>kreiraj projekat</Link>.</p>}{error&&<p role="alert">{error}</p>}<div className="production-row"><button type="button" disabled={busy} onClick={()=>setAdding(false)}>Odustani</button><button className="klipanje-primary" disabled={busy||!project||!name.trim()}>Dodaj skriptu</button></div></form></div>}</Context.Provider>;
}
export function useProduction(){const value=useContext(Context);if(!value)throw new Error('ProductionProvider required');return value;}
export function useSelection(){const w=useProduction();const [params,setParams]=useSearchParams();const project=w.projects.find(p=>p.id===params.get('project'))||w.projects[0];const script=w.scripts.find(s=>s.id===params.get('script')&&s.project===project?.id)||w.scripts.find(s=>s.project===project?.id);return {...w,project,script,params,select:(project:string,script?:string,segment?:string)=>setParams({project,...script?{script}:{},...segment?{segment}:{}})};}
export function ProjectTree({photos=false,beforeSelect}:{photos?:boolean;beforeSelect?:()=>boolean|Promise<boolean>}){const w=useSelection();const [closed,setClosed]=useState<string[]>([]);return <aside className="production-tree"><header><strong>Moji projekti</strong><Link to="/projekti" title="Uredi projekte"><Icon name="folder"/></Link></header><button className="klipanje-primary" onClick={async()=>{if(beforeSelect&&!await beforeSelect())return;w.createScript(w.project?.id);}}><Icon name="plus"/>Dodaj skriptu</button>{w.loading?<p>Učitavanje…</p>:!w.projects.length?<div className="production-empty"><p>Prvo napravi projekat.</p><Link to="/projekti">+ Novi projekat</Link></div>:w.projects.map(p=><section key={p.id}><div className="production-tree-project"><button aria-expanded={!closed.includes(p.id)} onClick={()=>setClosed(list=>list.includes(p.id)?list.filter(id=>id!==p.id):[...list,p.id])}><Icon name="chevron" className={closed.includes(p.id)?'closed':''}/><Icon/><span>{p.name}</span></button><button title={`Dodaj skriptu u ${p.name}`} onClick={async()=>{if(!beforeSelect||await beforeSelect())w.createScript(p.id);}}><Icon name="plus"/></button></div>{!closed.includes(p.id)&&<div className="production-tree-scripts">{w.scripts.filter(s=>s.project===p.id).map(s=><div key={s.id}><button className={w.script?.id===s.id?'selected':''} onClick={async()=>{if(!beforeSelect||await beforeSelect())w.select(p.id,s.id);}}><Icon name="file"/><span>{s.title}</span><Icon name="chevron"/></button>{photos&&w.script?.id===s.id&&<div className="production-tree-folders">{[{id:'',text:'Sve fotografije'},...s.segments.map((seg,i)=>({id:seg.id,text:`${String(i+1).padStart(2,'0')} · ${seg.start}s – ${seg.end}s`}))].map(item=><button key={item.id} className={(w.params.get('segment')||'')===item.id?'selected':''} onClick={async()=>{if(!beforeSelect||await beforeSelect())w.select(p.id,s.id,item.id);}}><Icon name="folder"/><span>{item.text}</span></button>)}</div>}</div>)}{!w.scripts.some(s=>s.project===p.id)&&<small>Još nema skripti.</small>}</div>}</section>)}{w.error&&<p role="alert">{w.error}</p>}</aside>;}
export function useAssets(projectId?:string,refreshKey?:string){const [assets,setAssets]=useState<Asset[]>([]),[error,setError]=useState('');useEffect(()=>{setAssets([]);setError('');if(!projectId)return;let active=true;void apiJson<{assets:Asset[]}>(`/api/projects/${projectId}/assets`).then(r=>{if(active)setAssets(r.assets);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[projectId,refreshKey]);return {assets,setAssets,error};}
