import {useEffect,useLayoutEffect,useRef,useState,useId,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
export function SettingsPopover({label,children,icon,value}:{label:string;children:ReactNode;icon?:ReactNode;value?:string}){
 const [open,setOpen]=useState(false),[position,setPosition]=useState({left:0,top:0,width:260,maxHeight:350});
 const button=useRef<HTMLButtonElement>(null),panel=useRef<HTMLDivElement>(null),id=useId();
 useLayoutEffect(()=>{if(!open)return;const place=()=>{const box=button.current?.getBoundingClientRect();if(!box)return;const sidebar=button.current?.closest('.subtitle-inspector,.video-caption-editor')?.getBoundingClientRect(),leftEdge=Math.max(8,(sidebar?.left??0)+8),rightEdge=Math.min(window.innerWidth-8,(sidebar?.right??window.innerWidth)-8),width=Math.min(290,rightEdge-leftEdge),height=Math.min(panel.current?.scrollHeight||280,window.innerHeight-24),below=window.innerHeight-box.bottom-12,down=below>=height||below>box.top;setPosition({left:Math.max(leftEdge,Math.min(box.left,rightEdge-width)),top:down?box.bottom+6:Math.max(8,box.top-height-6),width,maxHeight:Math.max(100,down?below:box.top-12)});};place();window.addEventListener('resize',place);window.addEventListener('scroll',place,true);return()=>{window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true);};},[open]);
 useEffect(()=>{if(!open)return;const outside=(event:PointerEvent)=>{if(!panel.current?.contains(event.target as Node)&&!button.current?.contains(event.target as Node))setOpen(false);};const keys=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);button.current?.focus();}if(event.key==='Tab'&&panel.current){const inputs=Array.from(panel.current.querySelectorAll<HTMLElement>('input:not(:disabled),button:not(:disabled),[tabindex="0"]'));const next=event.shiftKey?inputs.at(-1):inputs[0];if((event.shiftKey&&document.activeElement===inputs[0])||(!event.shiftKey&&document.activeElement===inputs.at(-1))){event.preventDefault();next?.focus();}}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',keys);panel.current?.querySelector<HTMLElement>('input,button')?.focus();return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',keys);};},[open]);
 return <div className="settings-popover language-dropdown"><span>{icon||value!==undefined?label:'\u00a0'}</span><button type="button" ref={button} className="language-dropdown-trigger" aria-label={label} title={label} aria-expanded={open} aria-haspopup="dialog" aria-controls={id} onClick={()=>setOpen(value=>!value)}><span>{icon||value||label}</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></button>{open&&createPortal(<div id={id} ref={panel} role="dialog" aria-label={label} className="caption-settings-popover" style={position}><header>{value===undefined&&<strong>{label}</strong>}<button type="button" aria-label="Zatvori" onClick={()=>{setOpen(false);button.current?.focus();}}>×</button></header>{children}</div>,button.current?.closest('dialog')||document.body)}</div>;
}
