import {formatSeconds} from '../lib/format-seconds';
import {useState} from 'react';
import {TextFontPicker} from './TextFontPicker';
import type {Overlay} from '../lib/video-overlays';
import {textFonts,textEffects,applyTextEffect} from '../lib/text-presets';
import {OverlayPresetPreview} from './OverlayPresetPreview';
function AlignmentIcon({vertical=false,index=1}:{vertical?:boolean;index?:number}){
 return <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" aria-hidden="true">{vertical?<><path d="M5 4v16"/><path d={`M10 ${index===0?4:index===1?7:10}v10M15 4v16M20 ${index===0?4:index===1?7:10}v10`}/></>:<path d={`M4 5h16M${index===0?4:index===1?7:10} 10h10M4 15h16M${index===0?4:index===1?7:10} 20h10`}/>}</svg>;
}
function Slider({label,value,min=0,max=100,step=1,onChange}:{label:string;value:number;min?:number;max?:number;step?:number;onChange:(v:number)=>void}){
 return <label className="text-value-slider"><span>{label}</span><div><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><input aria-label={`${label} vrijednost`} type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(Math.max(min,Math.min(max,Number(e.target.value))))}/></div></label>;
}
export function TextDesignControls({item,onChange}:{item:Overlay;onChange:(o:Overlay)=>void}){
 const [open,setOpen]=useState<string|null>(null);
 const toggle=(id:string)=>setOpen(open===id?null:id);
 const update=(patch:Partial<Overlay>)=>onChange({...item,...patch});
 const more=(id:string,label:string)=><button className="text-more" aria-label={label} aria-expanded={open===id} onClick={()=>toggle(id)}>•••</button>;
 return <div className="text-basic-panel"><textarea aria-label="Tekst" rows={2} maxLength={500} value={item.text} onChange={e=>update({text:e.target.value})}/>
 <div className="text-font-size-row"><TextFontPicker value={item.fontFamily||textFonts[0].value} onChange={fontFamily=>update({fontFamily})}/><input aria-label="Veličina fonta" type="number" min={12} max={240} value={item.fontSize||72} onChange={e=>update({fontSize:Math.max(12,Math.min(240,Number(e.target.value)))})}/></div>
 <div className="text-basic-format">{(['bold','italic','underline'] as const).map((key,i)=><button key={key} className={`format-${key}`} title={['Podebljano','Kurziv','Podvučeno'][i]} aria-label={['Podebljano','Kurziv','Podvučeno'][i]} aria-pressed={!!item[key]} onClick={()=>update({[key]:!item[key]})}>{['B','I','U'][i]}</button>)}<button title="Poravnanje teksta" aria-label="Poravnanje teksta" aria-expanded={open==='align'} onClick={()=>toggle('align')}><AlignmentIcon vertical/><svg className="text-dropdown-chevron" width="9" height="9" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></button><button aria-label="Velika slova" aria-pressed={!!item.uppercase} onClick={()=>update({uppercase:!item.uppercase})}>Aa</button><button title="Razmaci i smjer teksta" aria-label="Razmaci i smjer teksta" aria-expanded={open==='spacing'} onClick={()=>toggle('spacing')}>↕≡</button></div>
 {open==='align'&&<div className="text-inline-options text-align-options">{(['left','center','right'] as const).map((align,i)=><button key={align} aria-label={['Poravnaj lijevo','Poravnaj u sredinu','Poravnaj desno'][i]} aria-pressed={(item.align||'center')===align} onClick={()=>update({align})}><AlignmentIcon index={i}/></button>)}{(['top','middle','bottom'] as const).map((verticalAlign,i)=><button key={verticalAlign} aria-label={['Poravnaj uz vrh','Poravnaj okomito u sredinu','Poravnaj uz dno'][i]} aria-pressed={(item.verticalAlign||'middle')===verticalAlign} onClick={()=>update({verticalAlign})}><AlignmentIcon vertical index={i}/></button>)}</div>}
 {open==='spacing'&&<div className="text-inline-options"><Slider label="Letter spacing" min={-5} max={30} value={item.letterSpacing||0} onChange={letterSpacing=>update({letterSpacing})}/><Slider label="Line height" min={.8} max={3} step={.1} value={item.lineHeight||1.2} onChange={lineHeight=>update({lineHeight})}/><label className="overlay-check"><input type="checkbox" checked={!!item.verticalText} onChange={e=>update({verticalText:e.target.checked})}/>Okomiti tekst</label></div>}
 <Slider label="Opacity (%)" value={item.opacity} onChange={opacity=>update({opacity})}/>
 <section className="text-style-rows"><strong>Style</strong>
 <div className="text-style-row"><span>Fill</span><input aria-label="Fill boja" type="color" value={item.color} onChange={e=>update({color:e.target.value})}/></div>
 <div className="text-style-row"><span>Stroke</span><input aria-label="Stroke boja" type="color" value={item.strokeColor||'#171717'} onChange={e=>update({strokeColor:e.target.value,strokeWidth:item.strokeWidth||2})}/>{more('stroke','Postavke konture')}</div>
 {open==='stroke'&&<div className="text-inline-options"><Slider label="Debljina" max={20} value={item.strokeWidth||0} onChange={strokeWidth=>update({strokeWidth})}/></div>}
 <div className="text-style-row"><span>Background</span><input aria-label="Background boja" type="color" value={item.background==='transparent'?'#171717':item.background} onChange={e=>update({background:e.target.value})}/>{more('background','Postavke pozadine')}</div>
 {open==='background'&&<div className="text-inline-options"><Slider label="Opacity pozadine (%)" value={item.background==='transparent'?0:item.backgroundOpacity??100} onChange={backgroundOpacity=>update({backgroundOpacity,background:item.background==='transparent'?'#171717':item.background})}/><button onClick={()=>update({background:'transparent'})}>Bez pozadine</button></div>}
 <div className="text-style-row"><span>Shadow</span><input aria-label="Shadow boja" type="color" value={item.shadowColor||'#171717'} onChange={e=>update({shadowColor:e.target.value,shadowBlur:item.shadowBlur||8})}/>{more('shadow','Postavke sjene')}</div>
 {open==='shadow'&&<div className="text-inline-options"><Slider label="Opacity sjene (%)" value={item.shadowOpacity??100} onChange={shadowOpacity=>update({shadowOpacity})}/><Slider label="Blur" max={100} value={item.shadowBlur||0} onChange={shadowBlur=>update({shadowBlur})}/><Slider label="Distance" max={100} value={item.shadowDistance??item.shadowOffset??0} onChange={shadowDistance=>update({shadowDistance})}/><Slider label="Angle (°)" min={-180} max={180} value={item.shadowAngle??45} onChange={shadowAngle=>update({shadowAngle})}/><label className="overlay-check"><input type="checkbox" checked={!!item.glow} onChange={e=>update({glow:e.target.checked})}/>Glow</label></div>}
 </section>
 <details className="text-style-details"><summary>Animacija</summary><label>Ulazak<select value={item.animation||'fade'} onChange={e=>update({animation:e.target.value as Overlay['animation']})}><option value="none">Bez animacije</option><option value="fade">Lagano pojavljivanje</option><option value="rise">Ulazak odozdo</option><option value="pop">Povećavanje</option><option value="slide">Ulazak sa strane</option><option value="typewriter">Slovo po slovo</option></select></label><Slider label="Trajanje (s)" min={.1} max={3} step={.1} value={formatSeconds(item.animationDuration||.6)} onChange={animationDuration=>update({animationDuration})}/></details>
 <details className="text-style-details"><summary>Text effects</summary><div className="overlay-preset-grid">{textEffects.map(p=><button key={p.id} title={p.name} onClick={()=>onChange(applyTextEffect(item,p))}><OverlayPresetPreview preset={p}/><small>{p.name}</small></button>)}</div></details></div>;
}
