import { useEffect, useState, useRef } from 'react';
import { apiJson } from '../lib/api';
const labels:Record<string,string>={captions:'Titlovi',video:'Video',audio:'Zvuk',export:'Izvoz',affiliate:'Affiliate',other:'Ostalo',new:'Novo',reviewing:'U obradi',resolved:'Riješeno',transcription:'Prepoznavanje titlova',titlovi:'Prepoznavanje titlova',narration:'Naracija',voice_change:'Promjena glasa',reserved:'Rezervisano',completed:'Završeno',refunded:'Vraćeno',upload:'Upload'};
const label=(key:string)=>labels[key]||key;
type Row={id:string;created_at:string;category?:string;message?:string;status?:string;user__username?:string;capability?:string;tokens?:number;kind?:string;size?:number};
type Page={rows:Row[];page:number;hasNext:boolean};
export function UserInsights({admin=false}:{admin?:boolean}){
 const [tab,setTab]=useState(admin?'feedback':'operations'),[page,setPage]=useState(1),[data,setData]=useState<Page|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[category,setCategory]=useState('other'),[sent,setSent]=useState(false);
 const pending=useRef<{id:string;message:string;category:string}|null>(null);
 useEffect(()=>{let live=true;setData(null);setError('');const url=admin?'/api/admin/feedback':tab==='feedback'?'/api/feedback':`/api/usage/history?kind=${tab}`;apiJson<Page>(url+(url.includes('?')?'&':'?')+`page=${page}`).then(v=>{if(live)setData(v);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[admin,tab,page,refresh]);
 const send=async()=>{setBusy(true);setError('');setSent(false);try{if(!pending.current||pending.current.message!==message.trim()||pending.current.category!==category)pending.current={id:crypto.randomUUID(),message:message.trim(),category};await apiJson('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pending.current)});pending.current=null;setMessage('');setPage(1);setRefresh(v=>v+1);setSent(true);}catch(e){setError(e instanceof Error?e.message:'Slanje nije uspjelo.');}finally{setBusy(false);}};
 return <section className="user-insights"><div className="billing-toolbar admin-section-header"><h2>{admin?'Feedback korisnika':'Historija i feedback'}</h2><button disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Osvježi</button></div>{!admin&&<div className="billing-toolbar" role="tablist" aria-label="Historija i feedback">{[['operations','Obrade'],['transfers','Prijenos'],['feedback','Feedback']].map(([key,text])=><button role="tab" aria-selected={tab===key} key={key} onClick={()=>{setTab(key);setPage(1);}}>{text}</button>)}</div>}
 {tab==='feedback'&&!admin&&<form onSubmit={e=>{e.preventDefault();void send();}}><label>Oblast <select value={category} onChange={e=>setCategory(e.target.value)}>{['captions','video','audio','export','affiliate','other'].map(k=><option value={k} key={k}>{label(k)}</option>)}</select></label><label>Šta možemo popraviti?<textarea value={message} minLength={5} maxLength={2000} required onChange={e=>setMessage(e.target.value)} placeholder="Opiši problem ili prijedlog. Bez lozinki i osjetljivih podataka."/></label><button disabled={busy||message.trim().length<5}>Pošalji feedback</button>{sent&&<p role="status">Poruka je poslana administraciji.</p>}</form>}
 {tab==='operations'&&<p>Tokeni su Editine jedinice korištenja. Rezervisani iznosi još nisu konačna potrošnja.</p>}{tab==='transfers'&&<p>Evidentirani uploadi i izvozi; ovo nije račun Cloudflarea niti ukupan mrežni promet.</p>}
 {error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Učitavanje…</p>}{data&&<><div className="billing-table-wrap"><table className="billing-table"><thead><tr><th>Vrijeme</th><th>{admin?'Korisnik / poruka':'Radnja'}</th><th>Status / količina</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.id}><td>{new Date(row.created_at).toLocaleString('bs-BA')}</td><td>{admin&&<strong>@{row.user__username}<br/></strong>}{label(row.category||row.capability||row.kind||'')} {row.message&&<p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{row.message}</p>}</td><td>{row.status&&label(row.status)}{row.tokens!==undefined&&` · ${row.tokens} tokena`}{row.size!==undefined&&`${(row.size/1000000).toFixed(2)} MB`}{admin&&<div>{['new','reviewing','resolved'].map(status=><button key={status} disabled={busy||row.status===status} onClick={async()=>{setBusy(true);try{await apiJson(`/api/admin/feedback/${row.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});setRefresh(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Promjena nije uspjela.');}finally{setBusy(false);}}}>{label(status)}</button>)}</div>}</td></tr>)}{!data.rows.length&&<tr><td className="billing-empty" colSpan={3}>Još nema zapisa.</td></tr>}</tbody></table></div><div className="billing-toolbar admin-pagination" role="navigation" aria-label="Stranice rezultata"><button disabled={page===1} onClick={()=>setPage(v=>v-1)}>Prethodna</button><span>{page}</span><button disabled={!data.hasNext} onClick={()=>setPage(v=>v+1)}>Sljedeća</button></div></>}
 </section>;
}
