import {loadOverlayFonts} from '../lib/text-fonts';
import {useEffect,useRef} from 'react';
import {drawOverlays,resizeOverlay,overlayMotion,rotatedOverlayAngle,type OverlayHandle,type Overlay} from '../lib/video-overlays';
export function VideoOverlayLayer({items,time,aspect,selected,disabled,onSelect,onChange,onBegin,onEnd}:{items:Overlay[];time:number;aspect:number;selected:string;disabled:boolean;onSelect:(id:string)=>void;onChange:(item:Overlay)=>void;onBegin:()=>void;onEnd:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null);
 const drag=useRef<{item:Overlay;x:number;y:number;width:number;height:number;edge?:OverlayHandle|'rotate';centerX:number;centerY:number;angle:number}|null>(null);
 useEffect(()=>{let active=true;const draw=()=>{const el=canvas.current;if(!active||!el)return;el.width=1280;el.height=Math.round(1280/aspect);drawOverlays(el.getContext('2d')!,items,time);};draw();void loadOverlayFonts(items).then(draw).catch(()=>{});return()=>{active=false;};},[items,time,aspect]);
 return <div className="video-overlay-layer"><canvas ref={canvas}/>{items.filter(o=>time>=o.start&&time<o.end).map(o=>{const motion=overlayMotion(o,time);return <button key={o.id} aria-label={`Pomjeri ${o.kind==='text'?o.text:'element'}`} className={selected===o.id?'selected':''} disabled={disabled} style={{left:`${o.x+motion.x}%`,top:`${o.y+motion.y}%`,width:`${o.width}%`,height:`${o.height}%`,transform:`translate(-50%,-50%) rotate(${o.rotation}deg) scale(${motion.scale})`}} onPointerDown={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.focus({preventScroll:true});onSelect(o.id);onBegin();const r=e.currentTarget.parentElement!.getBoundingClientRect();const edge=(e.target as HTMLElement).dataset.edge as OverlayHandle|'rotate'|undefined;drag.current={item:o,x:e.clientX,y:e.clientY,width:r.width,height:r.height,edge,centerX:r.left+(o.x+motion.x)/100*r.width,centerY:r.top+(o.y+motion.y)/100*r.height,angle:Math.atan2(e.clientY-(r.top+(o.y+motion.y)/100*r.height),e.clientX-(r.left+(o.x+motion.x)/100*r.width))};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(d?.edge==='rotate'){onChange({...d.item,rotation:rotatedOverlayAngle(d.item.rotation,d.angle,Math.atan2(e.clientY-d.centerY,e.clientX-d.centerX))});return;}if(d?.edge){onChange(resizeOverlay(d.item,d.edge,e.clientX-d.x,e.clientY-d.y,d.width,d.height));return;}if(d)onChange({...d.item,x:Math.max(0,Math.min(100,d.item.x+(e.clientX-d.x)/d.width*100)),y:Math.max(0,Math.min(100,d.item.y+(e.clientY-d.y)/d.height*100))});}} onPointerUp={()=>{drag.current=null;onEnd();}} onPointerCancel={()=>{drag.current=null;onEnd();}} onLostPointerCapture={()=>{if(drag.current){drag.current=null;onEnd();}}} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopPropagation();onChange({...o,x:Math.max(0,Math.min(100,o.x+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0))),y:Math.max(0,Math.min(100,o.y+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0)))});}}>{selected===o.id&&(['n','s','e','w','ne','nw','se','sw'] as const).map(edge=><span key={edge} data-edge={edge} className={`overlay-resize-handle handle-${edge}`} title="Povuci za promjenu veličine"/>)}{selected===o.id&&<span className="overlay-rotation-stem"><span data-edge="rotate" className="overlay-rotation-handle" title={`Rotiraj tekst · ${o.rotation}°`}>↻</span></span>}</button>;})}</div>;
}
