import { Link } from 'react-router-dom';
import { PublicLayout } from '../../components/PublicLayout/PublicLayout';
export default function PrivacyPage() {
  return <PublicLayout><main className="public-content privacy-page">
    <header className="public-hero"><p className="public-kicker">Tvoj sadržaj. Tvoja privatnost.</p><h1>Politika privatnosti</h1><p>Kako Edita koristi podatke dok od tvog snimka nastaju titlovi, glas i gotov video.</p><small>Ažurirano: 11. septembra 2026.</small></header>
    <div className="privacy-layout"><nav aria-label="Sadržaj politike privatnosti"><a href="#odgovornost">Ko smo mi</a><a href="#podaci">Koje podatke obrađujemo</a><a href="#svrha">Zašto ih koristimo</a><a href="#servisi">Pohrana i AI servisi</a><a href="#cuvanje">Čuvanje i brisanje</a><a href="#prava">Tvoja prava</a></nav>
    <article>
      <section id="odgovornost"><h2>Ko stoji iza Edite?</h2><p>Edita.ba je alat za uređivanje videa i izradu titlova koji razvija Gordon Digital Marketing. Za pitanja o obradi podataka i zahtjeve vezane za privatnost kontaktiraj nas na <a href="mailto:info@gordondm.com">info@gordondm.com</a>.</p></section>
      <section id="podaci"><h2>Koje podatke obrađujemo?</h2><p>Podatke koje uneseš pri kreiranju računa, kao što su ime, korisničko ime i adresa e-pošte ako je navedena. Lozinka se čuva u obliku za provjeru prijave, a ne kao čitljiv tekst.</p><p>Obrađujemo snimke koje odabereš za obradu ili spremanje, njihov zvuk, prepoznati tekst, vremenske oznake, nazive projekata i postavke uređivanja. Ako koristiš naratora, obrađuje se uneseni tekst; za promjenu glasa obrađuje se odabrani zvuk.</p><p>Za prijavu i rad aplikacije koriste se podaci o sesiji, sigurnosni tokeni i tehnički podaci potrebni za obradu zahtjeva i otklanjanje grešaka.</p></section>
      <section id="svrha"><h2>Zašto koristimo ove podatke?</h2><p>Da omogućimo prijavu, prepoznavanje govora, izradu i uređivanje titlova, obradu zvuka, spremanje projekata i izvoz videa. Dio obrade potreban je i za zaštitu računa, sprečavanje zloupotrebe i rješavanje zahtjeva podršci.</p><p>Podatke obrađujemo radi pružanja usluge koju tražiš, zaštite i održavanja usluge te ispunjavanja primjenjivih zakonskih obaveza. Za dodatne namjene za koje je potrebna saglasnost, zatražit ćemo je zasebno.</p></section>
      <section id="servisi"><h2>Gdje odlaze video i zvuk?</h2><p>Spremljene medijske datoteke pohranjuju se u privatnu Cloudflare R2 pohranu. Trenutno je odabrana EU lokacija pohrane. Drugi korisnički računi nemaju pristup tvojim projektima kroz aplikaciju. Privremene poveznice za pristup snimku nemoj dijeliti ako ne želiš omogućiti pristup osobi koja ih dobije.</p><p>Za AI prepoznavanje govora, naraciju i promjenu glasa koristimo ElevenLabs. Pri pokretanju tih funkcija relevantni zvuk ili tekst šalje se tom servisu. EU lokacija medijske pohrane ne znači da se sva AI obrada odvija u EU.</p><p>Čuvanje podataka kod vanjskih pružalaca zavisi i od njihovih pravila i ugovorenih postavki. Ne obećavamo da AI servis odmah briše svaki poslani sadržaj. Više informacija: <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noreferrer">Cloudflare privatnost</a> i <a href="https://elevenlabs.io/privacy-policy" target="_blank" rel="noreferrer">ElevenLabs privatnost</a>.</p></section>
      <section id="cuvanje"><h2>Čuvanje i brisanje</h2><p>Spremljeni projekti ostaju dostupni za nastavak rada dok ih ne obrišeš ili dok ne riješimo tvoj zahtjev za brisanje. Brisanje projekta pokreće brisanje pripadajućih datoteka iz naše aktivne pohrane. To samo po sebi ne briše kopije koje si preuzeo, podatke u pregledniku niti podatke koje zasebno čuvaju vanjski AI servisi.</p><p>Preglednik može lokalno sačuvati postavke, nedavne projekte i kopije medija radi bržeg učitavanja. Možeš ih ukloniti brisanjem podataka stranice u pregledniku. Za brisanje računa ili dodatnih podataka pošalji nam zahtjev.</p></section>
      <section><h2>Kolačići i lokalna pohrana</h2><p>Koristimo funkcionalne podatke za prijavu, sigurnost i pamćenje postavki editora. U trenutnoj verziji Edite nisu uključeni oglašivački ni analitički alati za praćenje. Ako se to promijeni, ažurirat ćemo informacije i uvesti odgovarajuće kontrole saglasnosti.</p></section>
      <section id="prava"><h2>Tvoja prava i izbori</h2><p>Možeš nam se obratiti za pristup svojim podacima, ispravku, brisanje, ograničenje obrade ili prenos podataka, kao i uložiti prigovor, u skladu s primjenjivim propisima. Kada se obrada zasniva na saglasnosti, možeš je povući. Radi zaštite računa možemo tražiti potvrdu identiteta.</p><p>Ako smatraš da se tvoji podaci obrađuju nepravilno, možeš se obratiti nadležnom organu za zaštitu ličnih podataka.</p></section>
      <section><h2>Snimci drugih osoba</h2><p>Prije dodavanja snimka provjeri da imaš pravo koristiti ga i obrađivati glasove i podatke osoba koje se u njemu pojavljuju. Posebno vodi računa o privatnim razgovorima i osjetljivim podacima.</p></section>
    </article></div>
    <aside className="public-contact"><h2>Imaš pitanje o svojim podacima?</h2><p>Piši na <a href="mailto:info@gordondm.com">info@gordondm.com</a> ili pogledaj <Link to="/faq">česta pitanja o Editi</Link>.</p></aside>
  </main></PublicLayout>;
}
