import {AdminAnnouncements} from '../../components/AdminAnnouncements';
import {AdminCreateUser} from '../../components/AdminCreateUser';
import {StudioIcon} from '../../components/StudioIcon/StudioIcon';
import './AdminUsersPage.scss';
import {AdminUserControls,AdminEmails,AdminPayments} from '../../components/AdminUserControls';
import {ProductAnalyticsDashboard} from '../ProductAnalyticsDashboard';
import {AffiliateDashboard} from '../AffiliateDashboard';
import { ProviderUsage } from '../../components/ProviderUsage';
import { UserInsights } from '../../components/UserInsights';
import {AdminEditorFailures} from '../../components/AdminEditorFailures';
import {AdminCaptionPresets} from '../../components/AdminCaptionPresets';
import { BillingSelect } from '../../components/BillingSelect/BillingSelect';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useAuth } from '../../context/auth-context';
import { apiJson } from '../../lib/api';
import { dateLabel, entryLabel, type Entry, type Subscription } from '../../lib/billing';
import '../SubscriptionsPage/SubscriptionsPage.scss';
type User={id:number;username:string;name:string;email:string;accessApproved:boolean;isAdmin:boolean;isAffiliate:boolean;isActive:boolean;joined:string;subscription:Subscription};
type Dashboard={users:User[];total:number;page:number;stats:{users:number;active:number;used:number;pending:number;plans:Record<string,number>};requests:{id:number;user_id:number;user__username:string;plan:string}[]};
const plans=['free','affiliate','standard','advanced'];
const activationPlans=['free','standard','advanced'];
function UsersPanel(){
 const [creating,setCreating]=useState<'user'|'affiliate'|null>(null);
 const [created,setCreated]=useState('');
 const [controls,setControls]=useState<number|null>(null);
 const {session}=useAuth(); const [data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState(''),[page,setPage]=useState(1);
 const [selected,setSelected]=useState<{id:number;username:string;requestId?:number}|null>(null),[plan,setPlan]=useState('standard'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<Entry[]|null>(null),[historyName,setHistoryName]=useState('');
 const [paymentConfirmed,setPaymentConfirmed]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null); const operationId=useRef('');
 const load=useCallback(async()=>{const result=await apiJson<Dashboard>(`/api/admin/users?search=${encodeURIComponent(search)}&plan=${filter}&page=${page}`);setData(result);},[search,filter,page]);
 useEffect(()=>{if(!session.user?.isStaff)return;let live=true;const timer=setTimeout(()=>{apiJson<Dashboard>(`/api/admin/users?search=${encodeURIComponent(search)}&plan=${filter}&page=${page}`).then(result=>{if(live)setData(result);}).catch(e=>{if(live)setError(e.message);});},200);return()=>{live=false;clearTimeout(timer);};},[session.user,search,filter,page]);
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close();},[selected]);
 function open(user:{id:number;username:string;requestId?:number},plan:string){operationId.current=crypto.randomUUID();setSelected(user);setPlan(plan);setReason('');setPaymentConfirmed(false);setError('');}
 async function activate(){if(!selected)return;setBusy(true);setError('');try{await apiJson(`/api/admin/users/${selected.id}/plan`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan,reason,paymentConfirmed,requestId:selected.requestId,operationId:operationId.current})});setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:'Aktivacija nije uspjela.');}finally{setBusy(false);}}
 if(!session.user?.isStaff)return <main className="billing-workspace"><h1>Administracija</h1><p>Ovaj dio je dostupan samo administratorima.</p></main>;
 return <main className="billing-workspace"><span className="billing-eyebrow">EDITA ADMINISTRACIJA</span><h1>Korisnici i paketi</h1><div className="admin-create-actions"><button onClick={()=>setCreating('user')}>+ Kreiraj korisnika</button><button onClick={()=>setCreating('affiliate')}>+ Dodaj affiliatora</button></div>{created&&<p role="status">{created}</p>}{creating&&<AdminCreateUser affiliate={creating==='affiliate'} onClose={()=>setCreating(null)} onCreated={()=>{setCreated(creating==='affiliate'?'Affiliate račun je kreiran.':'Korisnik je kreiran.');void load().catch(()=>setError('Račun je kreiran, ali osvježavanje liste nije uspjelo.'));}}/>}{controls&&<AdminUserControls key={controls} userId={controls} onClose={()=>setControls(null)}/>} {error&&<p className="billing-error" role="alert">{error}</p>}{!data&&<p>Učitavanje…</p>}{data&&<>
 <div className="billing-stats"><div><small>Korisnici</small><strong>{data.stats.users}</strong></div><div><small>Aktivni računi</small><strong>{data.stats.active}</strong></div><div><small>Potrošeni tokeni ukupno</small><strong>{data.stats.used}</strong></div><div><small>Zahtjevi za paket</small><strong>{data.stats.pending}</strong></div></div>
 <div className="billing-toolbar">{plans.map(plan=><span key={plan}>{plan}: {data.stats.plans[plan]??0}</span>)}</div>
 {data.requests.length>0&&<><h2>Zahtjevi za pretplatu</h2><div className="billing-table-wrap"><table className="billing-table"><thead><tr><th>Korisnik</th><th>Željeni paket</th><th>Akcija</th></tr></thead><tbody>{data.requests.map(row=><tr key={row.id}><td>{row.user__username}</td><td>{row.plan}</td><td><button onClick={()=>open({id:row.user_id,username:row.user__username,requestId:row.id},row.plan)}>Pregledaj i aktiviraj</button></td></tr>)}</tbody></table></div></>}
 <h2>Pregled korisnika</h2><div className="billing-toolbar"><input placeholder="Pretraži korisnika ili email" aria-label="Pretraži korisnike" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><BillingSelect label="Paket" value={filter} onChange={value=>{setFilter(value);setPage(1);}} options={[{value:"",label:"Svi paketi"},...plans.map(value=>({value,label:value[0].toUpperCase()+value.slice(1)}))]}/><button onClick={()=>void load().catch(e=>setError(e.message))}>Osvježi</button></div>
 <div className="billing-table-wrap"><table className="billing-table admin-users-table"><thead><tr><th>Korisnik</th><th>Paket</th><th>Potrošeno</th><th>Preostalo</th><th>Važi do</th><th>Akcije</th></tr></thead><tbody>{data.users.map(user=><tr key={user.id}><td><strong>{user.name||user.username}</strong><br/>@{user.username}{user.isAdmin?' · Admin':user.isAffiliate?' · Affiliate':''}{!user.isActive?' · Neaktivan':''}{!user.accessApproved?' · Čeka odobrenje':''}</td><td>{user.isAffiliate?'Affiliate':user.subscription.plan}{user.subscription.status==='expired'?' · Istekao':''}</td><td>{user.subscription.unlimited?'Neograničeno':`${user.subscription.used} / ${user.subscription.allowance}`}</td><td>{user.subscription.unlimited?'∞':user.subscription.remaining}</td><td>{dateLabel(user.subscription.periodEnd)}</td><td className="admin-actions-cell"><div className="admin-user-actions"><button className="admin-icon-action" title="Tokeni i limiti" aria-label={`Tokeni i limiti za ${user.username}`} onClick={()=>setControls(user.id)}><StudioIcon name="settings"/></button> <button className="admin-role-action" aria-label={`Affiliate uloga za ${user.username}`} aria-pressed={user.isAffiliate} title={user.isAffiliate?'Ukloni affiliate ulogu':'Dodijeli affiliate ulogu'} disabled={busy} onClick={async()=>{setBusy(true);try{await apiJson(`/api/admin/users/${user.id}/affiliate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({affiliate:!user.isAffiliate})});await load();}catch{setError('Uloga nije promijenjena.');}finally{setBusy(false);}}}><StudioIcon name="spark"/></button> {!user.isAdmin&&<button className="admin-access-action" aria-label={`Pristup za ${user.username}`} aria-pressed={user.accessApproved} title={user.accessApproved?'Ima pristup · klikni za opoziv':'Bez pristupa · klikni za odobrenje'} disabled={busy} onClick={async()=>{setBusy(true);try{await apiJson(`/api/admin/users/${user.id}/access`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved:!user.accessApproved})});await load();}catch(e){setError(e instanceof Error?e.message:'Odobrenje nije uspjelo.');}finally{setBusy(false);}}}><StudioIcon name={user.accessApproved?"check":"close"}/></button>} <button className="admin-icon-action" title="Promijeni paket" aria-label={`Promijeni paket za ${user.username}`} onClick={()=>open(user,activationPlans.includes(user.subscription.plan)?user.subscription.plan:'standard')}><StudioIcon name="elements"/></button> <button className="admin-icon-action" title="Historija potrošnje" aria-label={`Historija potrošnje za ${user.username}`} onClick={()=>{setHistoryName(user.username);void apiJson<{entries:Entry[]}>(`/api/admin/users/${user.id}/history`).then(result=>setHistory(result.entries)).catch(e=>setError(e.message));}}><StudioIcon name="timelineShow"/></button></div></td></tr>)}</tbody></table></div>
 <div className="billing-toolbar admin-pagination" role="navigation" aria-label="Stranice rezultata"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Prethodna</button><span>{page} · {data.total} korisnika</span><button disabled={page*30>=data.total} onClick={()=>setPage(page+1)}>Sljedeća</button></div>
 {history&&<><h2>Historija · {historyName}</h2><div className="billing-table-wrap"><table className="billing-table"><thead><tr><th>Datum</th><th>Radnja</th><th>Tokeni</th><th>Preostalo</th><th>Administrator</th></tr></thead><tbody>{history.map(entry=><tr key={entry.id}><td>{dateLabel(entry.created_at)}</td><td>{entryLabel[entry.kind]} · {entry.detail}</td><td>{entry.amount}</td><td>{entry.balance_after}</td><td>{entry.actor__username||'Sistem'}</td></tr>)}</tbody></table></div></>}
 </>}
 <dialog ref={dialog} className="billing-modal" onCancel={event=>{event.preventDefault();if(!busy)setSelected(null);}}><h2>Paket za @{selected?.username}</h2><p>Ova radnja ne naplaćuje novac. Aktivira novi mjesečni period i zamjenjuje preostale tokene izabranim paketom. Free ne dodjeljuje ponovo početnih 5 tokena.</p><BillingSelect label="Paket" value={plan} disabled={Boolean(selected?.requestId)||busy} onChange={setPlan} options={(selected?.requestId&&!activationPlans.includes(plan)?[...activationPlans,plan]:activationPlans).map(value=>({value,label:value[0].toUpperCase()+value.slice(1)}))}/><label>Razlog aktivacije<input value={reason} maxLength={200} onChange={e=>setReason(e.target.value)} placeholder="Npr. potvrđena uplata ili testni pristup"/></label>{error&&<p role="alert">{error}</p>}{['standard','advanced','annual','loyalty'].includes(plan)&&<label><input type="checkbox" checked={paymentConfirmed} onChange={e=>setPaymentConfirmed(e.target.checked)}/>Potvrđujem primljenu uplatu — aktiviraj plaćeni pristup</label>}<footer><button disabled={busy||reason.trim().length<3} onClick={()=>void activate()}>{busy?'Aktiviranje…':'Potvrdi aktivaciju'}</button><button disabled={busy} onClick={()=>setSelected(null)}>Odustani</button></footer></dialog>
 </main>;
}

function ResourcesPanel(){
 const {session}=useAuth();
 const [resources,setResources]=useState<{checkedAt:string;elevenlabs:{available:boolean;error?:string;used?:number;remaining?:number;limit?:number;resetAt?:number};storage:{available:boolean;error?:string;provider:string;bytes?:number;trackedBytes:number;partial?:boolean;objects?:number}}|null>(null);
 const [resourcesBusy,setResourcesBusy]=useState(true),[resourcesError,setResourcesError]=useState(''),[resourcesRefresh,setResourcesRefresh]=useState(0);
 useEffect(()=>{if(!session.user?.isStaff)return;let live=true;apiJson<NonNullable<typeof resources>>(`/api/admin/resources${resourcesRefresh?'?refresh=1':''}`).then(v=>{if(live)setResources(v);}).catch(()=>{if(live)setResourcesError('Stanje servisa nije učitano. Pokušaj ponovo.');}).finally(()=>{if(live)setResourcesBusy(false);});return()=>{live=false;};},[session.user,resourcesRefresh]);
 return <section> <div className="billing-toolbar admin-section-header"><h2>Servisi i pohrana</h2><button disabled={resourcesBusy} onClick={()=>{setResourcesBusy(true);setResourcesError('');setResourcesRefresh(v=>v+1);}}>{resourcesBusy?'Učitavanje…':'Osvježi stanje servisa'}</button></div>
 {resourcesError&&<p role="alert">{resourcesError}</p>}
 <div className="billing-stats" aria-busy={resourcesBusy}><div><small>ElevenLabs · preostali krediti</small><strong>{resources?.elevenlabs.available?resources.elevenlabs.remaining?.toLocaleString('bs-BA'):resourcesBusy?'Učitavanje…':'Nedostupno'}</strong>{resources?.elevenlabs.available?<p>Potrošeno {resources.elevenlabs.used?.toLocaleString('bs-BA')} od {resources.elevenlabs.limit?.toLocaleString('bs-BA')}{resources.elevenlabs.resetAt?` · Obnova ${new Date(resources.elevenlabs.resetAt*1000).toLocaleDateString('bs-BA')}`:''}</p>:!resourcesBusy&&<p>{resources?.elevenlabs.error}</p>}</div><div><small>Cloudflare R2 · zauzeta pohrana</small><strong>{resources?.storage.available?`${resources.storage.partial?'Najmanje ':''}${((resources.storage.bytes||0)/1e9).toFixed(2)} GB`:resourcesBusy?'Učitavanje…':'Nedostupno'}</strong><p>{resources?.storage.available?`${resources.storage.objects} datoteka · Ukupni limit prostora nije postavljen.`:!resourcesBusy?resources?.storage.error:''}</p></div></div>
 <p>{resources?.checkedAt&&`Zadnja provjera: ${new Date(resources.checkedAt).toLocaleTimeString('bs-BA')}. `}Dugme osvježava stanje direktno kod servisa. R2 prikazuje zauzet prostor, ne novčani saldo ni konačan mjesečni račun. <a href="https://developers.cloudflare.com/r2/pricing/" target="_blank" rel="noreferrer">R2 obračun</a></p>
<ProviderUsage admin/></section>;
}
export function AdminUsersPage(){
 const {session}=useAuth();const [tab,setTab]=useState('users');
 if(!session.user?.isStaff)return <main className="billing-workspace">Samo za administratore.</main>;
 return <main className="billing-workspace admin-organized"><h1>Administracija</h1><nav className="admin-tabs" aria-label="Administracija">{Object.entries({users:'Korisnici',announcements:'Obavijesti',errors:'Greške',usage:'Potrošnja',stats:'Statistike i stilovi',affiliates:'Affiliatori',feedback:'Feedback',email:'Emailovi',payments:'Plaćanja',styles:'Predlošci'}).map(([key,name])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{name}</button>)}</nav>{tab==='users'&&<UsersPanel/>}{tab==='announcements'&&<AdminAnnouncements/>}{tab==='errors'&&<AdminEditorFailures/>}{tab==='usage'&&<ResourcesPanel/>}{tab==='stats'&&<ProductAnalyticsDashboard/>}{tab==='affiliates'&&<AffiliateDashboard/>}{tab==='feedback'&&<UserInsights admin/>}{tab==='email'&&<AdminEmails/>}{tab==='payments'&&<AdminPayments/>}{tab==='styles'&&<AdminCaptionPresets/>}</main>;
}
