# Generated by Django 5.2.17 on 2026-09-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_initial_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenentry',
            name='reference',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
