# Generated by Django 5.2.17 on 2026-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_accessapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMediaDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('backend', models.CharField(max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(auto_now_add=True)),
                ('last_error', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('backend', 'name'), name='unique_pending_media_deletion')],
            },
        ),
    ]
