# Generated by Django 5.2.17 on 2026-09-17 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_affiliatesettings_affiliateprofile_referral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipartMediaUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('key', models.CharField(max_length=500)),
                ('upload_id', models.TextField()),
                ('parts', models.JSONField(default=dict)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.project')),
            ],
        ),
    ]
