# Generated by Django 5.2.17 on 2026-09-23 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_subscription_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('style', models.CharField(max_length=40)),
                ('settings', models.JSONField(default=dict)),
                ('portrait', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('private', 'Private'), ('proposed', 'Proposed'), ('published', 'Published'), ('rejected', 'Rejected')], default='private', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
