# Generated by Django 5.2.17 on 2026-10-07 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_editorfailure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='campaign',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='referral',
            name='link_slug',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='AffiliateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit', to='studio.affiliateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=40, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='studio.affiliateprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('affiliate',), name='one_primary_affiliate_link')],
            },
        ),
        migrations.CreateModel(
            name='AffiliateVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.UUIDField()),
                ('campaign', models.CharField(blank=True, max_length=48)),
                ('link_slug', models.CharField(blank=True, max_length=40)),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_events', to='studio.affiliateprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('affiliate', 'visitor', 'campaign', 'day'), name='affiliate_visit_daily_unique')],
            },
        ),
    ]
