# Generated by Django 5.2.17 on 2026-10-07 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_referral_campaign_referral_link_slug_affiliateaudit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor', models.UUIDField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('page', models.CharField(max_length=24)),
                ('section', models.CharField(blank=True, max_length=24)),
                ('style', models.CharField(blank=True, db_index=True, max_length=80)),
                ('campaign', models.CharField(blank=True, max_length=48)),
                ('affiliate_id_value', models.PositiveBigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
