# Generated by Django 5.2.17 on 2026-10-07 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_productevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateaudit',
            name='changes',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='AffiliateCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('campaign', models.CharField(blank=True, max_length=48)),
                ('metric', models.CharField(choices=[('visits', 'Visits'), ('registrations', 'Registrations'), ('purchases', 'Purchases')], max_length=16)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='studio.affiliateprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
