# Generated by Django 5.2.17 on 2026-10-07 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_userfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=24)),
                ('action', models.CharField(max_length=40)),
                ('operation_key', models.UUIDField(null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('http_status', models.PositiveSmallIntegerField(null=True)),
                ('input_chars', models.PositiveIntegerField(default=0)),
                ('input_seconds', models.FloatField(default=0)),
                ('input_bytes', models.PositiveBigIntegerField(default=0)),
                ('output_bytes', models.PositiveBigIntegerField(default=0)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_test', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'created_at'], name='studio_prov_provide_4da480_idx')],
            },
        ),
    ]
