# Generated by Django 5.2.17 on 2026-10-07 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_providerusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.UUIDField()),
                ('tab', models.UUIDField()),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('page', models.CharField(default='other', max_length=24)),
                ('section', models.CharField(blank=True, max_length=24)),
                ('source', models.CharField(default='direct', max_length=24)),
                ('campaign', models.CharField(blank=True, max_length=48)),
                ('visible', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('is_test', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(db_index=True)),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.affiliateprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('visitor', 'tab'), name='unique_presence_tab')],
            },
        ),
    ]
