# Generated by Django 5.2.17 on 2026-10-07 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0018_visitorpresence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('event_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100, null=True, unique=True)),
                ('subscription_id', models.CharField(max_length=100, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('checkout_key', models.UUIDField(default=uuid.uuid4)),
                ('checkout_id', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripeInvoice',
            fields=[
                ('invoice_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subscription_id', models.CharField(max_length=100)),
                ('amount_paid', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio.stripeaccount')),
            ],
        ),
    ]
