# Generated by Django 5.2.17 on 2026-10-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_affiliaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliaterequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='affiliaterequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='affiliaterequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='affiliaterequest',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
