# Generated by Django 5.2.17 on 2026-10-07 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0022_affiliateprofile_discount_percent_accountemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprofile',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AffiliateDemoDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('visits', models.PositiveIntegerField(default=0)),
                ('registrations', models.PositiveIntegerField(default=0)),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.affiliateprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('affiliate', 'day'), name='unique_affiliate_demo_day')],
            },
        ),
    ]
