import {AffiliateCoupons} from '../components/AccountTools';
import {useAuth} from '../context/auth-context';
import {AffiliateRequests} from '../components/AffiliateRequests';
import {LivePresence} from '../components/LivePresence';
import {AffiliateReview} from '../components/AffiliateReview';
import {useEffect,useState} from 'react';
import {useParams,Link} from 'react-router-dom';
import {apiJson} from '../lib/api';
import '../pages/SubscriptionsPage/SubscriptionsPage.scss';
import './AffiliatePortal.scss';
type Point={date:string;visits:number;registrations:number;purchases:number};
type Data={demo?:boolean;userId:number;name:string;active:boolean;eligible:boolean;path:string;days:number;historicalVisits:number;totals:{visits:number;visitors:number;registrations:number;purchases:number};series:Point[];links:{slug:string;is_primary:boolean}[];campaigns:{campaign:string;visits:number;registrations:number}[];rawTotals?:Record<string,number>;audit?:{at:string;actor:string;action:string;detail:string;changes:Record<string,string|number>}[]};
export function AffiliatePortal(){
 const {userId}=useParams(); const [active,setActive]=useState(false),[tab,setTab]=useState<'overview'|'tokens'>('overview');
 return <div className={`affiliate-page${active||userId?' is-member':''}`}>
 {active&&!userId&&<nav className="affiliate-tabs" aria-label="Affiliate pregled"><button aria-pressed={tab==='overview'} onClick={()=>setTab('overview')}>Pregled i moj link</button><button aria-pressed={tab==='tokens'} onClick={()=>setTab('tokens')}>Tokeni i zahtjevi</button></nav>}
 {!userId&&<div hidden={active&&tab!=='tokens'}><AffiliateRequests onStatus={setActive}/></div>}
 {(userId||(active&&tab==='overview'))&&<AffiliateStatistics/>}
 </div>;
}
function AffiliateStatistics(){
 const {session}=useAuth();
 const adminView=!!session.user?.isStaff;
 const {userId}=useParams(),[days,setDays]=useState('30'),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[slug,setSlug]=useState(''),[campaign,setCampaign]=useState(''),[notice,setNotice]=useState('');
 const endpoint=userId?'/api/admin/affiliates/'+userId+'/dashboard':'/api/affiliate/dashboard';
 useEffect(()=>{let live=true;setBusy(true);setError('');setData(null);void apiJson<Data>(endpoint+'?days='+days).then(value=>{if(live){setData(value);setSlug(value.links.find(l=>l.is_primary)?.slug||'');}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setBusy(false);});return()=>{live=false;};},[endpoint,days,reload]);
 const link=data?window.location.origin+data.path+(campaign?'?campaign='+encodeURIComponent(campaign):''):'';
 const [presenceOpen,setPresenceOpen]=useState(false);
 const [metric,setMetric]=useState<'visits'|'registrations'|'purchases'>('visits');
 const max=Math.max(1,...(data?.series.map(p=>p[metric])||[]));
 return <main className="billing-workspace affiliate-portal"><span className="billing-eyebrow">EDITA PARTNERI</span><h1>{userId?'Affiliate pregled':'Moj affiliate'}</h1>{userId&&<Link to="/studio/affiliates">← Svi affiliatori</Link>}<div className="billing-toolbar"><label>Period <select value={days} onChange={e=>setDays(e.target.value)}>{[7,30,90].map(n=><option key={n} value={n}>{n} dana</option>)}</select></label><button disabled={busy} onClick={()=>setReload(v=>v+1)}>Osvježi</button></div>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">Učitavanje…</p>}{data&&<>{data.demo&&<p className="billing-notice">DEMO · Ovo su izmišljeni podaci testnog računa, ne stvarne posjete ili kupovine.</p>}<p className="affiliate-owner">{data.name}</p>{!data.eligible&&<p role="status">Link trenutno nije aktivan. Potreban je odobren i aktivan affiliate status.</p>}<div className="billing-stats">{Object.entries(data.totals).filter(([key])=>adminView||key!=='visitors').map(([key,value])=><div key={key}><small>{{visits:'Posjete preko linka',visitors:'Preglednici',registrations:'Registracije',purchases:'Kupovine'}[key]}</small><strong>{value}</strong></div>)}</div>
 <section className="affiliate-card"><h2>Tvoj link</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{const next=await apiJson<Data>(endpoint+'?days='+days,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug})});setData(next);setSlug(next.links.find(l=>l.is_primary)?.slug||'');setNotice('Link je sačuvan. Raniji linkovi i dalje rade.');}catch(e){setError(e instanceof Error?e.message:'Spremanje nije uspjelo.');}finally{setBusy(false);}}}><label>Naziv linka<input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="gogi" minLength={3} maxLength={40} required pattern="[a-zA-Z0-9][a-zA-Z0-9-]{1,38}[a-zA-Z0-9]"/></label><button disabled={busy}>Spremi naziv</button></form><label>Kampanja — opciono<input value={campaign} placeholder="instagram-oktobar" maxLength={48} onChange={e=>setCampaign(e.target.value.replace(/[^a-zA-Z0-9_-]/g,''))}/></label><div className="affiliate-copy"><input aria-label="Link za dijeljenje" readOnly value={link}/><button onClick={()=>void navigator.clipboard.writeText(link).then(()=>setNotice('Link kopiran.')).catch(()=>setNotice('Označi link i kopiraj ga ručno.'))}>Kopiraj</button></div><p role="status">{notice}</p>{data.links.length>1&&<details><summary>Raniji linkovi</summary>{data.links.filter(l=>!l.is_primary).map(l=><p key={l.slug}>/{l.slug}</p>)}</details>}</section>
 {!userId&&<AffiliateCoupons/>}
 {data.series.some(p=>p.visits||p.registrations||p.purchases)&&<section className="affiliate-card"><h2>Rezultati po danima</h2><div className="billing-toolbar">{(['visits','registrations','purchases'] as const).map(key=><button key={key} aria-pressed={metric===key} onClick={()=>setMetric(key)}>{{visits:'Dolasci',registrations:'Registracije',purchases:'Kupovine'}[key]}</button>)}</div>{data.series.some(p=>p[metric]>0)?<div className="affiliate-chart" role="img" aria-label="Dnevni rezultati; tačne vrijednosti su u tabeli ispod">{data.series.map(p=><div key={p.date} title={p.date+': '+p[metric]}><span style={{height:(p[metric]/max*100)+'%'}}/></div>)}</div>:<p>Još nema rezultata za odabranu metriku u ovom periodu.</p>}<p>{data.series[0]?.date} — {data.series.at(-1)?.date} · najviše {max===1&&!data.series.some(p=>p[metric])?0:max} u danu</p><details><summary>Prikaži tačne dnevne vrijednosti</summary><div className="billing-table-wrap"><table className="billing-table"><thead><tr><th>Datum</th><th>Dolasci</th><th>Registracije</th><th>Kupovine</th></tr></thead><tbody>{data.series.map(p=><tr key={p.date}><td>{p.date}</td><td>{p.visits}</td><td>{p.registrations}</td><td>{p.purchases}</td></tr>)}</tbody></table></div></details></section>}
 {adminView&&<details className="affiliate-card" onToggle={event=>setPresenceOpen(event.currentTarget.open)}><summary>Aktivnost uživo</summary>{presenceOpen&&<LivePresence affiliateUser={userId}/>}</details>}
 {adminView&&<section className="affiliate-card"><h2>Kampanje</h2>{data.campaigns.length?<div className="billing-table-wrap"><table className="billing-table"><thead><tr><th>Kampanja</th><th>Dolasci</th><th>Registracije</th></tr></thead><tbody>{data.campaigns.map(c=><tr key={c.campaign}><td>{c.campaign||'Bez oznake'}</td><td>{c.visits}</td><td>{c.registrations}</td></tr>)}</tbody></table></div>:<p>Još nema zabilježenih kampanja u ovom periodu.</p>}</section>}
 {adminView?<details className="affiliate-method"><summary>Kako se broje rezultati?</summary><p>Jedan preglednik broji se jednom po kampanji i danu. To nije provjeren broj ljudi. Prva važeća preporuka dobija registraciju. Vlastiti dolasci prijavljenih korisnika se ne broje. Grafikoni prikazuju događaje od uvođenja novog praćenja; stari zbirni brojač ({data.historicalVisits}) ne pretvaramo u dnevnu historiju. Prikazani rezultati uključuju odobrene provjere. Program ne obračunava nagrade.</p></details>:<p className="affiliate-method">Rezultati su za odabrani period. Posjete se broje jednom po pregledniku, kampanji i danu.</p>}
 {userId&&data.audit&&<><AffiliateReview userId={userId} onChanged={()=>setReload(v=>v+1)}/><details><summary>Izvorno zabilježeni rezultati (samo administratori)</summary><p>{Object.entries(data.rawTotals||{}).map(([key,value])=>`${key}: ${value}`).join(' · ')}</p></details><details><summary>Interna historija promjena</summary>{data.audit.map((a,i)=><div key={i}><p>{new Date(a.at).toLocaleString()} · {a.actor} · {a.action==='link_changed'?'Promjena linka':a.action==='correction_created'?'Predložena korekcija':a.action==='status_changed'?'Promjena affiliate statusa':'Odluka o korekciji'} · {a.detail}</p>{Object.entries(a.changes).map(([key,value])=><span key={key}>{key}: {String(value)} · </span>)}</div>)}</details></>}</>}</main>;
}
