import {useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {ProjectTree,useSelection} from '../components/ProductionWorkspace';
import {LocalDialog,localConfirm} from '../components/LocalDialog';
import {CreativeTutorial} from '../components/CreativeTutorial';
import {WorkflowSteps} from '../components/WorkflowSteps';
import {ActionIcon,SelectField} from '../components/CreativeControls';
import {apiJson,apiFetch} from '../lib/api';
import {downloadBlob,jsonBody,type Script,type Interval} from '../lib/production';
import {useLocalSave} from '../lib/use-local-save';
export function LocalScripts(){const w=useSelection();return <><div className="production-heading"><div><h1>Skripte i naracije</h1><p>Napiši tekst, podijeli naraciju i odredi trajanje kadrova.</p></div></div>{w.script?<ScriptEditor key={w.script.id} script={w.script}/>:<div className="production-workspace"><ProjectTree/><div className="production-empty"><h2>Dodaj skriptu</h2><p>Odaberi projekat i unesi naziv skripte.</p></div></div>}</>;}
function ScriptEditor({script}:{script:Script}){
 const w=useSelection();const [chapter,setChapter]=useState(script.chapter||''),[title,setTitle]=useState(script.title),[content,setContent]=useState(script.content),[segments,setSegments]=useState(script.segments),[tab,setTab]=useState('text'),[message,setMessage]=useState(''),[aiOpen,setAiOpen]=useState(false),[direction,setDirection]=useState(''),[aiBusy,setAiBusy]=useState(false),[tutorial,setTutorial]=useState(false);
 const cursors=useRef<Record<string,number>>({});
 const saved=useLocalSave({title,content,segments,chapter:chapter||null},async data=>{const result=await apiJson<Script>(`/api/scripts/${script.id}`,jsonBody(data,'PATCH'));w.putScript(result);});
 const round=(n:number)=>Math.round(n*10)/10;
 const patch=(id:string,values:Partial<Interval>)=>setSegments(items=>items.map(s=>s.id===id?{...s,...values}:s));
 function insert(index:number,duplicate=false){setSegments(items=>{const prior=items[index-1],start=prior?.end||0,duration=duplicate&&prior?round(prior.end-prior.start):3;const next={id:crypto.randomUUID(),start,end:round(start+duration),text:duplicate?prior?.text||'':'',prompt:duplicate?prior?.prompt||'':''};return [...items.slice(0,index),next,...items.slice(index).map(s=>({...s,start:round(s.start+duration),end:round(s.end+duration)}))];});}
 function splitOne(index:number){setSegments(items=>{const s=items[index];if(!s||s.text.trim().length<2||s.end-s.start<.2)return items;let at=cursors.current[s.id]||Math.floor(s.text.length/2);if(at<=0||at>=s.text.length)at=Math.floor(s.text.length/2);const space=s.text.indexOf(' ',at);if(space>0&&space<s.text.length-1)at=space;const middle=round(Math.max(s.start+.1,Math.min(s.end-.1,s.start+(s.end-s.start)*at/s.text.length)));return [...items.slice(0,index),{...s,end:middle,text:s.text.slice(0,at).trim()},{...s,id:crypto.randomUUID(),start:middle,text:s.text.slice(at).trim(),prompt:''},...items.slice(index+1)];});}
 function merge(index:number){setSegments(items=>{const a=items[index],b=items[index+1];if(!b)return items;return [...items.slice(0,index),{...a,end:b.end,text:a.text+' '+b.text},...items.slice(index+2)];});}
 function timing(index:number,edge:'start'|'end',value:number){setSegments(items=>{const current=items[index];if(!Number.isFinite(value))return items;if(edge==='start'){return items.map((s,i)=>i===index?{...s,start:round(Math.max(items[index-1]?.end||0,Math.min(current.end-.1,value)))}:s);}const end=round(Math.max(current.start+.1,value)),delta=end-current.end;return items.map((s,i)=>i===index?{...s,end}:i>index?{...s,start:round(s.start+delta),end:round(s.end+delta)}:s);});}
 async function split(){if(segments.length&&!await localConfirm('Zamijeniti postojeću podjelu naracije?','Nova podjela naracije','Zamijeni'))return;let start=0;setSegments((content.match(/[^.!?\n]+[.!?]?/g)||[]).map(text=>{const duration=Math.max(2,Math.ceil(text.trim().split(/\s+/).length/2.5));const item={id:crypto.randomUUID(),start,end:start+duration,text:text.trim(),prompt:''};start+=duration;return item;}));setTab('intervals');}
 return <div className="production-workspace"><ProjectTree beforeSelect={saved.save}/><section className="production-panel script-panel"><WorkflowSteps project={script.project} script={script.id}/><div className="script-toolbar"><div className="production-tabs"><button aria-pressed={tab==='text'} onClick={()=>setTab('text')}>Tekst skripte</button><button aria-pressed={tab==='intervals'} onClick={()=>setTab('intervals')}>Prilagodba naracije <small>{segments.length}</small></button></div><div className="save-control"><span role="status">{saved.status}</span><button className="klipanje-primary" disabled={saved.busy||!title.trim()} onClick={()=>void saved.save()}>{saved.busy?'Spremanje…':'Spremi skriptu'}</button></div></div><div className="script-name-chapter"><label>Naziv skripte<input maxLength={160} value={title} placeholder="Epizoda 1" onChange={e=>setTitle(e.target.value)}/></label><SelectField label="Odaberi chapter" value={chapter} onChange={setChapter} options={[["","Bez chaptera"],...w.chapters.filter(c=>c.project===script.project).map(c=>[c.id,c.title])]}/><button onClick={async()=>{if(await saved.save())w.createChapter(script.project);}}><ActionIcon name="plus"/>Dodaj chapter</button></div>
 {tab==='text'?<><div className="script-ai-actions"><button onClick={()=>{setMessage('');setAiOpen(true);}}>AI prijedlog skripte</button><button onClick={()=>setTutorial(true)}>Pravila i upute</button></div><label>Tekst<textarea className="production-script-text" value={content} maxLength={100000} onChange={e=>setContent(e.target.value)} placeholder="Unesi tekst skripte…"/></label><div className="production-row"><span className="production-muted">{content.trim().split(/\s+/).filter(Boolean).length} riječi</span><button disabled={!content.trim()} onClick={split}>Podijeli u intervale</button><button onClick={()=>downloadBlob(new Blob([content],{type:'text/plain;charset=utf-8'}),title+'.txt')}>Preuzmi TXT</button></div></>:<><div className="script-toolbar"><small>Vrijeme u sekundama · podjela na mjestu kursora</small><button onClick={()=>insert(0)}><ActionIcon name="plus"/>Dodaj na početak</button></div><div className="narration-rows">{segments.map((s,i)=><article className="narration-row" key={s.id}><span className="row-number">{String(i+1).padStart(2,'0')}</span><textarea aria-label={`Naracija ${i+1}`} rows={2} maxLength={10000} value={s.text} onSelect={e=>{cursors.current[s.id]=e.currentTarget.selectionStart;}} onChange={e=>patch(s.id,{text:e.target.value})}/><div className="interval-clock"><label>Od<input aria-label={`Početak intervala ${i+1}`} type="number" min="0" step="0.1" value={s.start} onChange={e=>timing(i,'start',Number(e.target.value))}/></label><label>Do<input aria-label={`Kraj intervala ${i+1}`} type="number" min="0.1" step="0.1" value={s.end} onChange={e=>timing(i,'end',Number(e.target.value))}/></label></div><div className="interval-actions"><button title="Podijeli na mjestu kursora" onClick={()=>splitOne(i)}><ActionIcon name="split"/></button><button title="Dupliciraj interval" onClick={()=>insert(i+1,true)}><ActionIcon name="copy"/></button><button title="Spoji sa sljedećim" disabled={i===segments.length-1} onClick={()=>merge(i)}><ActionIcon name="merge"/></button><button title="Dodaj interval ispod" onClick={()=>insert(i+1)}><ActionIcon name="plus"/></button><button title="Obriši interval" onClick={()=>setSegments(items=>items.filter(item=>item.id!==s.id))}><ActionIcon name="trash"/></button></div></article>)}</div><div className="production-row"><button onClick={()=>insert(segments.length)}><ActionIcon name="plus"/>Dodaj interval</button><button disabled={!content.trim()} onClick={split}>Podijeli tekst ponovo</button></div></>}
 <div className="production-bottom"><span role="status">{saved.status}</span><Link className="klipanje-secondary" to={`/fotografije?project=${script.project}&script=${script.id}`}>Nastavi na fotografije →</Link></div>{message&&<p role="alert">{message}</p>}<button className="production-delete" disabled={saved.busy} onClick={async()=>{if(!await localConfirm(`Obrisati skriptu „${title}”?`,'Obriši skriptu','Obriši',true))return;try{const r=await apiFetch(`/api/scripts/${script.id}`,{method:'DELETE'});if(!r.ok)throw new Error('Brisanje nije uspjelo.');await w.reload();w.select(script.project);}catch(e){setMessage((e as Error).message);}}}><ActionIcon name="trash"/>Obriši skriptu</button>{tutorial&&<CreativeTutorial onClose={()=>setTutorial(false)}/>} {aiOpen&&<LocalDialog title="AI prijedlog skripte" busy={aiBusy} onClose={()=>setAiOpen(false)}><p>Koristi spremljena pravila i likove projekta.</p>{message&&<p role="alert">{message}</p>}<label>Upute za ovu epizodu<textarea rows={5} maxLength={6000} value={direction} onChange={e=>setDirection(e.target.value)} placeholder="Šta se dešava u ovoj epizodi, dužina i ton…"/></label><div className="local-dialog-actions"><button disabled={aiBusy} className="klipanje-primary" onClick={async()=>{if(!direction.trim()||!await saved.save())return;if(content.trim()&&!await localConfirm('Zamijeniti tekst skripte AI prijedlogom? Intervali ostaju dok ih ponovo podijeliš.','Zamijeni tekst','Generiši'))return;setAiBusy(true);try{const r=await apiJson<{text:string}>('/api/creative/script',jsonBody({script:script.id,direction}));setContent(r.text);setAiOpen(false);setMessage('AI prijedlog je unesen. Pregledaj tekst i podijeli ga u intervale.');}catch(e){setMessage((e as Error).message);}finally{setAiBusy(false);}}}>{aiBusy?'Generisanje…':'Generiši skriptu'}</button></div></LocalDialog>}</section></div>;
}
