import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ProjectTree,useSelection} from '../components/ProductionWorkspace';
import {apiJson,apiFetch} from '../lib/api';
import {downloadBlob,jsonBody,type Script,type Interval} from '../lib/production';
import {useUnsaved} from '../lib/use-unsaved';
export function LocalScripts(){const w=useSelection();return <><div className="production-heading"><div><p className="klipanje-eyebrow">01 / SKRIPTA</p><h1>Oblikuj svoju priču.</h1><p>Tekst, naracija i ritam budućeg videa.</p></div></div>{w.script?<ScriptEditor key={w.script.id} script={w.script}/>:<div className="production-workspace"><ProjectTree/><div className="production-empty"><h2>Dodaj skriptu u projekat.</h2><p>Ovdje počinje tvoj sljedeći video.</p></div></div>}</>;}
function ScriptEditor({script}:{script:Script}){
 const w=useSelection();const [title,setTitle]=useState(script.title),[content,setContent]=useState(script.content),[segments,setSegments]=useState(script.segments),[tab,setTab]=useState('text'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const dirty=title!==script.title||content!==script.content||JSON.stringify(segments)!==JSON.stringify(script.segments);const mayLeave=useUnsaved(dirty);
 const patch=(id:string,values:Partial<Interval>)=>setSegments(items=>items.map(s=>s.id===id?{...s,...values}:s));
 async function save(){setBusy(true);setMessage('');try{const saved=await apiJson<Script>(`/api/scripts/${script.id}`,jsonBody({title,content,segments},'PATCH'));w.putScript(saved);setMessage('Spremljeno lokalno.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function split(){if(segments.length&&!confirm('Zamijeniti postojeće intervale? Njihovi pojedinačni promptovi i veze na fotografije neće se prenijeti.'))return;let start=0;setSegments((content.match(/[^.!?\n]+[.!?]?/g)||[]).map(text=>{const duration=Math.max(2,Math.ceil(text.trim().split(/\s+/).length/2.5));const item={id:crypto.randomUUID(),start,end:start+duration,text:text.trim(),prompt:''};start+=duration;return item;}));setTab('intervals');}
 return <div className="production-workspace"><ProjectTree beforeSelect={mayLeave}/><section className="production-panel"><div className="production-heading compact"><div className="production-tabs"><button aria-pressed={tab==='text'} onClick={()=>setTab('text')}>Tekst skripte</button><button aria-pressed={tab==='intervals'} onClick={()=>setTab('intervals')}>Prilagodba naracije <small>{segments.length}</small></button></div><button className="klipanje-primary" disabled={busy||!title.trim()} onClick={()=>void save()}>{busy?'Spremanje…':'Spremi skriptu'}</button></div><label>Naziv skripte<input className="production-title-input" maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label>
 {tab==='text'?<><label>Tekst<textarea className="production-script-text" value={content} maxLength={100000} onChange={e=>setContent(e.target.value)} placeholder="Napiši prvu rečenicu…"/></label><div className="production-row"><span className="production-muted">{content.trim().split(/\s+/).filter(Boolean).length} riječi</span><button disabled={!content.trim()} onClick={split}>Podijeli po rečenicama →</button><button onClick={()=>downloadBlob(new Blob([content],{type:'text/plain;charset=utf-8'}),title+'.txt')}>Preuzmi TXT</button></div></>:<><p className="production-muted">Vrijeme je u sekundama. Intervali određuju naraciju, fotografije i titlove. Automatska podjela procjenjuje trajanje; prilagodi ga snimljenom glasu.</p><div className="production-intervals">{segments.map((s,i)=><article key={s.id}><header><strong>{String(i+1).padStart(2,'0')}</strong><label>Od (s)<input aria-label={`Početak intervala ${i+1}`} type="number" min="0" step="0.1" value={s.start} onChange={e=>patch(s.id,{start:Number(e.target.value)})}/></label><span>→</span><label>Do (s)<input aria-label={`Kraj intervala ${i+1}`} type="number" min="0.1" step="0.1" value={s.end} onChange={e=>patch(s.id,{end:Number(e.target.value)})}/></label><button title="Ukloni interval" onClick={()=>{if(confirm('Ukloniti interval? Fotografije ostaju u galeriji.'))setSegments(list=>list.filter(item=>item.id!==s.id));}}>×</button></header><label>Naracija<textarea rows={3} maxLength={10000} value={s.text} onChange={e=>patch(s.id,{text:e.target.value})}/></label></article>)}</div><div className="production-row"><button onClick={()=>{const start=segments.at(-1)?.end||0;setSegments([...segments,{id:crypto.randomUUID(),start,end:start+5,text:'',prompt:''}]);}}>+ Dodaj interval</button><button disabled={!content.trim()} onClick={split}>Podijeli tekst ponovo</button></div></>}
 <div className="production-bottom"><span>{dirty?'Nespremljene izmjene':'Sve izmjene spremljene'}</span><Link className="klipanje-secondary" to={`/fotografije?project=${script.project}&script=${script.id}`}>Nastavi na fotografije →</Link></div>{message&&<p role="status">{message}</p>}<button className="production-delete" disabled={busy} onClick={async()=>{if(!confirm(`Obrisati skriptu „${title}”?`))return;setBusy(true);try{const r=await apiFetch(`/api/scripts/${script.id}`,{method:'DELETE'});if(!r.ok)throw new Error('Brisanje nije uspjelo.');await w.reload();w.select(script.project);}catch(e){setMessage((e as Error).message);setBusy(false);}}}>Obriši skriptu</button></section></div>;
}
