import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ProjectTree,useSelection,useAssets,Icon} from '../components/ProductionWorkspace';
import {WorkflowSteps} from '../components/WorkflowSteps';
import {SelectField,FormatPicker,VisualStylePicker,ActionIcon} from '../components/CreativeControls';
import {LocalDialog,localConfirm} from '../components/LocalDialog';
import {CreativeTutorial} from '../components/CreativeTutorial';
import {apiJson,apiFetch} from '../lib/api';
import {jsonBody,uploadAsset,downloadBlob,type Script,type Asset,type PhotoPrompt} from '../lib/production';
import {useLocalSave} from '../lib/use-local-save';
import {buildPhotoPlan} from '../lib/photo-plan';
import {imageOutputEstimate} from '../lib/image-estimate';
const models=[['gpt-image-2.5-flare','GPT Image 2.5 Flare'],['gpt-image-2.5-sunburst','GPT Image 2.5 Sunburst']];
const descriptions={'gpt-image-2.5-flare':'Brzo generisanje novih kadrova i svakodnevnih fotografija.','gpt-image-2.5-sunburst':'Precizne izmjene i rad s referencama likova i detaljnim scenama.'};
export function Photos(){const w=useSelection();return <><div className="production-heading"><div><h1>Fotografije</h1><p>Odaberi kadrove, fotografije i promptove.</p></div></div>{w.script&&w.project?<PhotoWorkspace key={w.script.id} script={w.script}/>:<div className="production-workspace photo-workspace"><ProjectTree photos/><div className="production-empty"><h2>Odaberi projekat i skriptu</h2></div></div>}</>;}
function PhotoWorkspace({script}:{script:Script}){
 const w=useSelection(),project=w.project!,{assets,setAssets,error:assetError}=useAssets(project.id);
 const active=script.segments.find(s=>s.id===w.params.get('segment'));
 const frames=[{id:'overall',start:0,end:0,text:script.content},...script.segments];
 const [overall,setOverall]=useState(script.image_prompt),[prompts,setPrompts]=useState<PhotoPrompt[]>(()=>script.photo_settings.generationPrompts||Object.entries(script.photo_settings.prompts||{}).flatMap(([id,items])=>items.map(p=>({...p,segment:id}))));
 const [counts,setCounts]=useState<Record<string,number>>(script.photo_settings.frameCounts||{});
 const [provider,setProvider]=useState(script.photo_settings.provider||'api'),[model,setModel]=useState(script.photo_settings.model||models[0][0]),[style,setStyle]=useState(script.photo_settings.style||project.brief.style||'cinematic'),[format,setFormat]=useState(script.photo_settings.format||'');
 const [references,setReferences]=useState<string[]>(script.photo_settings.references||(project.brief.characters||[]).map(c=>c.referenceId||'').filter(Boolean));
 const [referenceFrames,setReferenceFrames]=useState<Record<string,string[]>>(script.photo_settings.referenceFrames||{});
 const [busy,setBusy]=useState(false),[generating,setGenerating]=useState(false),[message,setMessage]=useState(''),[prepared,setPrepared]=useState(''),[progress,setProgress]=useState(0);
 const [referenceOpen,setReferenceOpen]=useState(false),[tutorial,setTutorial]=useState(false),[preview,setPreview]=useState<Asset|null>(null);
 const settings={...script.photo_settings,provider,model,style,format,references,referenceFrames,generationPrompts:prompts,frameCounts:counts};
 const saved=useLocalSave({image_prompt:overall,photo_settings:settings},async data=>{w.putScript(await apiJson<Script>(`/api/scripts/${script.id}`,jsonBody(data,'PATCH')));});
 const refs=assets.filter(a=>a.contentType.startsWith('image/')&&a.metadata.gallery!==false);
 const own=assets.filter(a=>a.metadata.scriptId===script.id&&a.contentType.startsWith('image/'));
 const pending=own.filter(a=>a.metadata.gallery===false),pictures=own.filter(a=>a.metadata.gallery!==false&&(!active||a.metadata.segmentId===active.id));
 const validPrompts=prompts.filter(p=>frames.some(f=>f.id===p.segment));
 const total=frames.reduce((sum,f)=>sum+(counts[f.id]||0),0),estimate=imageOutputEstimate(format||'1:1');
 const frameName=(id:string)=>{const index=script.segments.findIndex(s=>s.id===id);return index<0?'Cijela skripta':`Kadar ${index+1} · ${script.segments[index].start}s – ${script.segments[index].end}s`;};
 const options=frames.map(f=>[f.id,frameName(f.id)]);
 function chooseFrame(id:string,enabled:boolean){setCounts(old=>({...old,[id]:enabled?old[id]||1:0}));if(enabled&&!prompts.some(p=>p.segment===id))setPrompts(old=>[...old,{id:crypto.randomUUID(),segment:id,text:script.segments.find(s=>s.id===id)?.prompt||''}]);}
 function addPrompt(){const id=active?.id||frames.find(f=>counts[f.id])?.id||frames[0].id;setPrompts(old=>[...old,{id:crypto.randomUUID(),text:'',segment:id}]);setCounts(old=>({...old,[id]:old[id]||1}));}
 function requestBody(segment:string,prompt:string,selectedModel=model,selectedStyle=style,selectedFormat=format,selectedReferences?:string[]){const id=segment||'overall';return {script:script.id,segment,prompt,model:selectedModel,style:selectedStyle,aspect:selectedFormat,size:selectedFormat==='9:16'?'1024x1536':selectedFormat==='16:9'?'1536x1024':'1024x1024',quality:'medium',references:selectedReferences||references.filter(ref=>!referenceFrames[ref]||referenceFrames[ref].includes(id))};}
 async function one(body:ReturnType<typeof requestBody>){if(provider==='api'){const asset=await apiJson<Asset>('/api/creative/generate',jsonBody(body));setAssets(list=>[asset,...list]);return '';}const r=await apiJson<{prompt:string}>('/api/creative/prompt',jsonBody(body));return `${frameName(body.segment)}\nModel: ${body.model}\nFormat: ${body.aspect}\nGeneriši jednu sliku navedenim modelom; nemoj ga zamijeniti drugim.\n\n${r.prompt}`;}
 async function generate(){setBusy(true);setGenerating(true);setMessage('');setProgress(0);let completed=0;try{if(!format)throw new Error('Odaberi format.');const plan=buildPhotoPlan(frames.map(f=>f.id),counts,validPrompts);if(!await saved.save())return;const output=[];for(const item of plan){output.push(await one(requestBody(item.segment,item.prompt)));setProgress(++completed);}if(provider==='chatgpt'){setPrepared(output.join('\n\n---\n\n'));setMessage('Upute spremne za ChatGPT.');}else setMessage(`Generisano ${completed} fotografija. Odaberi koje želiš ubaciti u galeriju.`);}catch(e){setMessage(`${completed?`Završeno ${completed}. `:''}${(e as Error).message}`);}finally{setBusy(false);setGenerating(false);}}
 async function accept(asset:Asset){setBusy(true);try{const updated=await apiJson<Asset>(`/api/assets/${asset.id}`,jsonBody({metadata:{gallery:true}},'PATCH'));setAssets(list=>list.map(a=>a.id===updated.id?updated:a));setPreview(null);setMessage('Fotografija je ubačena u galeriju.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function remove(asset:Asset){if(!await localConfirm('Obrisati ovu fotografiju s računara?','Obriši fotografiju','Obriši',true))return;setBusy(true);try{const r=await apiFetch(`/api/assets/${asset.id}`,{method:'DELETE'});if(!r.ok)throw new Error('Brisanje nije uspjelo.');setAssets(list=>list.filter(a=>a.id!==asset.id));setPreview(null);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function download(asset:Asset){try{const r=await apiFetch(asset.url);if(!r.ok)throw new Error('Preuzimanje nije uspjelo.');downloadBlob(await r.blob(),asset.name);}catch(e){setMessage((e as Error).message);}}
 async function regenerate(asset:Asset){setBusy(true);setMessage('');try{if(!await saved.save())return;const output=await one(requestBody(asset.metadata.segmentId||'',asset.metadata.prompt||'',asset.metadata.model||model,asset.metadata.style||style,asset.metadata.aspect||format||'1:1',asset.metadata.references));if(output)setPrepared(output);setMessage(provider==='api'?'Nova fotografija je spremna za pregled.':'Nove upute su spremne.');setPreview(null);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const actions=(a:Asset)=><div className="photo-result-actions">{a.metadata.gallery===false&&<button disabled={busy} onClick={()=>void accept(a)} title="Ubaci u galeriju"><ActionIcon name="check"/>Ubaci u galeriju</button>}<button disabled={busy} onClick={()=>void download(a)} title="Preuzmi"><ActionIcon name="download"/>Preuzmi</button><button disabled={busy} onClick={()=>void regenerate(a)} title="Ponovo generiši"><ActionIcon name="refresh"/>Ponovo generiši</button><button disabled={busy} onClick={()=>void remove(a)} title="Obriši"><ActionIcon name="trash"/>Obriši</button></div>;
 function grid(list:Asset[]){const groups=new Map<string,Asset[]>();for(const a of list){const key=(a.metadata.segmentId||'overall')+'|'+(a.metadata.aspect||format||'1:1');groups.set(key,[...(groups.get(key)||[]),a]);}return [...groups.entries()].map(([key,items])=>{const [id,ratio]=key.split('|');return <section className="photo-frame-gallery" key={key}><header><h3>{frameName(id)}</h3><p>{frames.find(f=>f.id===id)?.text}</p></header><div className={`photo-results-grid ratio-${ratio.replace(':','-')}`}>{items.map(a=><article key={a.id}><button className="photo-preview-button" onClick={()=>setPreview(a)} title="Otvori pregled fotografije"><img src={a.url} alt={a.metadata.prompt||a.name}/></button>{actions(a)}</article>)}</div></section>;});}
 return <div className="production-workspace photo-workspace"><ProjectTree photos beforeSelect={async()=>!busy&&await saved.save()}/><div className="production-photo-main"><section className="production-panel"><WorkflowSteps project={project.id} script={script.id}/><div className="production-heading compact"><div><h2>Generisanje fotografija</h2><p>{script.title}</p></div><button onClick={()=>setTutorial(true)}>Upute</button></div><fieldset disabled={busy}>
 <div className="photo-options two"><SelectField label="Generisanje" value={provider} onChange={setProvider} options={[["api","OpenAI API"],["chatgpt","ChatGPT · ručni prijenos"]]}/><SelectField label="Model" value={model} onChange={setModel} options={models} descriptions={descriptions}/></div>
 {provider==='api'&&<p className="photo-per-image-estimate">Procjena: ≈ ${estimate.usd.toFixed(3)} / fotografija + tekst i reference <small>Izlazna slika, srednji kvalitet · isti kalkulator za Flare i Sunburst</small></p>}
 <details className="photo-style-section"><summary>Vizuelni stil <Icon name="chevron"/></summary><VisualStylePicker value={style} onChange={setStyle}/></details><h3>Format</h3><FormatPicker value={format} onChange={setFormat}/>
 <section className="photo-frame-selection main-frame-selection"><h3>Kadrovi za generisanje</h3>{frames.map(f=><div className="photo-frame-choice" key={f.id}><input aria-label={`Odaberi ${frameName(f.id)}`} type="checkbox" checked={!!counts[f.id]} onChange={e=>chooseFrame(f.id,e.target.checked)}/><strong>{frameName(f.id)}</strong><p>{f.text||'Bez teksta'}</p><label>Slika<input aria-label={`Broj fotografija: ${frameName(f.id)}`} disabled={!counts[f.id]} type="number" min="1" max="10" value={counts[f.id]||1} onChange={e=>setCounts(old=>({...old,[f.id]:Math.max(1,Math.min(10,Math.trunc(Number(e.target.value)||1)))}))}/></label></div>)}<small>Odabrano fotografija: {total}</small></section>
 <label>Zajedničke upute<textarea rows={2} value={overall} maxLength={15000} onChange={e=>setOverall(e.target.value)} placeholder="Smjernice za sve kadrove…"/></label><div className="photo-prompts">{validPrompts.map((p,i)=><div className="photo-prompt" key={p.id}><header><strong>Prompt {i+1}</strong><label className="prompt-frame-checkbox"><input type="checkbox" checked={!!counts[p.segment]} onChange={e=>chooseFrame(p.segment,e.target.checked)}/>Uključi kadar</label><button title="Obriši prompt" onClick={()=>setPrompts(items=>items.filter(item=>item.id!==p.id))}><ActionIcon name="trash"/></button></header><SelectField label="Kadar" value={p.segment} onChange={id=>{setPrompts(items=>items.map(item=>item.id===p.id?{...item,segment:id}:item));setCounts(old=>({...old,[id]:old[id]||1}));}} options={options}/><blockquote><p>{frames.find(f=>f.id===p.segment)?.text}</p></blockquote><textarea aria-label={`Prompt ${i+1}`} rows={3} maxLength={10000} value={p.text} onChange={e=>setPrompts(items=>items.map(item=>item.id===p.id?{...item,text:e.target.value}:item))} placeholder="Opiši lik, radnju, okolinu i svjetlo…"/></div>)}</div><button onClick={addPrompt} disabled={validPrompts.length>=80}><ActionIcon name="plus"/>Dodaj prompt</button>
 <div className="photo-reference-heading"><h3>Reference <small>Odabrano: {references.length}</small></h3><button onClick={()=>setReferenceOpen(true)}>Odaberi i dodaj reference</button></div><p className="production-muted">Projektni likovi povezani su s njihovim referencama. Dodatne reference biraš po kadrovima.</p>
 <div className="photo-generate-footer"><button className="klipanje-primary" disabled={!format||!total} onClick={()=>void generate()}>{provider==='api'?'Generiši fotografije':'Pripremi za ChatGPT'}</button><small role="status">{saved.status} · {total} fotografija</small></div></fieldset>{generating&&<p role="status">Generisanje: {progress} / {total}…</p>}{(message||assetError)&&<p className="save-feedback" role="status">{message||assetError}</p>}
 {prepared&&<LocalDialog title="Upute za ChatGPT" wide onClose={()=>setPrepared('')}><textarea readOnly rows={12} value={prepared}/><div className="local-dialog-actions"><button onClick={()=>void navigator.clipboard.writeText(prepared)}>Kopiraj upute</button><a href="https://chatgpt.com/" target="_blank" rel="noreferrer">Otvori ChatGPT ↗</a></div></LocalDialog>}</section>
 {!!pending.length&&<section className="production-panel"><div className="production-heading compact"><h2>Generisane fotografije <small>Slika: {pending.length}</small></h2></div>{grid(pending)}</section>}
 <section className="production-panel"><div className="production-heading compact"><h2>Galerija <small>Slika: {pictures.length}</small></h2><label className="production-upload">+ Uvezi fotografije<input type="file" accept="image/png,image/jpeg,image/webp" multiple disabled={busy} onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setBusy(true);try{for(const file of files){const a=await uploadAsset(project.id,file,{purpose:'image',gallery:true,aspect:format||'1:1',scriptId:script.id,segmentId:active?.id||''});setAssets(list=>[a,...list]);}setMessage('Fotografije uvezene.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}/></label></div>{grid(pictures)}{!pictures.length&&<p className="production-muted">Ovdje su prihvaćene i uvezene fotografije.</p>}<div className="production-bottom"><span/><Link className="klipanje-secondary" to={`/videa?project=${project.id}&script=${script.id}`}>Nastavi na video →</Link></div></section></div>
 {preview&&<LocalDialog title={frameName(preview.metadata.segmentId||'overall')} wide busy={busy} onClose={()=>setPreview(null)} className="photo-preview-dialog"><img className="photo-full-preview" src={preview.url} alt={preview.metadata.prompt||preview.name}/><p>{preview.metadata.prompt}</p>{preview.metadata.scriptId===script.id?actions(preview):<div className="local-dialog-actions"><button onClick={()=>void download(preview)}>Preuzmi referencu</button></div>}</LocalDialog>}
 {tutorial&&<CreativeTutorial onClose={()=>setTutorial(false)}/>}
 {referenceOpen&&<LocalDialog title="Reference i kadrovi" wide busy={busy} onClose={()=>setReferenceOpen(false)}><label className="production-upload">+ Dodaj reference<input type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setBusy(true);try{for(const file of files){const a=await uploadAsset(project.id,file,{purpose:'reference'});setAssets(list=>[a,...list]);setReferences(list=>[...list,a.id]);}}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}/></label><div className="photo-reference-manager">{refs.map(a=><article key={a.id}><button className="reference-preview-button" title="Otvori referencu" onClick={()=>setPreview(a)}><img src={a.url} alt={a.name}/></button><div><label><input type="checkbox" checked={references.includes(a.id)} onChange={e=>setReferences(list=>e.target.checked?[...list,a.id]:list.filter(id=>id!==a.id))}/>{a.name}</label>{references.includes(a.id)&&<div className="reference-frame-options">{frames.map(f=><label key={f.id}><input type="checkbox" checked={!referenceFrames[a.id]||referenceFrames[a.id].includes(f.id)} onChange={e=>{const current=referenceFrames[a.id]||frames.map(f=>f.id);setReferenceFrames(old=>({...old,[a.id]:e.target.checked?[...current,f.id]:current.filter(id=>id!==f.id)}));}}/>{frameName(f.id)}</label>)}</div>}</div></article>)}</div>{!refs.length&&<p>Dodaj referentne fotografije ovdje.</p>}</LocalDialog>}
 </div>;
}
