import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ProjectTree,useSelection,useAssets} from '../components/ProductionWorkspace';
import {apiJson,apiFetch} from '../lib/api';
import {jsonBody,uploadAsset,type Script,type Asset} from '../lib/production';
import {useUnsaved} from '../lib/use-unsaved';
export function Photos(){const w=useSelection();return <><div className="production-heading"><div><p className="klipanje-eyebrow">02 / FOTOGRAFIJE</p><h1>Daj priči izgled.</h1><p>Zajednički stil, prepoznatljivi likovi i kadar za svaki interval.</p></div></div>{w.script&&w.project?<PhotoWorkspace key={`${w.script.id}:${w.params.get('segment')||''}`} script={w.script}/>:<div className="production-workspace"><ProjectTree photos/><div className="production-empty"><h2>Prvo projekat i skripta.</h2><p>Fotografije će pratiti tvoju priču kroz vremenske intervale.</p></div></div>}</>;}
function PhotoWorkspace({script}:{script:Script}){
 const w=useSelection(),project=w.project!;const {assets,setAssets,error:assetError}=useAssets(project.id);const segment=script.segments.find(s=>s.id===w.params.get('segment'));
 const [overall,setOverall]=useState(script.image_prompt),[prompt,setPrompt]=useState(segment?segment.prompt||'':script.photo_settings?.prompt||''),[provider,setProvider]=useState(script.photo_settings?.provider||'api'),[model,setModel]=useState(script.photo_settings?.model||project.brief.model||'gpt-image-2.5-flare'),[style,setStyle]=useState(script.photo_settings?.style||project.brief.style||'cinematic'),[size,setSize]=useState(script.photo_settings?.size||'1536x1024'),[quality,setQuality]=useState(script.photo_settings?.quality||'medium');
 const [references,setReferences]=useState<string[]>(script.photo_settings?.references||(project.brief.characters||[]).map(c=>c.referenceId||'').filter(Boolean).slice(0,5)),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[prepared,setPrepared]=useState('');
 const photoSettings={provider,model,style,size,quality,references,prompt:segment?script.photo_settings?.prompt||'':prompt};const dirty=overall!==script.image_prompt||Boolean(segment&&prompt!==(segment.prompt||''))||JSON.stringify(photoSettings)!==JSON.stringify({provider:script.photo_settings?.provider||'api',model:script.photo_settings?.model||project.brief.model||'gpt-image-2.5-flare',style:script.photo_settings?.style||project.brief.style||'cinematic',size:script.photo_settings?.size||'1536x1024',quality:script.photo_settings?.quality||'medium',references:script.photo_settings?.references||(project.brief.characters||[]).map(c=>c.referenceId||'').filter(Boolean).slice(0,5),prompt:script.photo_settings?.prompt||''});const leave=useUnsaved(dirty);const refs=assets.filter(a=>a.contentType.startsWith('image/'));const pictures=assets.filter(a=>a.metadata.scriptId===script.id&&a.contentType.startsWith('image/')&&(!segment||a.metadata.segmentId===segment.id));
 async function save(){const result=await apiJson<Script>(`/api/scripts/${script.id}`,jsonBody({image_prompt:overall,photo_settings:photoSettings,segments:script.segments.map(s=>s.id===segment?.id?{...s,prompt}:s)},'PATCH'));w.putScript(result);return result;}
 async function action(generate:boolean){setBusy(true);setMessage('');try{await save();const body={script:script.id,segment:segment?.id||'',prompt,model,style,size,quality,references};if(generate){const a=await apiJson<Asset>('/api/creative/generate',jsonBody(body));setAssets(list=>[a,...list]);setMessage('Fotografija je spremljena u ovaj folder.');}else{const r=await apiJson<{prompt:string}>('/api/creative/prompt',jsonBody(body));setPrepared(r.prompt);setMessage('Prompt je spreman. Kopiraj ga u ChatGPT, priloži odabrane reference i ovdje uvezi rezultat.');}}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className="production-workspace"><ProjectTree photos beforeSelect={()=>!busy&&leave()}/><div className="production-photo-main"><section className="production-panel"><div className="production-heading compact"><div><h2>{segment?`${segment.start}s – ${segment.end}s`:'Sve fotografije'}</h2><p>{script.title}</p></div><Link className="klipanje-secondary" to={`/videa?project=${project.id}&script=${script.id}`}>Složi video →</Link></div>
 <fieldset disabled={busy}><div className="production-columns"><div><label>Izvor generisanja<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="api">OpenAI API</option><option value="chatgpt">ChatGPT — ručni prijenos</option></select></label><label>Model<select value={model} onChange={e=>setModel(e.target.value)}><option value="gpt-image-2.5-flare">GPT Image 2.5 Flare</option><option value="gpt-image-2.5-sunburst">GPT Image 2.5 Sunburst</option></select></label><p className="production-muted">{model.endsWith('flare')?'Brzo generisanje novih ideja i kadrova.':'Precizne izmjene i dosljednost prema referencama.'}</p></div><div><label>Vizuelni stil<select value={style} onChange={e=>setStyle(e.target.value)}>{[['realistic','Fotorealistično'],['cinematic','Filmski'],['cartoon3d','3D cartoon'],['cartoon2d','2D cartoon'],['anime','Anime'],['watercolor','Akvarel'],['comic','Strip'],['clay','Plastelin']].map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><div className="production-columns"><label>Format<select value={size} onChange={e=>setSize(e.target.value)}><option value="1536x1024">Pejzaž</option><option value="1024x1536">Portret</option><option value="1024x1024">Kvadrat</option></select></label><label>Kvalitet<select value={quality} onChange={e=>setQuality(e.target.value)}><option value="low">Nizak</option><option value="medium">Srednji</option><option value="high">Visok</option></select></label></div></div></div>
 <label>Zajednički prompt za skriptu<textarea rows={3} value={overall} maxLength={15000} onChange={e=>setOverall(e.target.value)} placeholder="Atmosfera i izgled koji povezuju sve kadrove…"/></label>
 {segment&&<blockquote><small>NARACIJA INTERVALA</small><p>{segment.text||'Ovaj interval još nema tekst.'}</p></blockquote>}
 <label>{segment?'Opis slike za ovaj interval':'Opis pojedinačne slike'}<textarea rows={4} value={prompt} maxLength={10000} onChange={e=>setPrompt(e.target.value)} placeholder="Šta se vidi u kadru? Lik, radnja, lokacija, svjetlo…"/></label><label>Reference <small>do 5 slika; šalju se samo pri generisanju</small></label><div className="production-references">{refs.map(a=><button key={a.id} aria-pressed={references.includes(a.id)} title={a.name} onClick={()=>setReferences(list=>list.includes(a.id)?list.filter(id=>id!==a.id):list.length<5?[...list,a.id]:list)}><img src={a.url} alt={a.name}/><span>{references.includes(a.id)?'✓':''}</span></button>)}</div>{!refs.length&&<p className="production-muted">Reference likova dodaješ u <Link to={`/projekti?project=${project.id}`}>opisu projekta</Link>.</p>}
 <div className="production-row"><button onClick={async()=>{setBusy(true);try{await save();setMessage('Promptovi spremljeni.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Spremi promptove</button><button className="klipanje-primary" onClick={()=>void action(provider==='api')}>{provider==='api'?'Generiši 1 fotografiju':'Pripremi za ChatGPT'}</button></div><p className="production-muted">{provider==='api'?'Klik koristi API sredstva tvog računa. Nema automatskog generisanja.':'U ChatGPT-u odaberi svoj workspace i dostupan model. Ovdje odabrani model odnosi se na API.'}</p></fieldset>
 {busy&&<p role="status">Radim… generisanje slike može potrajati nekoliko minuta.</p>}{(message||assetError)&&<p role="status">{message||assetError}</p>}
 {prepared&&<div className="production-prepared"><label>Pripremljeni prompt<textarea readOnly rows={6} value={prepared}/></label><div className="production-row"><button onClick={async()=>{try{await navigator.clipboard.writeText(prepared);setMessage('Prompt kopiran.');}catch{setMessage('Označi i kopiraj tekst iz polja.');}}}>Kopiraj prompt</button><a className="klipanje-secondary" href="https://chatgpt.com/" target="_blank" rel="noreferrer">Otvori ChatGPT ↗</a>{refs.filter(a=>references.includes(a.id)).map(a=><a href={a.url} download key={a.id}>Preuzmi {a.name}</a>)}</div></div>}
 </section><section className="production-panel"><div className="production-heading compact"><div><h2>Galerija <small>{pictures.length}</small></h2><p>{segment?'Fotografije odabranog intervala':'Sve fotografije ove skripte'}</p></div><label className="production-upload">+ Uvezi fotografije<input type="file" accept="image/png,image/jpeg,image/webp" multiple disabled={busy} onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setBusy(true);try{for(const file of files){const a=await uploadAsset(project.id,file,{purpose:'image',scriptId:script.id,segmentId:segment?.id||''});setAssets(list=>[a,...list]);}setMessage('Fotografije uvezene.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}/></label></div><div className="production-gallery">{pictures.map(a=><article key={a.id}><a href={a.url} target="_blank" rel="noreferrer"><img src={a.url} alt={a.metadata.prompt||a.name}/></a><div><strong>{a.name}</strong><small>{script.segments.find(s=>s.id===a.metadata.segmentId)?`${script.segments.find(s=>s.id===a.metadata.segmentId)!.start}s – ${script.segments.find(s=>s.id===a.metadata.segmentId)!.end}s`:'Opći folder'}</small><a href={a.url} download>Preuzmi</a><button disabled={busy} onClick={async()=>{if(!confirm('Obrisati fotografiju? Ako je na timelineu, taj kadar će trebati zamijeniti.'))return;try{const r=await apiFetch(`/api/assets/${a.id}`,{method:'DELETE'});if(!r.ok)throw new Error('Brisanje nije uspjelo.');setAssets(list=>list.filter(i=>i.id!==a.id));}catch(e){setMessage((e as Error).message);}}}>Obriši</button></div></article>)}</div>{!pictures.length&&<div className="production-empty"><h3>Prvi kadar čeka.</h3><p>Generiši fotografiju ili uvezi sliku s računara.</p></div>}</section></div></div>;
}
