import {useEffect,useState,useRef} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {CreativeTutorial} from '../components/CreativeTutorial';
import {Icon,useAssets,useSelection} from '../components/ProductionWorkspace';
import {SelectField,ActionIcon,VisualStylePicker} from '../components/CreativeControls';
import {LocalDialog,localQuestion,localConfirm} from '../components/LocalDialog';
import {apiFetch} from '../lib/api';
import {useLocalSave} from '../lib/use-local-save';
import {useAuth} from '../context/auth-context';
import {apiJson} from '../lib/api';
import {jsonBody,uploadAsset,type Production,type Character,type Asset} from '../lib/production';
export function Projects(){
 const guard=useRef<()=>Promise<boolean>>(async()=>true);const w=useSelection(),{session}=useAuth();
 const [openId,setOpenId]=useState(w.params.get('project')||''),[adding,setAdding]=useState(false),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const opened=w.projects.find(p=>p.id===openId);
 return <><div className="production-heading"><div><h1>Projekti</h1><p>Folderi sa skriptama, fotografijama i pravilima projekta.</p></div><button className="klipanje-primary" onClick={()=>{setAdding(true);setName('');}}><Icon name="plus"/>Novi projekat</button></div>
 {adding&&<form className="production-panel production-row" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const p=await apiJson<Production>('/api/projects',jsonBody({name:name.trim(),workspace:session.workspaces[0]?.id,kind:'production',brief:{style:'cinematic'}}));w.putProject(p);setOpenId(p.id);w.select(p.id);setAdding(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Naziv projekta<input autoFocus required maxLength={160} placeholder="Serijal 1" value={name} onChange={e=>setName(e.target.value)}/></label><button className="klipanje-primary" disabled={busy||!name.trim()}>Kreiraj projekat</button><button type="button" onClick={()=>setAdding(false)}>Odustani</button></form>}
 {(error||w.error)&&<p role="alert">{error||w.error}</p>}<div className="project-folder-grid">{w.projects.map(p=><button className="project-folder-card" key={p.id} onClick={()=>{setOpenId(p.id);w.select(p.id);}}><div className="project-folder-cover"><svg viewBox="0 0 72 58" fill="none" aria-hidden="true"><path d="M5 16V9a4 4 0 0 1 4-4h18l7 8h29a4 4 0 0 1 4 4v33H5Z" fill="currentColor" opacity=".16"/><path d="M5 17h62v33H5Zm0 0V9a4 4 0 0 1 4-4h18l7 8h29a4 4 0 0 1 4 4" stroke="currentColor" strokeWidth="2" strokeLinejoin="round"/></svg><strong>{p.name}</strong><p>{p.brief.description||'Dodaj opis projekta'}</p></div><div className="project-folder-details"><span><Icon name="file"/>{w.scripts.filter(s=>s.project===p.id).length} skripti</span><span><Icon name="image"/>{p.image_count||0} fotografija</span><span>♫ {p.audio_count||0} naracija</span><small>Detalji <span>↗</span></small></div></button>)}</div>
 {!w.loading&&!w.projects.length&&<div className="production-empty"><h2>Dodaj prvi projekat</h2></div>}
 {opened&&<ProjectBook key={opened.id} project={opened} guard={guard} onClose={()=>setOpenId('')}/>}</>;
}
function ProjectBook({project,guard,onClose}:{project:Production;guard:{current:()=>Promise<boolean>};onClose:()=>void}){
 const navigate=useNavigate(),[tutorial,setTutorial]=useState(false),w=useSelection(),{assets,setAssets,error:assetError}=useAssets(project.id);const [name,setName]=useState(project.name),[brief,setBrief]=useState(project.brief),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[preview,setPreview]=useState<Asset|null>(null);
 const saved=useLocalSave({name,brief},async data=>{w.putProject(await apiJson<Production>(`/api/projects/${project.id}`,jsonBody(data,'PATCH')));},{auto:false});
 useEffect(()=>{guard.current=saved.save;return()=>{guard.current=async()=>true;};},[saved.save]);
 async function closeBook(){
  if(busy||saved.busy)return;
  if(saved.dirty){const choice=await localQuestion({title:'Spremiti izmjene projekta?',message:'Projektne postavke su promijenjene.',options:[{value:'cancel',label:'Ostani'},{value:'discard',label:'Zatvori bez spremanja'},{value:'save',label:'Spremi i zatvori',primary:true}]});if(choice==='save'){if(await saved.save())onClose();}else if(choice==='discard')onClose();return;}
  onClose();
 }
 async function deleteScript(id:string,title:string){if(!await localConfirm(`Obrisati skriptu „${title}” i njene intervale?`,'Obriši skriptu','Obriši',true))return;setBusy(true);try{const r=await apiFetch(`/api/scripts/${id}`,{method:'DELETE'});if(!r.ok)throw new Error('Brisanje nije uspjelo.');await w.reload();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}

 const refs=assets.filter(a=>a.metadata.purpose==='reference'),characters=brief.characters||[],notes=brief.notes||[],scripts=w.scripts.filter(s=>s.project===project.id);
 const changeCharacter=(id:string,patch:Partial<Character>)=>setBrief(b=>({...b,characters:(b.characters||[]).map(c=>c.id===id?{...c,...patch}:c)}));
 const chapterGroups=[{id:'',title:'Bez chaptera'},...w.chapters.filter(c=>c.project===project.id)];
 return <LocalDialog title="Detalji projekta" className="project-book-dialog" wide busy={busy||saved.busy} onClose={()=>void closeBook()}><section className="project-book"><header className="project-book-header"><div><span>PROJEKAT</span><h2 id="project-book-title">{name}</h2></div><div className="save-control"><button onClick={()=>setTutorial(true)}>Upute</button><span role="status">{saved.status}</span><button disabled={saved.busy||busy||!name.trim()} onClick={()=>void saved.save()}>Spremi</button><button disabled={busy} onClick={()=>void closeBook()}>Gotovo</button></div></header>
 <div className="project-book-pages"><div className="project-book-page"><label>Naziv projekta<input value={name} onChange={e=>setName(e.target.value)} maxLength={160}/></label><label>Opis<textarea rows={4} value={brief.description||''} maxLength={10000} onChange={e=>setBrief({...brief,description:e.target.value})}/></label>
 <details className="book-section" open><summary>Bilješke <Icon name="chevron"/></summary><div className="book-section-content">{notes.map(n=><details key={n.id} className="book-note"><summary><Icon name="file"/>{n.title}<Icon name="chevron"/></summary><label>Naziv<input value={n.title} maxLength={160} onChange={e=>setBrief({...brief,notes:notes.map(v=>v.id===n.id?{...v,title:e.target.value}:v)})}/></label><textarea aria-label={n.title} rows={5} maxLength={10000} value={n.text} onChange={e=>setBrief({...brief,notes:notes.map(v=>v.id===n.id?{...v,text:e.target.value}:v)})}/><button onClick={()=>setBrief({...brief,notes:notes.filter(v=>v.id!==n.id)})}><ActionIcon name="trash"/>Ukloni bilješku</button></details>)}<button onClick={()=>setBrief({...brief,notes:[...notes,{id:crypto.randomUUID(),title:'Nova bilješka',text:''}]})}><Icon name="plus"/>Dodaj bilješku</button>{brief.series&&<label>Serijal<textarea value={brief.series} rows={3} onChange={e=>setBrief({...brief,series:e.target.value})}/></label>}</div></details>
 <details className="book-section"><summary>Pravila i način pripovijedanja <Icon name="chevron"/></summary><div className="book-section-content"><label>Šta želimo<textarea rows={3} value={brief.desired||''} maxLength={6000} onChange={e=>setBrief({...brief,desired:e.target.value})}/></label><label>Šta izbjegavamo<textarea rows={3} value={brief.avoid||''} maxLength={6000} onChange={e=>setBrief({...brief,avoid:e.target.value})}/></label><label>Način pripovijedanja<textarea rows={3} value={brief.storyRules||''} maxLength={6000} onChange={e=>setBrief({...brief,storyRules:e.target.value})}/></label></div></details>
 <details className="book-section"><summary>Vizuelni stil <Icon name="chevron"/></summary><div className="book-section-content"><VisualStylePicker value={brief.style||'cinematic'} onChange={style=>setBrief({...brief,style})}/></div></details>
 <details className="book-section"><summary>Likovi i reference <Icon name="chevron"/></summary><div className="book-section-content"><label className="production-upload">+ Dodaj reference<input type="file" multiple accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setBusy(true);try{for(const file of files){const a=await uploadAsset(project.id,file,{purpose:'reference'});setAssets(list=>[...list,a]);}setMessage('Reference spremljene.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}/></label><div className="production-references">{refs.map(a=><button type="button" key={a.id} title="Otvori referentnu sliku" onClick={()=>setPreview(a)}><img src={a.url} alt={a.name}/></button>)}</div>{characters.map(c=><div className="book-character" key={c.id}><label>Ime lika<input value={c.name} maxLength={100} onChange={e=>changeCharacter(c.id,{name:e.target.value})}/></label><label>Izgled i osobine<textarea rows={3} maxLength={2000} value={c.description} onChange={e=>changeCharacter(c.id,{description:e.target.value})}/></label><SelectField label="Referentna slika" value={c.referenceId||''} onChange={referenceId=>changeCharacter(c.id,{referenceId})} options={[["","Bez reference"],...refs.map(a=>[a.id,a.name])]}/><button onClick={()=>setBrief({...brief,characters:characters.filter(v=>v.id!==c.id)})}><ActionIcon name="trash"/>Ukloni lika</button></div>)}<button onClick={()=>setBrief({...brief,characters:[...characters,{id:crypto.randomUUID(),name:'',description:''}]})}><Icon name="plus"/>Dodaj lika</button></div></details>
 </div><div className="project-book-page"><div className="book-script-heading"><h3>Skripte i naracije</h3><button onClick={async()=>{if(await saved.save())w.createScript(project.id);}}><Icon name="plus"/>Skripta</button></div><button className="book-add-chapter" onClick={async()=>{if(await saved.save())w.createChapter(project.id);}}><Icon name="plus"/>Dodaj chapter</button>
 {chapterGroups.filter(c=>c.id||scripts.some(s=>!s.chapter)).map(c=><details className="book-chapter" key={c.id} open><summary><Icon name="folder"/>{c.title}<small>{scripts.filter(s=>(s.chapter||'')===c.id).length}</small><Icon name="chevron"/></summary>{scripts.filter(s=>(s.chapter||'')===c.id).map(s=><details key={s.id} className="book-script"><summary><Icon name="file"/><span>{s.title}</span><span className="book-script-actions"><button type="button" title="Uredi skriptu" onClick={async e=>{e.preventDefault();if(await saved.save())navigate(`/skripte?project=${project.id}&script=${s.id}`);}}><ActionIcon name="edit"/>Uredi</button><button type="button" title="Obriši skriptu" disabled={busy} onClick={e=>{e.preventDefault();void deleteScript(s.id,s.title);}}><ActionIcon name="trash"/>Obriši</button></span><Icon name="chevron"/></summary><p>{s.content||'Skripta još nema tekst.'}</p><small>{s.segments.length} intervala · {s.segments.at(-1)?.end||0} sekundi</small><details className="book-narration-section"><summary>Naracija po intervalima <Icon name="chevron"/></summary>{s.segments.map(seg=><p className="book-narration" key={seg.id}><small>{seg.start}s – {seg.end}s</small>{seg.text}</p>)}</details><div className="book-script-links"><Link to={`/skripte?project=${project.id}&script=${s.id}`}>Uredi skriptu ↗</Link><Link to={`/fotografije?project=${project.id}&script=${s.id}`}>Fotografije ↗</Link><Link to={`/videa?project=${project.id}&script=${s.id}`}>Video ↗</Link></div></details>)}{c.id&&<button onClick={async()=>{if(await saved.save())w.createScript(project.id,c.id);}}>+ Dodaj skriptu</button>}</details>)}
 {!scripts.length&&<p className="book-empty">Dodaj skriptu da započneš. Chapteri grupišu epizode i dijelove priče.</p>}<div className="book-total">{scripts.length} skripti · {assets.filter(a=>a.contentType.startsWith('image/')).length} fotografija · {assets.filter(a=>a.contentType.startsWith('audio/')).length} naracija</div></div></div>
 {(message||assetError)&&<p className="book-message" role="status">{message||assetError}</p>}<footer><span>01 / Projektne postavke</span><span>02 / Skripte i naracije</span></footer></section>{tutorial&&<CreativeTutorial onClose={()=>setTutorial(false)}/>} {preview&&<LocalDialog title={preview.name} wide onClose={()=>setPreview(null)}><img className="photo-full-preview" src={preview.url} alt={preview.name}/><div className="local-dialog-actions"><a href={preview.url} download>Preuzmi sliku</a></div></LocalDialog>}</LocalDialog>;
}
