import {useEffect,useState,useRef} from 'react';
import {Link} from 'react-router-dom';
import {Icon,useAssets,useSelection} from '../components/ProductionWorkspace';
import {useUnsaved} from '../lib/use-unsaved';
import {useAuth} from '../context/auth-context';
import {apiJson} from '../lib/api';
import {jsonBody,uploadAsset,type Production,type Character} from '../lib/production';
export function Projects(){
 const guard=useRef(()=>true);
 const w=useSelection(),{session}=useAuth();const [adding,setAdding]=useState(false),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <><div className="production-heading"><div><p className="klipanje-eyebrow">TVOJA BIBLIOTEKA</p><h1>Projekti</h1><p>Jedno mjesto za priču, likove i sve kadrove.</p></div><button className="klipanje-primary" onClick={()=>{setAdding(true);setName('');}}><Icon name="plus"/>Novi projekat</button></div>
 {adding&&<form className="production-panel production-row" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const p=await apiJson<Production>('/api/projects',jsonBody({name:name.trim(),workspace:session.workspaces[0]?.id,kind:'production',brief:{model:'gpt-image-2.5-flare',style:'cinematic'}}));w.putProject(p);w.select(p.id);setAdding(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Naziv projekta<input autoFocus required maxLength={180} value={name} onChange={e=>setName(e.target.value)}/></label><button className="klipanje-primary" disabled={busy||!name.trim()}>Kreiraj projekat</button><button type="button" onClick={()=>setAdding(false)}>Odustani</button></form>}
 {(error||w.error)&&<p role="alert">{error||w.error}</p>}
 <div className="production-project-grid">{w.projects.map(p=><button className={`production-project-card ${p.id===w.project?.id?'selected':''}`} key={p.id} onClick={()=>{if(guard.current())w.select(p.id);}}><Icon/><strong>{p.name}</strong><p>{p.brief.description||'Dodaj opis svoje sljedeće priče.'}</p><small>{w.scripts.filter(s=>s.project===p.id).length} skripti <span>↗</span></small></button>)}</div>
 {w.project?<ProjectDetails key={w.project.id} project={w.project} guard={guard}/>:<div className="production-empty"><Icon name="folder"/><h2>Svaka priča treba svoj prostor.</h2><p>Kreiraj prvi projekat, a zatim dodaj skripte, fotografije i video.</p></div>}</>;
}
function ProjectDetails({project,guard}:{project:Production;guard:{current:()=>boolean}}){
 const w=useSelection(),{assets,setAssets,error:assetError}=useAssets(project.id);const [name,setName]=useState(project.name),[brief,setBrief]=useState(project.brief),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const dirty=name!==project.name||JSON.stringify(brief)!==JSON.stringify(project.brief);const mayLeave=useUnsaved(dirty);useEffect(()=>{guard.current=mayLeave;return()=>{guard.current=()=>true;};},[dirty]);
 const refs=assets.filter(a=>a.metadata.purpose==='reference');const characters=brief.characters||[];
 const changeCharacter=(id:string,patch:Partial<Character>)=>setBrief(b=>({...b,characters:characters.map(c=>c.id===id?{...c,...patch}:c)}));
 useEffect(()=>{setName(project.name);setBrief(project.brief);},[project.id]);
 return <section className="production-panel"><div className="production-heading compact"><div><h2>O projektu</h2><p>Ove smjernice prate sve fotografije u projektu.</p></div><button className="klipanje-primary" disabled={busy||!name.trim()} onClick={async()=>{setBusy(true);try{const p=await apiJson<Production>(`/api/projects/${project.id}`,jsonBody({name:name.trim(),brief},'PATCH'));w.putProject(p);setMessage('Opis projekta je spremljen.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Spremi projekat</button></div>
 <div className="production-columns"><div><label>Naziv<input value={name} onChange={e=>setName(e.target.value)} maxLength={180}/></label><label>O čemu je video ili projekat?<textarea rows={4} value={brief.description||''} maxLength={10000} onChange={e=>setBrief({...brief,description:e.target.value})}/></label><label>Serijal i vizuelna pravila<textarea rows={3} placeholder="Isti svijet, odjeća, atmosfera, boje…" value={brief.series||''} maxLength={10000} onChange={e=>setBrief({...brief,series:e.target.value})}/></label></div><div><label>Početni model<select value={brief.model||'gpt-image-2.5-flare'} onChange={e=>setBrief({...brief,model:e.target.value})}><option value="gpt-image-2.5-flare">GPT Image 2.5 Flare — brzi kadrovi</option><option value="gpt-image-2.5-sunburst">GPT Image 2.5 Sunburst — precizne reference</option></select></label><label>Početni stil<select value={brief.style||'cinematic'} onChange={e=>setBrief({...brief,style:e.target.value})}>{[['realistic','Fotorealistično'],['cinematic','Filmski'],['cartoon3d','3D cartoon'],['cartoon2d','2D cartoon'],['anime','Anime'],['watercolor','Akvarel'],['comic','Strip'],['clay','Plastelin']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><div className="production-reference-heading"><h3>Reference projekta</h3><label className="production-upload">+ Dodaj slike<input type="file" accept="image/png,image/jpeg,image/webp" multiple disabled={busy} onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setBusy(true);try{for(const file of files){const a=await uploadAsset(project.id,file,{purpose:'reference'});setAssets(list=>[...list,a]);}setMessage('Reference su spremljene.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}/></label></div><div className="production-references">{refs.map(a=><a href={a.url} download key={a.id} title={a.name}><img src={a.url} alt={a.name}/></a>)}</div>{!refs.length&&<p className="production-muted">Učitaj izgled likova ili primjere ambijenta.</p>}</div></div>
 <div className="production-heading compact"><h3>Likovi</h3><button onClick={()=>setBrief({...brief,characters:[...characters,{id:crypto.randomUUID(),name:'',description:''}]})}><Icon name="plus"/>Dodaj lika</button></div><div className="production-character-grid">{characters.map(c=><div className="production-character" key={c.id}><label>Ime lika<input value={c.name} maxLength={100} onChange={e=>changeCharacter(c.id,{name:e.target.value})}/></label><label>Izgled i osobine<textarea rows={3} maxLength={2000} value={c.description} onChange={e=>changeCharacter(c.id,{description:e.target.value})}/></label><label>Referentna slika<select value={c.referenceId||''} onChange={e=>changeCharacter(c.id,{referenceId:e.target.value})}><option value="">Bez reference</option>{refs.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><button onClick={()=>setBrief({...brief,characters:characters.filter(item=>item.id!==c.id)})}>Ukloni lika</button></div>)}</div>
 <div className="production-row"><button onClick={()=>w.createScript(project.id)}><Icon name="plus"/>Dodaj skriptu</button><Link className="klipanje-secondary" to={`/skripte?project=${project.id}`}>Skripte →</Link><Link className="klipanje-secondary" to={`/fotografije?project=${project.id}`}>Fotografije →</Link><Link className="klipanje-secondary" to={`/videa?project=${project.id}`}>Video →</Link></div>{(message||assetError)&&<p role="status">{message||assetError}</p>}</section>;
}
